### ISSUE TITLE
OAuth funktioniert nicht außerhalb einer Organisation

### ISSUE THREAD

**Issue by MalteSehmer** [hellohq-io/hellohq.docs#101]
### Stand:

Wir haben eine OAuth App erstellt und wir können uns mithilfe von OAuth bei HelloHQ authentifizieren.

### Problem:

Das einloggen funktioniert aber nur mit Accounts die in der selben HelloHQ "Organisation" (subdomain) sind. Wenn wir uns mit einem Account mit OAuth authentifizieren wollen der nicht in der OAuth Organisation ist, welche den OAuth Client erstellt hat bekommen wir beim einloggen auf der Seite: "Invalid user or password" angezeigt.

Wir wollen aber das sich "jeder" HelloHQ Nutzer mit OAuth authentifizieren können und nicht nur die in der selben Organisation (in welcher auch der OAuth Client im Admin angelegt wurde).

Wie können wir erreichen das sich "jeder" authentifizieren kann? 

_Viele Grüße Malte von CLINQ_

**Comment by monderino** [comment]
Hey Malte,

es gibt keine zentrale Möglichkeit. Jeder helloHQ Kunde hat seine OAuth Clients die er verwalten kann.
Daher müsste für jeden Nutzer eurer app auch die ClientId und das ClientSecret aus der des entsprechenden helloHQ Systems hinterlegt werden.

Viele Grüße
Sven
