### ISSUE TITLE
Possibility to Update and Delete PlannedRevenues

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#103]
**Describe**
Hi guys, its me again :)

Is it possible to Update and Delete the Recurring-Planned Revenues?

Last time you created the possibility to create planned revenues for QUotations and this works very fine. 

Now they asked me for example to "update" the Start/EndDate for the Recurring Planned Revenues so that the user can for example cancel (delete) or update the start date of the recurring planned revenue.

Is it possible via API?

Thanks for your help,
Thoren

**Comment by donnercody** [comment]
Hei @monderino 

sorry i think i need to concretize.

I can chang the start and end date for the "planned revenue" - but not for the "recurrence" right?

Here is a screenshot to explain what i mean:
![Screenshot 2023-06-06 at 10 12 14](https://github.com/hellohq-io/hellohq.docs/assets/41285052/41742053-a3ee-475d-b7df-a1db2c64a7f1)

I want to change the "planned revenue" that leads to the child planned revenues. And i have not found a API endpoint to modify this.

To find the planned revenues i currently use this:
/v1/PlannedRevenues?$filter=ProjectId eq 3466

Thanks for your help,
Thoren

**Comment by monderino** [comment]
Your issue is to identify the parent planned revenue, correct?
If that is the case, I can check if we can add some identifier.

Best Sven

**Comment by donnercody** [comment]
I mean, if i receive all "PlannedREvenues" even the "Parent" in the API Endpoint /v1/PlannedRevenues - than YES.

I thought i only receive the "children" with this Endpoint.

But a delete route is event not available isnt it? Because how can i delete the "parent" object?

Thanks for your help!

**Comment by patrickkurras** [comment]
hi @donnercody,

I added a new endpoint to delete planned revenues. This will be online from tomorrow.

To the generell structure: If the interval of the planned revenue is "once", the Recurrence.Id ist the same as the Id of the planned revenue. If not, the Recurrence.Id is the Id of the Parent. So if you want to delete the whole planned revenue or to change the interval, you have to use the Recurrence.Id as the Id in your call.

You can delete both, a child planned revenue as also the whole planned revenue itself.

I hope this answers your questions.

Best Patrick

**Comment by donnercody** [comment]
Perfect - i have tested it and it works fine for me.
