### ISSUE TITLE
Create a Planned Revenue from a quotation works only when done via frontend.

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#104]
**Describe the bug**
In the last weeks you supported the method to "create a planned Revenue" with the "interval" feature. This works awesome!

But this only works when i create the Quotation via Frontend and not via API. But when i edit the Quotation via Frontend and "save it" than i can create it. Maybe there is some hidden field i missed? 

You can test it with the link down there, cause i think it maybe only happen within our tenant? Feel free to create and delete the planned revenue there we dont use the feature currently, cause thats the last problem we encountered.

**To Reproduce**
1. curl --location 'https://api.hqlabs.de/v1/Quotations(115256)/do.CreatePlannedRevenue' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer your-bearer' \
--data '{"StartDate": "2023-06-12T14:25:40.61Z", 
              "EndDate": "2023-09-12T14:25:40.61Z", 
              "Interval": "Monthly", 
              "Probability": 0, 
              "LeadId": 0}'
2. The error occurs:

Oops! Sorry, something went wrong. Please contact us in our developer portal at https://developer.helloHQ.io so we can assist you.

![image](https://github.com/hellohq-io/hellohq.docs/assets/41285052/9d239dac-bbeb-4483-a688-b9f6da08cdd9)

**Expected behavior**
I want to create the planned revenue. But currently it does not work. 

But when i "edit" the Quotation via Frontend (see screenshot) than it worked. What am i doing wrong?

**Screenshots**
![Screenshot 2023-06-12 at 16 24 50](https://github.com/hellohq-io/hellohq.docs/assets/41285052/2a1d5a96-6e8d-42d0-b0cd-73f47b20e684)

If you need a bearer to test it out, let me know.

**Comment by donnercody** [comment]
Sorry - think it was my failure. When there is no "ContactPerson" Set, the creation crashes.

**Comment by patrickkurras** [comment]
hi @donnercody,

the contact person should be mandatory to create a planned revenue. Let me check that and I'll get back to you.

Best Patrick

**Comment by patrickkurras** [comment]
@donnercody I tested it without a Contact person, but it worked for me. Can you send me a link from your hellohq system and the document id via email to patrick.kurras@everii.io?
