### ISSUE TITLE
URGENT: Fetch all Quotations for a Project by its ProjectId does not work since 1PM, but worked before perfectly.

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#106]
**Describe the bug**
We fetch all Quotations for a specific Project to show them in a Treeview. Normally when i fetch the Quotations by the "ProjectId" it works fine. Since 1pm it doesnt work anymore but the data has not changed.

**To Reproduce**
1. Fetch All Quotations by ProjectId:
GET https://api.hqlabs.de/v1/Quotations?$filter=ProjectId eq 102294
The Result is:
{
    "@odata.context": "http://api.hqlabs.de/v1/$metadata#Quotations",
    "value": []
}

2. Check the screenshot in the project:
![Screenshot 2023-06-14 at 14 47 40](https://github.com/hellohq-io/hellohq.docs/assets/41285052/9f802031-f769-4382-8473-63ed8d6b6a99)

3. Fetch one specific Quotation where we know its inside the Project:
GET https://api.hqlabs.de/v1/Quotations(115346)
![Screenshot 2023-06-14 at 14 58 29](https://github.com/hellohq-io/hellohq.docs/assets/41285052/c625d5c6-7602-4c68-b78d-acc0e5c757af)

**Expected behavior**
My expectation is that i receive the List of the 3 quotations of the project by its project id as it did before today.

Urgent:
Sorry but tomorrow is a presentation where we wanted to show our new workflow to hundreds of people. We worked on it since weeks and now it doesnt work one day before :( @monderino  or @patrickkurras  can you please help us very urgent?

Our Tenant is: agentur-id

Thanks,
Thoren

**Comment by donnercody** [comment]
Hmm, some hours later, it suddenly works and the same api call gives this:

![Screenshot 2023-06-14 at 19 38 19](https://github.com/hellohq-io/hellohq.docs/assets/41285052/9f4c90a0-0519-4736-8350-c87acd356873)

Can you imagine why it works now and has not worked till the whole day?

Main thing is we can do our presentation tomorrow 👍

**Comment by monderino** [comment]
Hi @donnercody,

Sorry for the late response. Currently I can not image why this should not work. 
If it happens again please let me know and good look for tomorrow.

Best
Sven

**Comment by donnercody** [comment]
@monderino thanks. It worked fine last week because "suddenly" it worked again.

But now we are live, and have the same problem again. Maybe you can directly look here (I think later on it maybe works again). 

Here is the Link of the Project that has some quotations:
https://***.hellohq.io/hqframe?menuitemid=21093&url=projekte_details_belege&belegid=115576&projektid=102359

And when i then search for the quotations with the ID "102359", this happens:
![Screenshot 2023-06-19 at 16 34 36](https://github.com/hellohq-io/hellohq.docs/assets/41285052/3fdd435d-373b-464c-8fe6-defbea620793)

So here is the corresponding curl:
`curl --location --request GET 'https://api.hqlabs.de/v1/Quotations?%24filter=ProjectId%20eq%20102359' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <bearer>' `

**Comment by monderino** [comment]
Hi,

ok I check

**Comment by monderino** [comment]
Hey, 

I guess it's related to our cache, which have sometimes not the latest version of data for your case!
How often do you do this call?

Could you please tell me the next time again when it happen?

Best 
Sven

**Comment by donnercody** [comment]
Hm. It seems really that this is your caching.

We call this very often. But in most time it works its only "sometimes" that it doesnt work.

We now have a "maintenance" mode when this happens again.

So you can close this.

Thanks!!

**Comment by donnercody** [comment]
@monderino soemtimes it happens between 3pm and 7pm on daily basis.

Is it possible to "clean" the cache for our tenant?

**Comment by monderino** [comment]
@donnercody 
Currently this is a manual step I need to todo....

Would be really good if you could tell me when it's happening (with the get call). And then I will check again if I can solve the issue with a reset.

If this is the case I will think about how we can fix this issue

**Comment by donnercody** [comment]
@monderino Now it happened again.

If you try to get all quotations for a Project you get "empty" list, but in the frontend its working fine.

https://api.hqlabs.de/v1/Quotations?$filter=ProjectId eq 102581

![Screenshot 2023-06-30 at 12 45 02](https://github.com/hellohq-io/hellohq.docs/assets/41285052/3dadd1ea-5636-4494-b03b-eb196f482b96)

**Comment by monderino** [comment]
Yes it's the cache... 
I will try to find a way to solve this issue! Let's see if I find a solution.

Best
Sven

**Comment by donnercody** [comment]
Thanks a lot! Already sent you an email. Sorry for pushing this.

**Comment by monderino** [comment]
All good ;)

**Comment by donnercody** [comment]
Hi @monderino ,

today in the morning we had again problems with the cache.

**Comment by donnercody** [comment]
@monderino 
 it has not changed till now:
https://api.hqlabs.de/v1/Quotations?$filter=ProjectId eq 102612

If you call this, you get nothing, but in the frontend there is a Quotation.

Is there any other possibility how to "get all quotations" for a project? If yes, maybe that could help us to avoid the Cache?

**Comment by donnercody** [comment]
@monderino can you please clean the cache again? We have the problem again and its a little critical.

**Comment by donnercody** [comment]
@monderino THANKS :)
