### ISSUE TITLE
Anlegen einer Company über die API taucht nicht im Frontend auf

### ISSUE THREAD

**Issue by dzinzius** [hellohq-io/hellohq.docs#107]
Hallo,

Ich habe über die API eine Firma angelegt, die existiert auch in der API (ich kann sie abfragen), kann diese im Frontend aber nicht sehen:
 
{
  "@odata.context": http://api.hellohq.io/v1/$metadata#Companies/$entity,
  "Name": "Peter  Meiers",
  "IndustrialSector": "sadfsdgfwseg",
  "Description": "312r132r",
  "IBAN": null,
  "BIC": null,
  "DebitorNumber": null,
  "CreditorNumber": null,
  "TaxId": null,
  "DefaultDeliveryConditionId": null,
  "DefaultPaymentConditionId": null,
  "Id": 61037,
  "CreatedBy": 11014,
  "UpdatedBy": 11014,
  "CreatedOn": "2023-06-07T13:53:21.07Z",
  "UpdatedOn": "2023-06-07T13:53:21.41Z"
}
 
Frage 1: Woran liegt das?
 
Frage2: Woran erkenne ich in der API Doku die Pflichtfelder?

Vielen Dank

David

**Comment by dzinzius** [comment]
Frage 1 konnte ich lösen, es muß ein CompanyType zugeordnet werden

Damit wäre Frage 2 noch wichtiger. Gibt es eine Dokumentation der Pflichtfelder und der Abhängigkeiten?

**Comment by patrickkurras** [comment]
Hallo @dzinzius ,

freut mich, das du das erste Problem lösen konntest. Du hast recht, eine Company muss einen Type haben um in der UI sichtbar zu sein.

in unserer aktuellen Doku sind die Pflichtfelder leider nicht gut zu erkennen. Ich werde das allerdings einmal aufnehmen, damit wir dafür eine besser Lösung finden.

Wenn du dadurch ein bestimmen Stellen nicht weiter kommst, stelle deine Fragen gerne wieder hier.

Viele Grüße
Patrick

**Comment by dzinzius** [comment]
Hallo Patrick,

vielen Dank. Ich habe allerdings noch ein Frage, über welche Entität kann ich die Kunden Nr. bzw. die Interessenten Nr. setzen?

Viele Grüße

David

**Comment by patrickkurras** [comment]
Hallo @dzinzius,

die kannst mit dem dem CompanyType zusammen setzt im Feld CompanyType.Number. Ein Beispiel poste ich weiter unten. Das geht allerdings nur, wenn in der UI kein Nummernkreis für den CompanyType aktiv ist. Dann wird die Nummer vom System automatisch erstellt.
Die kannst du in der UI Admin > Standardwerte > Unternehmenstypen überprüfen.

`{
    "Name": "Peter Meiers",
    "IndustrialSector": "sadfsdgfwseg",
    "Description": "312r132r",
    "IBAN": null,
    "BIC": null,
    "DebitorNumber": null,
    "CreditorNumber": null,
    "TaxId": null,
    "DefaultDeliveryConditionId": null,
    "DefaultPaymentConditionId": null,
      "CompanyTypes": [
    {
      "Name": "Kunde",
      "Number": "Nummer 1234"
    }
  ]
}
`

Viele Grüße
Patrick

**Comment by dzinzius** [comment]
Super danke, hat geklappt
