### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Thomstar87** [hellohq-io/hellohq.docs#109]
Hallo,
wir ziehen für ein Reporting über folgenden Link Daten:
http://reportings.add2.space/hq?s=2023-05-01&e=2023-05-31
Das ganze läuft dann in Excel Power Query rein und wird weiter verarbeitet.
Leider werden über diesen Link nicht alle Mitarbeiter ausgewiesen, sondern nur Mitarbeiter des Teams Kreation".  Wir bräuchten aber alle Mitarbeiter ausgewiesen. Das ganze wurde von einem Kollegen eingerichtet, der leider nicht mehr da ist. Ich weiß nicht, an welcher Stelle ich da was anpassen kann. Könnt ihr hier vlt weiter helfen? Danke und LG, Thom

**Comment by monderino** [comment]
Hi Thom,

du benötigst leider Zugriff auf den Code aus der Power Query, da dies keine von unseren API URL's ist und ich daher nicht nachvollziehen kann was passiert.
Ohne den Code und eine Möglichkeit da etwas anzupassen müsstet ihr das sonst eventuell neu bauen.

Tut mir leid das ich hier nicht weiterhelfen kann.

Viele Grüße
Sven

**Comment by Thomstar87** [comment]
Hi Svenson,

Trotzdem Danke für die Info 😊

LG,

Thom

Thomas Winkels
Junior Finance Manager
T +49 211 54038 130
F +49 211 54038 150
***@***.******@***.***>
www.add2.de
***@***.***
add2 GmbH | Kaistraße 16a | 40221 Düsseldorf | Germany
HR 39514 Amtsgericht Düsseldorf | CFO/COO Burkhard Rischer | CEO Simon Kathmann

Diese Nachricht kann vertrauliche Informationen enthalten und ist nur für den Adressaten bestimmt.
Sollten Sie diese Nachricht irrtümlich erhalten haben, teilen Sie dies bitte dem Absender mit
und vernichten Sie diese Mail mitsamt den Anlagen. Vielen Dank.

This message may contain confidential and privileged information. If received in error,
please reply to advise the sender of the error and delete this message. Thank you.


Von: Svenson ***@***.***>
Gesendet: Mittwoch, 21. Juni 2023 08:42
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Thomas Winkels ***@***.***>; Author ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] Question (Issue #109)


Hi Thom,

du benötigst leider Zugriff auf den Code aus der Power Query, da dies keine von unseren API URL's ist und ich daher nicht nachvollziehen kann was passiert.
Ohne den Code und eine Möglichkeit da etwas anzupassen müsstet ihr das sonst eventuell neu bauen.

Tut mir leid das ich hier nicht weiterhelfen kann.

Viele Grüße
Sven

**Comment by Thomstar87** [comment]
Hi Sven,

Schau mal die folgenden Dimensionen benötigen wir (siehe Screenshot).
Leider lassen sich die so nicht über das Excel Add-In ziehen.

Gibt es da eventuell eine andere Lösung?

***@***.***


Danke und mfg,

Thomas Winkels
Thomas Winkels
Junior Finance Manager
T +49 211 54038 130
F +49 211 54038 150
***@***.******@***.***>
www.add2.de
***@***.***
add2 GmbH | Kaistraße 16a | 40221 Düsseldorf | Germany
HR 39514 Amtsgericht Düsseldorf | CFO/COO Burkhard Rischer | CEO Simon Kathmann

Diese Nachricht kann vertrauliche Informationen enthalten und ist nur für den Adressaten bestimmt.
Sollten Sie diese Nachricht irrtümlich erhalten haben, teilen Sie dies bitte dem Absender mit
und vernichten Sie diese Mail mitsamt den Anlagen. Vielen Dank.

This message may contain confidential and privileged information. If received in error,
please reply to advise the sender of the error and delete this message. Thank you.


Von: Svenson ***@***.***>
Gesendet: Mittwoch, 21. Juni 2023 08:42
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Thomas Winkels ***@***.***>; Author ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] Question (Issue #109)


Hi Thom,

du benötigst leider Zugriff auf den Code aus der Power Query, da dies keine von unseren API URL's ist und ich daher nicht nachvollziehen kann was passiert.
Ohne den Code und eine Möglichkeit da etwas anzupassen müsstet ihr das sonst eventuell neu bauen.

Tut mir leid das ich hier nicht weiterhelfen kann.

Viele Grüße
Sven

**Comment by Thomstar87** [comment]
Hallo,

Schau mal die folgenden Dimensionen benötigen wir (siehe Screenshot).
Leider lassen sich die so nicht über das Excel Add-In ziehen.

Gibt es da eventuell eine andere Lösung?
<img width="948" alt="HQ" src="https://github.com/hellohq-io/hellohq.docs/assets/131436942/e75688f5-e620-4892-8d50-9ccbabdc0ecb">

**Comment by monderino** [comment]
Alles ich leite das weiter.

Viele Grüße

**Comment by Thomstar87** [comment]
hallo, habe bisher noch keine Rückmeldung erhalten.

LG

Thom

**Comment by monderino** [comment]
Moin, 

ich hoffe du hast nun ne Mail bekommen.

LG
