### ISSUE TITLE
CustomerWebservices SOAP Endpunkte auf REST  

### ISSUE THREAD

**Issue by johtesk** [hellohq-io/hellohq.docs#110]
Sehr geehrte Damen und Herren,
ich bearbeite gerade einen unserer Services, bei dem wir in der früheren Version von HqLabs, einen SOAP CustomerWebservice zwecks Auftragsübertragung von SixOmc genutzt haben.

 
Gibt es bei der aktuellen API einen REST-Endpunkt der das gleiche macht?

BG

**Comment by monderino** [comment]
Hi @johtesk ,

alle Endpoints findest du hier: https://developer.hellohq.io/apidocs/
Ich habe leider keinen Überblick darüber wie diese Schnittstelle aussah und welche Daten dort transferiert wurden. Es klingt auf jeden Fall nach einem größeren Projekt für mich. 

Wenn du möchtest kann ich gerne einen Kontakt zu unserem Customer Success Manger herstellen

Viele Grüße
Sven

**Comment by monderino** [comment]
I close this issue, because there is no response.
