### ISSUE TITLE
Aufträge per API

### ISSUE THREAD

**Issue by elbym** [hellohq-io/hellohq.docs#111]
Hallo Team HQ, 

wo finde ich die Auftragsbestätigungen in der API?

**Comment by monderino** [comment]
Hi @elbym,

aktuell haben wir keine Endpoints für Aufträge. 
Dies wird sich auch erst mit einer neuen Version der API ändern. An dieser arbeiten wir gerade, wissen jedoch noch nicht wann wir diese Online zur Verfügung stellen können

Viele Grüße
Sven
