### ISSUE TITLE
API Swagger documentation

### ISSUE THREAD

**Issue by ascky-alex** [hellohq-io/hellohq.docs#112]
**Describe the bug**

Trying out the API on https://developer.hellohq.io/apidocs/#/Leads%20-%20Leads/post_v1_Leads results in a 500 status response

**To Reproduce**
1. Go on website https://developer.hellohq.io/apidocs/#/Leads%20-%20Leads/post_v1_Leads
2. Click "Try out" button
3. Look at result 

**Expected behavior**
Either a 200 or 400 group http status response

**Screenshots**

**Environment (please complete the following information):**
 - OS: OSX 13.3 (22E252)
 - Browser Chrome 
 - Version 114.0.5735.133 (Official Build) (arm64)

**Comment by monderino** [comment]
Hi @ascky-alex,

wo do not support the 'Try out' function in swagger. Please use a tool Like Postman or insomnia for testing.

Best
Sven
