### ISSUE TITLE
Application Token

### ISSUE THREAD

**Issue by ascky-alex** [hellohq-io/hellohq.docs#113]
The api offers an auth flow for user authentication. Is there something similar for an app level access? I see you provide client id and secret but I still need to go through a user auth flow? 

Is there a different process for machine to machine connection without user interaction? Is there a way to get the token without manual user login?

I can also see the token in the admin interface of my hello HQ account. Can I use this instead?

**Comment by monderino** [comment]
Hi @ascky-alex,

in the OAuth Flow we need the client id and secret to identify which client you are.

Yes, in our Admin interface we show an api token to you. That one you can use for case to connect machine to machine. But here you cannot specify a specific user. 

Best 
Sven

**Comment by monderino** [comment]
I close this issue, because there is no response.
