### ISSUE TITLE
Is it possible to use the quotation states "Freigabe1" and "Freigabe2" 

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#114]
**Describe**
We want to use the Status "Warten auf Feedback" or "Freigabe 1" and "Freigabe 2" inside of the Quotations.

![MicrosoftTeams-image (4)](https://github.com/hellohq-io/hellohq.docs/assets/41285052/09cfbd77-06f5-4158-8a72-3d2f56420756)

**Additional context**
When i try to set or read the quotation of the API and the Status is set to "Freigabe 1" i receive the Status "Draft". Is it possible to receive "Feedback1".

Thanks,
Thoren

**Comment by monderino** [comment]
Hi,

sure we will check it.

Best Sven

**Comment by monderino** [comment]
Hi @donnercody,

you should post and get quotation with value Share1 and Share2 now.

Best
Sven

**Comment by donnercody** [comment]
Maybe you are interested in what we have built with your api?

**Comment by monderino** [comment]
Yes, of course 👍🏻 

You can find my mail address in my github profile.

**Comment by Schaukelking** [comment]
Due to low activity here I'll close this issue. Seems to be resolved (:
