### ISSUE TITLE
HQ-API-Access for excel

### ISSUE THREAD

**Issue by lisabuedel** [hellohq-io/hellohq.docs#115]
Ich habe in Excel die HQ-API-Excel eingerichtet, um mir die Daten aus dem HQ aktuell in meine Controlling-Auswertungen zu ziehen. Seit einiger Zeit lädt die Tabelle IncomingInvoices nicht mehr. Der Status ist "09:19:20 -Loading data for table IncomingInvoices from HQ-API" und von da aus geht es nicht weiter, auch wenn ich ne Stunde warte. 

**To Reproduce**
API Access laden
"Daten Aktualisieren" drücken oder Tabel Incoming Invoices auswählen und "Tabelle hinzufügen" drücken

**Expected behavior**
Die Tabelle mit den Eingangsrechnungen sollte geladen bzw. aktualisiert werden

**Screenshots**
![Bildschirmfoto 2023-06-28 um 09 28 49](https://github.com/hellohq-io/hellohq.docs/assets/137990126/b99a94f6-45f2-44d1-a1f1-6e36fea01b01)

**Environment (please complete the following information):**
 - iOS
 -Microsoft Excel für Mac, Version 16.74

**Comment by monderino** [comment]
Hi @lisabuedel,

Ich könnte mir denken das es and den Daten in euren Eingangsrechnungen liegt. Nennst du mir bitte deinen Firmennamen damit ich das checken kann?

Danke und viele Grüße
Sven

**Comment by lisabuedel** [comment]
livewelt GmbH & Co. KG

https://livewelt1.hellohq.io/

Bis vor ein paar Wochen funktionierte es allerdings einwandfrei.



Lisa Büdel
Chief Operating Officer | Member of the managing board

Fon.  +49 5241 21090-13
Mobil. +49 171 993 66 85

***@***.***

Die Idee
ist Bewegung.

livewelt GmbH & Co. KG
Berliner Str. 133
D-33330 Gütersloh

Unsere Datenschutzinformationen finden Sie unter: www.livewelt.de/dsgvo<http://www.livewelt.de/dsgvo>

Von: Svenson ***@***.***>
Datum: Mittwoch, 28. Juni 2023 um 09:48
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Büdel, Lisa | livewelt ***@***.***>, Mention ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] HQ-API-Access for excel (Issue #115)

Hi @lisabuedel<https://github.com/lisabuedel>,

Ich könnte mir denken das es and den Daten in euren Eingangsrechnungen liegt. Nennst du mir bitte deinen Firmennamen damit ich das checken kann?

Danke und viele Grüße
Sven

**Comment by monderino** [comment]
Hey,

Bei mir werden die Daten geladen. Aktuell habt ihr über 15000 Eingangsrechnungen und das Plugin läd die Daten in 100ter schritten. Daher dauert das laden aktuell sehr lange. Bei mir war es 10 - 15 min.

<img width="832" alt="Screenshot 2023-06-28 at 14 23 06" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/13fb058f-e1f7-4e26-84eb-281f99d0fc0e">

**Comment by lisabuedel** [comment]
Ich hab teilweise schon über eine Stunde gewartet und es ist nichts passiert.

**Comment by monderino** [comment]
Hi,

also ich habe es nun 2mal getestet und es hat jeweils rund 15 Minuten gedauert. Die Dauer kann natürlich auch von der Geschwindigkeit eures Internets abhängen.

Leider weiß ich nicht wie ich dir da noch weiterhelfen kann.

**Comment by lisabuedel** [comment]
ok, danke! Gestern hat es dann bei längerem Warten irgendwann funktioniert.
