### ISSUE TITLE
GET /v1/ProjectsTasks does not show all documented fields

### ISSUE THREAD

**Issue by nhamel-bridgecom** [hellohq-io/hellohq.docs#116]
When I execute the GET /v1/ProjectsTasks, I am not getting the fields documented like the Assignments section. Instead I am getting only the below example. I need to get the assigned people and the status of the task.

{
    "@odata.context": "http://api.hqlabs.de/v1/$metadata#ProjectTasks/$entity",
    "Name": "my task 2",
    "Order": null,
    "ParentId": null,
    "ProjectId": 13,
    "IsDone": false,
    "PlannedEffort": null,
    "PercentDone": null,
    "Description": null,
    "StartOn": null,
    "EndOn": null,
    "TaskTypeId": 1,
    "TaskTypeStatusId": 3,
    "IsAppointment": false,
    "SyncId": null,
    "Sync": null,
    "JiraProjectName": null,
    "Remaining": null,
    "ProjectBudgetId": null,
    "ChargeType": "Variable",
    "ChargeValue": 0.00000,
    "Id": 94263,
    "CreatedBy": 11010,
    "UpdatedBy": 11010,
    "CreatedOn": "2023-06-28T14:52:57.1133333Z",
    "UpdatedOn": "2023-06-28T14:52:57.1133333Z"
}

**Comment by monderino** [comment]
Hi @nhamel-bridgecom,

yes this is true. As we describe in the documentation you need to expand related objects.
For your example you have to use this call: /v1/ProjectTasks?$expand=Assignments

Best Sven
