### ISSUE TITLE
Expanding properties missing fields

### ISSUE THREAD

**Issue by jon-ovan** [hellohq-io/hellohq.docs#118]
** /v1/ContactPersons **
I see on your documentation that a field Addresses is provided on the response, and this contains the email.

I am calling the API but this field is not provided, I tried to expand the properties: /v1/ContactPersons?expand=Addresses but it does not work. Please let me know how I can obtain this field. 

Thanks in advance.

**Comment by Schaukelking** [comment]
Hey @jon-ovan 

in our documentation you can find an example for getting _companies_ with their addresses in the "Expand one property
" section: https://developer.hellohq.io/

In your case you have to call: 
`/v1/ContactPersons?$expand=DefaultAddress`

Hope this helps out
Kind regards
Patrick
