### ISSUE TITLE
API Datenexport (Mac)

### ISSUE THREAD

**Issue by matwuethrich** [hellohq-io/hellohq.docs#119]
Hallo zusammen 

Wir haben einen Datenexport über das API Plugin gemacht. Jetzt hatten wir den Fall dass jemand ein Angebot im HQ gelöscht hat.

Auf unserer Excel Auswertung ist das Angebot jedoch noch sichtbar. Das Plugin haben wir aktualisiert und wir haben versucht auch alles manuell anzustossen jedoch ist das Angebot immer noch sichtbar.
Was können wir machen damit dieses Angebot automatisch gelöscht wird über diese API Schnittstelle

**Comment by monderino** [comment]
Hi @matwuethrich,

gelöschte Daten werden nicht über eine API Endpoint zurückgegeben. Daher könnte ihr das nur manuell machen.
Entweder die Daten händisch löschen, oder alles löschen und komplett neu alles über die API holen.

Viele Grüße
Sven
