### ISSUE TITLE
API limit ContactPersons

### ISSUE THREAD

**Issue by solunic** [hellohq-io/hellohq.docs#12]
Wir lesen über die API bereits Unternehmen aus. Bei den Ansprechpartnern mit der URL https://api.hqlabs.de/v1/ContactPersons bekomme ich aber nur 1000 Personen. Wie kann ich das Limit erhöhen? Oder ist es möglich, bei der Abfrage nach CustomFields zu filtern?

**Comment by patrickkurras** [comment]
Hey,

beides ist ohne Probleme möglich nur muss du dann mehrere Calls machen um mehr als 1000 ContactPersons zu bekommen. Dazu kannst du dies einfach so machen:
`https://api.hqlabs.de/v1/ContactPersons?$skip=0`
`https://api.hqlabs.de/v1/ContactPersons?$skip=1000` usw.

Du kannst aber auch einfach nach einem CustomField filtern und die nur die ContactPersons ziehen, hier bekommst du aber auch maximal 1000 Eintrage zurück. Hier ein Beispiel um nach dem CustomField "Informationen" zu filtern, wo der Value nicht leer ist:
`https://api.hqlabs.de/v1/ContactPersons?$expand=CustomFields&$filter=CustomFields/any(customField: customField/Name eq 'Informationen' and customField/Value ne '')`

Melde dich gerne, wenn du dazu noch weitere Fragen hast.

Viele Grüße
Patrick

**Comment by solunic** [comment]
Danke für die Info. In diesem Fall ist die Variante mit dem Filter sinnvoll, da wir nur einzelne Kontakte benötigen.

Ich habe es mit diesem GET-Request versucht, bekomme aber nur einen Bad Request:
https://api.hqlabs.de/v1/ContactPersons?=CustomFields&=CustomFields/any(customField: customField/Name eq 'HubSpot ID Ansprechpartner' and customField/Value eq '1101')
