### ISSUE TITLE
Authentication Problem to the new helloHQ-API

### ISSUE THREAD

**Issue by projektagent** [hellohq-io/hellohq.docs#120]
Hello helloHQ developer-Team, 

At current time we have an authentication error to connect the new helloHQ-API. 

> The old Bearer token works but only v1 HelloHQ API:
![image](https://github.com/hellohq-io/hellohq.docs/assets/141842762/fdd45f41-baee-4aad-85cb-82a9d62b2805)

> But it seems v2 HelloHQ API it did not work, as it could be using different Authentication approach:
![image](https://github.com/hellohq-io/hellohq.docs/assets/141842762/5097a30b-8fe4-4932-83a4-ec6f5f3f7468)

Do you have an soloution proposal about this?

Thanks, 
Heiko

**Comment by monderino** [comment]
Hi @projektagent,

the API's working totally different. You cannot use the same token in v1 and v2.

For v1 you can get the token from helloHQ => Admin => API Clients.
For v2 you need to call the Authenticate/Login endpoint to generate a token. We currently build an UI to generate a token via the UI as, but this UI is not ready yet.

Best regards
Sven

**Comment by projektagent** [comment]
Hi Sven, 

thanks for the prompt feedback. We will check this.

Regards 
Heiko

**Comment by projektagent** [comment]
Hi Sven,

Can we get an example for authentication/Login to the V2 API?

Regards

Heiko

**Comment by monderino** [comment]
Hi Heiko,

sure. 

curl --location 'https://develop.hellohq.io/v2/Authenticate/Login' \
--header 'Content-Type: application/json' \
--data '{
  "userName": "peter@mustermann",
  "password": "ThisIsAPassword",
  "backendCustomerId": 11323322
}'

Choose a user from your system and add the credentials and add your customerid. Your customer id is shown in the info modal of your system.

Best Sven

**Comment by projektagent** [comment]
Hi Sven, 
Its´great.... it seems to work now for the authentication. 

Thanks and have a nice weekend.

Best Heiko
