### ISSUE TITLE
Issue on creating new company with API v2

### ISSUE THREAD

**Issue by ZHC-integration** [hellohq-io/hellohq.docs#122]
I get an error when trying to create new company without house number. For some company in my project, they could not be having house number. Wonder if this field can be made non mandatory?

URL: https://develop.hellohq.io/v2/Companies

Error:
{
  "errors": [
    {
      "propertyName": "DefaultAddress.HouseNumber",
      "errorMessage": "'House Number' must not be empty.",
      "attemptedValue": "",
      "customState": null,
      "severity": 0,
      "errorCode": "NotEmptyValidator",
      "formattedMessagePlaceholderValues": {
        "PropertyName": "House Number",
        "PropertyValue": ""
      }
    }
  ],
  "targetSite": null,
  "message": "Validation failed: \n -- DefaultAddress.HouseNumber: 'House Number' must not be empty. Severity: Error",
  "data": {},
  "innerException": null,
  "helpLink": null,
  "source": null,
  "hResult": -2146233088,
  "stackTrace": null
}

**Comment by Schaukelking** [comment]
hey @ZHC-integration,
thank you for the request. You are right, currently this mandatory. We discussed the topic already intern and will change this. I cannot say a date when this goes live, but will not take long. I will update you

Kind regards
Patrick

**Comment by ZHC-integration** [comment]
Thanks Patrick, looking forward for this change.

**Comment by Schaukelking** [comment]
Hey, the change is online now.

You still need to have the houseNumber in your body but it can be an empty string. 

Hope this helps

**Comment by ZHC-integration** [comment]
Thanks, it works now
