### ISSUE TITLE
Postal code validation error v2/Companies creation

### ISSUE THREAD

**Issue by ZHC-integration** [hellohq-io/hellohq.docs#124]
Hi,

With regards to company creation, there are some issue due to postal code validation.

Based on my checking, it due to different format of postal code that been use in different countries.

Can you check if technical team can remove this constraint into "free text"?

Error example:
"errorMessage": "Postalcode is not valid",
      "attemptedValue": "1016 EE",

"errorMessage": "Postalcode is not valid",

      "attemptedValue": "1096 AM",

"errorMessage": "Postalcode is not valid",

      "attemptedValue": "85260-1868",

**Comment by Schaukelking** [comment]
Hey, 

I will create a ticket for it. We will tackle this topic next week. Thanks for the report.

**Comment by Schaukelking** [comment]
hey @ZHC-integration 
also this problem is resolved now. We added a more generic validation. If you find another case where the postcode is not valid in our api just come here and write again!
