### ISSUE TITLE
Allow Customer-No field insert via /v2/Companies POST

### ISSUE THREAD

**Issue by ZHC-integration** [hellohq-io/hellohq.docs#125]
Hi,

I noticed the v2 swagger(https://develop.hellohq.io/swagger/index.html) doesnt describe"Customer-No" in to be insert as part of the field:

<img width="457" alt="image" src="https://github.com/hellohq-io/hellohq.docs/assets/142300267/71ea9614-d25d-4361-8bd6-5b0963da5a85">

May I know is there possibility to do so in upcoming release?

**Comment by Schaukelking** [comment]
Hey! 

I have to check how the current implementation is in the v2. 
In v2 our logic was:
We have number schemas for company types in the helloHQ! If the company you want to add is according to a company type with a number schema we do not allow setting a own number. Your passed number only will be taken, if the company type has no number schema. 

Otherwise your external input in this field will missmatch the schemas. But i still need to verify if this is

**Comment by ZHC-integration** [comment]
Hi,

The purpose of this is to add reference lookup to external backend system.

Wonder how it works with 'customFieldForCompanies', I tried to add one but it failed due to validation:

Example:
...
"customFieldForCompanies": [
    {
      "name": "SAPCompId",
      "type": "1 - Text",
      "value": "12345678"
    }
  ]

Error:
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-c2bd905c27d2b03ca06b63f1be16a36a-ccdf323713f1f125-00",
  "errors": {
    "company": [
      "The company field is required."
    ],
    "$.customFieldForCompanies[0].type": [
      "The JSON value could not be converted to HQ.SQL.Model.Enum.CustomFieldType. Path: $.customFieldForCompanies[0].type | LineNumber: 38 | BytePositionInLine: 24."
    ]
  }
}

**Comment by Schaukelking** [comment]
Hey @ZHC-integration 
Yeah you could easily resolve it with custom fields! Then the ids do not interfer with our number schemas.

2 issues:
1. Our api example is wrong. For texts you don't do  `"type": "1 - Text"` you just do `"type": 1`. 
2. You don't have a custom field defined in your system yet. As an administrator you can create customfields via UI. 
![image](https://github.com/hellohq-io/hellohq.docs/assets/48789562/fbf91d09-c231-4bb7-9ae6-9eb289a61d71)
This screenshot is from my system, I have 3 custom fields as you see. To find under Admin -> Default Settings. We currently also do not have an endpoint for you to get your customfield definitions from companies. I put this as a ticket into our sprint. 

For now i just created a custom field to your system with the name "SAPCompId". Your call should work now when you change the type to 1. 

Please give me feedback if this is fine for you know!

**Comment by ZHC-integration** [comment]
hi @Schaukelking ,

Seems something is broken, I added this but get an error.

...
"customFieldForCompanies": [
{
"name": "SAPCompId",
"type": 1,
"value": "12345678"
}
]

Error:
{"message": "Unauthorized or unexpected error"}

**Comment by Schaukelking** [comment]
If you want to, you can send me your full body (via mail, if the data is sensitive) and I will try to find the issue. And you are still trying this out on the system you sent me in the mail? I guess customFields can be very useful for you in different cases. 

And yes you can also use debitor- / creditorNumber. To use these you have to know the following:

The debitorNumber is only used in our system, when the companyType of the Company is "Kunde" which means customer. 
The creditorNumber is only used in our system, when the companyType of the Company is "Lieferant" which means supplier.

You can get all your system companyTypes via **GET** `v2/CompanyTypes`

There is also a setting in the system which causes, that the customerNumber is automatically also the debitorNumber. This is currently disabled in your system so everything should be fine.
