### ISSUE TITLE
Possibility to read the "Log Entries" for Projects

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#127]
**Describe**
We wanted to create a "workflow" logic outside of HQ and therefore read the "old statuses" the project went through.

I was wondering if it possible to read the "log entries" and generate a "status change history timeline" for myself?

For example:
/Projects(XXXX)/logs

Thanks,
Regards,
Thoren

**Comment by monderino** [comment]
Hi @donnercody,

currently we only have and endpoint to identify deletion events. To make a full sync implementation possible. This is /ConfigSystemEvents/do.GetDeleted().

But other events are currently not available.
Sorry.

Best Sven

**Comment by donnercody** [comment]
Hi Svenson,

thanks - is there a Endpoint for this button? (See screenshot)

![Screenshot 2023-09-06 at 10 51 30](https://github.com/hellohq-io/hellohq.docs/assets/41285052/66defd74-8ff4-4bf1-905e-b551665e2368)
![Screenshot 2023-09-06 at 10 51 25](https://github.com/hellohq-io/hellohq.docs/assets/41285052/ced390a8-4d34-4c38-ac10-3b12426459fe)


Sorry maybe i missed my description above.

Thanks,
Thoren

**Comment by monderino** [comment]
Hey,

I understood your question ;) But we have no endpoint for this.
Sorry.

Bets Sven
