### ISSUE TITLE
Can we update defaultAddress and companyTypes  or only selective value for Company?

### ISSUE THREAD

**Issue by ZHC-integration** [hellohq-io/hellohq.docs#128]
Based on the example in Swagger, it seems didnt show this information?

Example in real case scenario, there is a change only in Address or Company name. Can we just update this part?

Example in Swagger:
{
  "name": "everii Germany GmbH",
  "industrialSector": "IT",
  "description": "everii's cloud-based software is perfectly tailored to your needs",
  "iban": "DE75512108001245126199",
  "bic": "FRSDDEF1",
  "homepage": "https://everii.io",
  "vatId": "DE123456789",
  "financesChargeRateId": null,
  "standardDeliveryConditionId": null,
  "standardPaymentConditionId": null,
  "debitorNumber": 0,
  "creditorNumber": 0,
  "documentDefaultMailEntityId": null,
  "routingId": "1234567890123",
  "customFields": [
    {
      "name": "Random text",
      "type": "Text",
      "value": "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
    }
  ]
}

**Comment by Schaukelking** [comment]
I will tacke your requests today @ZHC-integration
