### ISSUE TITLE
Can API 2.0 allow to Get Company or Project more than 100 items?

### ISSUE THREAD

**Issue by ZHC-integration** [hellohq-io/hellohq.docs#129]
Based on query, it seems the default limit is 100 for GET method.

Is there possibilities to get the remaining items that is more than 100?

Especially company

**Comment by Schaukelking** [comment]
The max amount in one call is limited on 1000, the default limit is currently 100.  

You can do: /v2/Companies?&top=1000

if you have 1000 results you have to skip /v2/Companies?&skip=1000&top=1000 to get the next 1000. 

On our roadmap is to provide an info in the response of a get call if there are more entities than you received, so you don't have to theck the elements by your own.
