### ISSUE TITLE
How can i create an user or a resource using the API.

### ISSUE THREAD

**Issue by aJerezGit** [hellohq-io/hellohq.docs#13]
**Describe**
In the company we start using helloHQ platform, and we want to create some jobs that synchronize the information between the other platforms that we use currently, i was checking the API documentation, but in the USER section, seems like there is no exposed endpoint to create users or resources as is it call in the application. is there another option through the API that we can use to create them directly?

**Comment by patrickkurras** [comment]
Hi,

unfortunately it isn't possible to create users or resources in our api right now, you have to do it in HQ.

Kind regards
Patrick
