### ISSUE TITLE
Creating a Company or Project with a html entity character leads to wrong encoding

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#130]
**Describe the bug**
I created a Company via the API that is named "thoren & test gmbh". 

After creating it, the API responds with that name:
"thoren &amp; test gmbh;"

Also in HQ it is shown with the "&amp" entity. When i change it in HQ via frontend it works fine 

**To Reproduce**
curl --location 'https://api.hqlabs.de/v1/Companies' \
--header 'Charset: UTF-8' \
--header 'Content-Type: application/json' \
--data '{
    "Name": "test & thoren 3 gmbh",
    "CompanyTypes": [{
        "Name": "Kunde",
        "Id": 4002
    }]
}'

Response:
{
  "@odata.context":"http://api.hqlabs.de/v1/$metadata#Companies/$entity","Name":"**test &amp; thoren 4 gmbh"**,"IndustrialSector":null,"Description":"","IBAN":null,"BIC":null,"DebitorNumber":null,"CreditorNumber":null,"TaxId":null,"DefaultDeliveryConditionId":null,"DefaultPaymentConditionId":null,"Id":68734,"CreatedBy":11010,"UpdatedBy":11010,"CreatedOn":"2023-09-06T08:54:06.0866667Z","UpdatedOn":"2023-09-06T08:54:06.3233333Z"
}%

**Expected behavior**
I wanted to have the name without the html entity.

**Screenshots**
![Screenshot 2023-09-06 at 10 55 14](https://github.com/hellohq-io/hellohq.docs/assets/41285052/405e5758-313e-4cfc-a1ba-d185cef2f929)

**Comment by donnercody** [comment]
Hi @donnercody , sorry for my alarm last week.

Can you please check the "encoding" problems when you have a timeslot for it?

Thanks,
Thoren

**Comment by monderino** [comment]
Hi @donnercody,

yes I will check it.

Best Sven

**Comment by monderino** [comment]
A fix goes online tomorrow.

Best Sven

**Comment by donnercody** [comment]
Thanks a lot for your hlep!
