### ISSUE TITLE
Marking an incoming invoice/Beleg as paid

### ISSUE THREAD

**Issue by rainerpuschner** [hellohq-io/hellohq.docs#131]
Is there a way to do this via API?

Also for outgoing invoices that will be generated in HelloHQ and set via API to "paid" if they are paid in another application.

The reason i am asking is that HelloHQ and getMyInvoices do not offer that feature at the moment and it would be so good to see this!

**Comment by monderino** [comment]
Hi @rainerpuschner,

this is possible. You can find the endpoints in our documentation (https://developer.hellohq.io/apidocs/#/).

We have a do.SetStatus endpoint. For example /Invoices({id})/do.SetStatus() or /IncomingInvoices({id})/do.SetStatus().

Best Sven
