### ISSUE TITLE
Code 500 on post request

### ISSUE THREAD

**Issue by David4kraftwerk** [hellohq-io/hellohq.docs#134]
We created an app that fetches information from several endpoints. Therefore we're using https://https://api.hqlabs.de/Token
to create our new access token. If we do so, we receive code 500 in response.

**Request**
- **Request Headers**
Authorization: Basic XXX
User-Agent: PostmanRuntime/7.33.0
Accept: */*
Postman-Token: XXX
Host: api.hqlabs.de
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 274
- **Request Body**
grant_type: refresh_token
refresh_token: XXX

**Response**
- **Response Headers**
Date: Mon, 09 Oct 2023 08:56:39 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 10023
Connection: keep-alive
Cache-Control: private
Strict-Transport-Security: max-age=15724800; includeSubDomains

- **Response Body**
Source Error: 
"An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below."
Stack Trace:
[NullReferenceException: Object reference not set to an instance of an object.]
   Microsoft.Owin.Security.OAuth.<InvokeTokenEndpointAsync>d__22.MoveNext() +3343
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.OAuth.<InvokeAsync>d__0.MoveNext() +1248
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +535
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +768
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +768
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Cors.<Invoke>d__0.MoveNext() +1012
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Web.Http.Owin.<InvokeCore>d__0.MoveNext() +2291
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   HQSB.API.<Invoke>d__1.MoveNext() in D:\a\hq-legacy\hq-legacy\HQSB.API\RewriteUrlMiddleware.cs:19
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<RunApp>d__5.MoveNext() +197
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.<DoFinalWork>d__2.MoveNext() +184
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.StageAsyncResult.End(IAsyncResult ar) +124
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +510
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +232
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +140

**Expected behavior**
Response should contain new access/refresh token.

**Environment (please complete the following information):**
- We used postman for testing

**Additional context**
The way we set this up in our app used to work for almost a year now. The request we sent is still strucured like the one mentioned above

**Comment by monderino** [comment]
Hey @David4kraftwerk,

can you please add an example request as curl for example.

Please do not forget to remove the refreshtoken.

Thanks, best
Sven

**Comment by David4kraftwerk** [comment]
Hey @monderino,

here is the curl:

curl -k -i --raw -o 0.dat -X POST -d "grant_type=refresh_token&refresh_token=XXX" "https://api.hqlabs.de/Token" -H "Host: api.hqlabs.de" -H "Authorization: Basic XXX" -H "Accept-Encoding: gzip, deflate" -H "Content-Type: application/x-www-form-urlencoded"

Thank u, best regards,
David

**Comment by monderino** [comment]
Hey @David4kraftwerk,

there are many values not set.
Another member had the same issue in the past. Here the link of the issue entry: https://github.com/hellohq-io/hellohq.docs/issues/94#issuecomment-1547874726

Please let me know if this helped you.

Best
Sven

**Comment by David4kraftwerk** [comment]
@monderino 

thanks i'll look into that. Just a little side note (maybe important), we've been using the req. mentioned above for almost a year now and it suddenly stopped working on sunday.

I'll get back to you when everything works!

Thanks in advance.

Best regards,
David

**Comment by monderino** [comment]
Oh ok, thank you very.
I will debug it and let you know.

**Comment by monderino** [comment]
Hey @David4kraftwerk,

I guess your request is wrong. You need to add all parameter in the request body and not as part of the url.
See my Postman request:
<img width="1406" alt="Screenshot 2023-10-10 at 13 46 43" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/a82d66be-7b06-415e-94a5-cbf1a415c6b3">

**Comment by monderino** [comment]
Do you use the same redirect_uri you used for getting the initial token?
I could image that is the issue. The redirect_uri to get the access token and later to get the refresh token needs to be the same.

**Comment by monderino** [comment]
In Postman you can create really easy a new access and refresh token.
Just create a new get call and setup the Authorization Tab like the example of the Screenshot. You just need to add your helloHQ Credentials in a Popup you get and that's it.
<img width="1109" alt="Screenshot 2023-10-10 at 17 35 17" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/013db633-c9b4-4fa8-86e8-e451b11cdd0f">

I did the same process and with the refresh_token you get, also the other call will work.
I hope this will work for you.

Best
Sven

**Comment by David4kraftwerk** [comment]
@monderino 

thx i've set this up the way you've suggested it and the error is now different:
![image](https://github.com/hellohq-io/hellohq.docs/assets/119495092/7cda65fd-e8e7-4600-b852-43b4c94324aa)

Is there the possibility that the calls themselves aren't the issue? For instance the for some reason the user that was used to initially authentificate the app doesn't exist anymore?

Best regards,
David

**Comment by David4kraftwerk** [comment]
Hey @monderino,

thanks! Forwarded a mail to you.

Best regards,
David
