### ISSUE TITLE
Error on Posting Reportings via c# SDK 

### ISSUE THREAD

**Issue by siegelpeter** [hellohq-io/hellohq.docs#135]
**Describe the bug**
Each Month we import our time booking (Reportings) via the Rest API (c# SDK). This Time we sometimes get and error code 500 when calling CreateReportingsByIdAsync

Sometimes when retrying the call it works. Is there some Problem with the API? There is no helpfull errormessage in the response content.
![grafik](https://github.com/hellohq-io/hellohq.docs/assets/3708070/8b189e3c-a207-4360-b6eb-c9f4e8010fd3)

Do you see any helpfull info in the server logs?

Is there some kind of throtteling in place. Because retrying the request seems to help?

This happens on our tenant verticalcodes.hellohq.io

**Comment by siegelpeter** [comment]
If the Sdk is deprecated what is the way to go now ?Am 10.10.2023 um 17:10 schrieb Svenson ***@***.***>:﻿
Hi @siegelpeter,
I see a lot of System.FormatExceptions with the message: String was not recognized as a valid DateTime.
Could you log your parameters when this error happens?
Is this our helloHQ API SDK you use?
If so, this one is deprecated since couple of years now. I cannot guarantee that it will work in all cases anymore.
Best
Sven

**Comment by monderino** [comment]
Just do Http request from your code, with the normal HttpClient or any library you want. 
For example: RestSharp, refit, etc.

But in your case I think it's related to the data you sent.
Maybe you can post your ProjectV1CreateReportingParameters object when an error happen.

Best
Sven
