### ISSUE TITLE
automatic update of the power bi data

### ISSUE THREAD

**Issue by matwuethrich** [hellohq-io/hellohq.docs#137]
Hi guys 
I have linked Power Bi to the Rest API using your guide and created reports.
Now I wanted the data to update automatically. I'm not sure if I've understood everything correctly, but it looks like this is not possible. Can you help me please? I always have to manually push the update.

**Comment by monderino** [comment]
Hey @matwuethrich ,

not sure what you mean exactly with update automatically?

If you mean you want updates from our API?
This feature like Webhooks or so are currently not available. You have to fetch the data every time when you need new updated data. But in this case you can filter by the UpdatedOn property to get only updated items between now and your last fetch.
Example:
`?$filter=UpdatedOn gt 2023-10-19T08:15:00+01:00`

I hope this answer your question?

Best
Sven
