### ISSUE TITLE
How to get Total Costs of Projects

### ISSUE THREAD

**Issue by fisadd** [hellohq-io/hellohq.docs#139]
**Describe**
I want to get the internal Total Costs of the projects like how you see it in the HQ interface. I wasnt able to find the correct endpoint for this - its not the object ProjectBudgets inside /Projects, thats the budget created by the user and not the real internal total cost. 
Is it possible to retrieve this information through your api and if yes which endpoint has it?

**Comment by monderino** [comment]
Hi @fisadd,

The project endpoints do not deliver financial data. Actually we do not have any endpoint to return these kind of information.

Is it possible to retrieve this information, but you have to fetch all entities by your own and do the calculation on your site.

Best 
Sven
