### ISSUE TITLE
Filter Parameter: Bad Request

### ISSUE THREAD

**Issue by solunic** [hellohq-io/hellohq.docs#14]
Ich habe eine gefilterte Abfrage der Kontakte mittels diesem GET-Request versucht, bekomme aber nur einen Bad Request:
https://api.hqlabs.de/v1/ContactPersons?$expand=CustomFields&$filter=CustomFields/any(customField: customField/Name eq 'HubSpot ID Ansprechpartner' and customField/Value eq '1101')

Ist der Request korrekt? Wie könnte ich das Debuggen?

**Comment by patrickkurras** [comment]
Hallo, 

magst du mir einmal eure HQ Url schicken, damit ich das bei euch im System direkt testen kann?

Viele Grüße 
Patrick

**Comment by solunic** [comment]
https://andares.hellohq.io/

**Comment by patrickkurras** [comment]
Hey,

also ich habe gerade den Call, den du oben mit geschickt hast, mit Postman in eurem System ausprobiert und bekomme dort kein Bad Request sondern genau einen ContactPerson zurück. Magst du es vielleicht auch einmal mit Postman ausprobieren und mir eine Rückmeldung dazu geben?

Viele Grüße
Patrick

**Comment by solunic** [comment]
Ja, dort funktioniert es.
