### ISSUE TITLE
Slow API responses

### ISSUE THREAD

**Issue by efandy** [hellohq-io/hellohq.docs#141]
**Describe**
Currently, the API seems very slow. I have a query like this: `https://api.hqlabs.de/v1/Invoices?$filter=Id eq 4244` and it takes 11.9 seconds for a response. Are there currently performance problems with the API?

**Additional context**
<img width="306" alt="grafik" src="https://github.com/hellohq-io/hellohq.docs/assets/95030081/a88c570a-3a69-47a3-bd83-f478f739ad6b">

**Comment by monderino** [comment]
Hey,

I don't think so. But it can be related to your system and the amount of data. If you know the Id of the document I would recommend to use the get by id endpoint.
https://api.hqlabs.de/v1/Invoices(4244)

Best
Sven
