### ISSUE TITLE
Endpoint filter

### ISSUE THREAD

**Issue by DerZerstampfer** [hellohq-io/hellohq.docs#142]
Hey i have two questions for you:

First, what is the ratelimit?

And second, can I filter the GET v1/ContactPersons endpoint?
I would like to filter with the FirstName and LastName, so I don't just get all Contactpersons, but just a filtered subset of them.

**Comment by monderino** [comment]
Hey @DerZerstampfer,

This API has currently no rate limit.
Sure you can filter by using the ODATA filter standard.
Example: v1/ContactPersons?$filter=FirstName eq 'Peter' and LastName eq 'Mustermann'

For more examples check out our documentation (https://developer.hellohq.io/) and search for filter.

Best 
Sven
