### ISSUE TITLE
Get User Abilities

### ISSUE THREAD

**Issue by timoh1** [hellohq-io/hellohq.docs#147]
Hi team,
I'd like to get the users abilities via REST call. Is there a way to use e.g. https://api.hellohq.io/v1/Users get method + expand? Or is there another way?
Is there a documentation which fields are available in context of expand? I couldn't find anything on the developer site.
Cheers,
Timo

**Comment by monderino** [comment]
Hey @timoh1,

When you look into the swagger documentation you can check out the response model. Here all nested object can be get as expand.
For users you can get:
- UserWorkingHours
- CustomFields
- UserGroups
- ResoruceGroups
- Absences
- ...

I hope this will help you.

Best 
Sven
