### ISSUE TITLE
Kostenübersicht Projektdetails

### ISSUE THREAD

**Issue by AnikaKoza** [hellohq-io/hellohq.docs#148]
**Describe**
Hallo, ich wüsste gerne, ob ich die Finanzdaten eines Projektes, sprich interne Kosten und Fremdkosten mir auch in die Excel ziehen kann, um den Deckungsbeitrag zu erhalten. Ich habe es leider nicht gefunden.
Anika

**Comment by AnikaKoza** [comment]
I guess, its the same as here. Isnt it?
https://github.com/hellohq-io/hellohq.docs/issues/139

**Comment by monderino** [comment]
Hi @AnikaKoza,

ja genau. Wir haben keine Endpoints die dir diese Daten liefern.

Viele Grüße
Sven
