### ISSUE TITLE
Problem beim Anzeigen von importierten Unternehmendaten im WebGUI

### ISSUE THREAD

**Issue by tpham2882** [hellohq-io/hellohq.docs#149]
Hallo,

ich habe die Unternehmensdaten über die RestAPI Schnittstelle importiert. Die importierte Daten kann man auch über die RestAPI Schnittstelle abrufen. Jedoch wird die importierte Daten über WebGUI nicht angezeigt. Kann mir jemand weiterhelfen.

Vielen Dank.
TK

**Comment by monderino** [comment]
Hi @tpham2882,

vielleicht hast du die Unternehmen nicht mit einem Unternehmenstyp verknüpft?
Kannst du uns bitte ein Beispiel schicken wie du die Unternehmen erstellt hast (Curl).

Kannst du mir bitte noch die Domain deines helloHQ Systems nennen und den Namen eines Unternehmens das du angelegt hast. Dann können wir uns das anschauen.

Viele Grüße
Sven

**Comment by khiukv** [comment]
Hi @monderino ,
Anbei noch ein bisschen mehr Info zu diesem Fall.

Domain: mhk.hellohq.io

Als Beispiel 3 Unternehmen, aber es gibt mehr mit diese Problem

Komarek Heizung und Sanitär GmbH
Markus Barth GmbH Sanitär Heizung Solar
Ralf Pfitzer Heizung-Sanitär

**Comment by monderino** [comment]
Ok danke.

Kannst du mir noch ein Beispiel vom Post schicken?

**Comment by monderino** [comment]
Hey,

ich habe mir das angeschaut.
Ich denke du hast beim Post kein Subsystem angegeben. Wenn du das machst tauchen die Unternehmen nur im Master Subsystem auf.
Ihr habt zwar ein das Master heißt. Aber das ist tatsächlich keins.

Also entweder definiert ihr ein Subsystem in eurem helloHQ als Master (würde ich auf jeden Fall empfehlen)
oder ihr gebt das beim Post mit an.

Viele Grüße
Sven

**Comment by khiukv** [comment]
Hi @monderino kannst du mir bitte ein Beispiel schicken wie muss ich in POST Subsystem angeben?

**Comment by monderino** [comment]
Hey, 

Entschuldige bitte die späte Antwort.
Ja, wenn ihr die Unternehmen in einem bestimmten Subsystem haben möchtet müsst ihr das immer mitschicken.


Wenn ihr MIYU as master definiert kann dieses Subsystem alles sehen. All Unternehmen, Projekte, etc.
Wenn ihr Unternehmen über die API erstellt und keine Subsysteme mit angebt sind diese nur im master sichtbar... also MIYU in euerm Fall.

Viele Grüße
Sven
