### ISSUE TITLE
Kundennummer nicht in der API response

### ISSUE THREAD

**Issue by efandy** [hellohq-io/hellohq.docs#15]
Hi

für unseren Use-Case benötige ich die Kundennummer eines Unternehmens per API. Ich habe folgende Endpoints abgefragt, die Kundennummer sehe ich jedoch bei keiner Response:

 https://api.hqlabs.de/v1/Companies(62756)
 https://api.hqlabs.de/v1/Companies(62756)/CustomFields

Die CompanyId ist ersichtlich, die Kundennummer jedoch nicht. In welchem API Endpoint müsste die Kundennummer ersichtlich sein und wie müsste das Property heissen?

Gruss
Andy

**Comment by monderino** [comment]
Hi Andy,

hierfür musst du ein expand auf die CompanyTypes machen => 
`https://api.hqlabs.de/v1/Companies(62756)?$expand=CompanyTypes `

Weitere infos dazu kannst du auch in unserer Doku finden. https://developer.hellohq.io/docs/#tag/Companies-Companies

![Screenshot 2021-11-25 at 16 05 41](https://user-images.githubusercontent.com/23459030/143465335-e875fb24-73ea-4c7b-8ae0-f05ca1050f7f.png)


Viele Grüße
Sven
