### ISSUE TITLE
Welche Status gibt es für eine Quotation

### ISSUE THREAD

**Issue by mschneidert3** [hellohq-io/hellohq.docs#151]
Gibt es eine Liste der Status die für eine Quotation möglich sind?

**Comment by monderino** [comment]
Hey,

Dies kannst du in der Swagger Doku sehen

Viele Grüße
Sven
<img width="1479" alt="Screenshot 2024-02-28 at 13 00 32" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/73bf3387-25a5-42ef-90a0-397023c0b774">

**Comment by mschneidert3** [comment]
Danke für die Info!

VG,
Mike
