### ISSUE TITLE
Customfields

### ISSUE THREAD

**Issue by mschneidert3** [hellohq-io/hellohq.docs#153]
Customfields: 

"CustomFields": [
                {
                    "Name": "$key",
                    "Value": "MDAwODg4ODk=;MA==",
                    "Type": "???"
                }
            ]
            
            Welche "Type" kann man verwenden?
            z.B. bei Artikeln
            
            Gibt es eine Möglichkeit eine Liste der möglichen CustomFields / Type pro Entity abzurufen?
            
            Dankeschön!
            
            Viele Grüße,
            Mike

**Comment by patrickkurras** [comment]
Hallo Mike,

der Type ist mehr eher als Information in dem Modal. Um einen Wert in ein Customfield zu schreiben, sollte dieser eigentlich nicht wichtig sein. Über die API können auch keine CustomFields angelegt werden, aber im helloHQ in der UI kannst du diese Anlegen und dort auch die verschiedenen Typen sehen.

Melde dich gerne, wenn du noch weitere Fragen hast.

Viele Grüße
Patrick

**Comment by mschneidert3** [comment]
Hallo Patrick,

danke schön für die Info!

Wo kann ich denn in der UI die Customfields sehen und anlegen/bearbeiten?

![image](https://github.com/hellohq-io/hellohq.docs/assets/148982052/75fa139d-72b0-45e7-a967-05090b5a0dc9)

Viele Grüße,
Mike

**Comment by monderino** [comment]
Hey,

Die findest du in den Standardwerten.

Viele Grüße
Sven

**Comment by mschneidert3** [comment]
Hi Sven,

unter dem Menüpunkt "Standardwerte" kann ich Projektvorlagen erstellen, aber keine CustomFields?

Wie erstelle ich für einen Artikel ein CustomField?

Viele Grüße,
Mike

**Comment by monderino** [comment]
Hey,

Anbei ein Screenshot.
<img width="1110" alt="Screenshot 2024-03-21 at 19 47 48" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/0593249d-864d-44a1-9ed9-5c5aa02e48b9">

**Comment by mschneidert3** [comment]
Aah, dankeschön!

Thema erledigt!

Viele Grüße,
Mike
