### ISSUE TITLE
HQ API Reporting Get Requests not updated maybe cached

### ISSUE THREAD

**Issue by svend-dorn** [hellohq-io/hellohq.docs#154]
for particular users we did not get the latest reportings. We add some Reportings with the HQ Api and we can see them in HQ Web GUI. But the request does not return the latest information.

We face this situation only by two users. One last month and one this month on last day of month.
After a day all reportings are returned as expected. 
Is there any caching that blocks the latest reportings to return?

**To Reproduce**
Difficult to reproduce, because it does not occur for every user. Only on the last or first day of the month.

**Expected behavior**
Return the latest reportings. 

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Edge

**Additional context**
Url: /v1/Users({userId})/Reportings{urlParameter}

**Comment by monderino** [comment]
Hey @svend-dorn,

yes this behavior is related to our caching. Sometimes it happens that cache entries stay longer in the cache as they should.
We try to solve this, but we have no 100% solution right now.

Best
Sven

**Comment by svend-dorn** [comment]
Hey @monderino, 

Thanks for your reply, we keep our fingers crossed, that you could solve this. Just let us know when it is fixed.

Best regards 
Svend

**Comment by monderino** [comment]
hey @svend-dorn,

we added a special header to the endpoints: 
/v1/UserReportings
/v1/Users({userId})/Reportings{urlParameter}
/v1/Users({userId})/Reportings(reportingId)

With this header you can disable the cache for this API call.
The header is: x-hq-without-cache and value should be set to true.

Please be careful with this header, depending on your call it can end up in long running API calls.

Best
Sven

**Comment by svend-dorn** [comment]
Thanks Sven (@monderino) Perfect, we implement this in our tool and I will give feedback If everything works as expected.

**Comment by svend-dorn** [comment]
Issue is Fixed thank you  @monderino
