### ISSUE TITLE
API V2 Payment Date

### ISSUE THREAD

**Issue by timoh1** [hellohq-io/hellohq.docs#155]
Hi,

I'm using the V2 API version to get invoices: https://develop.hellohq.io/v2/Documents?$filter=documentType eq 'Invoice'. Unfortunately, in the body of the answer there is no payment date included. Is there a workaround to the the date the invoice was paid by the customer?

Thanks,
Timo

**Comment by monderino** [comment]
Hey @timoh1,

currently not. We will check if we can bring it into the response data.

Best
Sven

**Comment by Schaukelking** [comment]
Hey @timoh1,
you will now recieve a list of payments in the body of the document including the payment dates. 

Hope this helps

Best,
Patrick
