### ISSUE TITLE
Differentiate API values with multiple mandates

### ISSUE THREAD

**Issue by elbym** [hellohq-io/hellohq.docs#157]
We have two mandates at HQ, and the API returns the values for both mandates. How can I differentiate between the two mandates on the API side?

**Comment by monderino** [comment]
Hey @elbym,

our API isn't subsystem (mandate) aware. 
But some entities you can filter by subsystems for example the projects.
In the swagger documentation you can check the response model. And every time there is the object subsystems included you can filter.

Best 
Sven
