### ISSUE TITLE
API Finance-Prozess 2.0

### ISSUE THREAD

**Issue by peterbmuc** [hellohq-io/hellohq.docs#158]
Hallo zusammen,
wir würden gerne die API-Schnittstelle mit dem neuen Finance-Prozess verknüpfen (Daten abrufen via Excel), um Planumsätze etc. abzurufen (inkl. Custom Fields).

Nach Nutzung der ursprünglichen Anleitung, hatte ich für die Base-URL die "v1/.." durch "v2/Documents" ersetzen wollen, wie von Marino empfohlen. Allerdings bekomme ich dann eine Fehlermeldung. Muss ich sonst noch etwas beachten bei dem Abfrage-Code oder woran liegt es, dass ich die Fehlermeldung erhalte?

Danke und viele Grüße,

Peter

**Comment by monderino** [comment]
Hey @peterbmuc,

das reicht leider nicht. Die v2 API benötigt einen neuen API Token. Diesen kannst du im Admin-Bereich unter Einstellungen im Reiter API-Clients anlegen.
Wenn du Filter nutzt müssen diese auch geändert werden da die v2 andere Filtermöglichkeiten bietet.

Viele Grüße
Sven

**Comment by peterbmuc** [comment]
> Hey @peterbmuc,
> 
> das reicht leider nicht. Die v2 API benötigt einen neuen API Token. Diesen kannst du im Admin-Bereich unter Einstellungen im Reiter API-Clients anlegen. Wenn du Filter nutzt müssen diese auch geändert werden da die v2 andere Filtermöglichkeiten bietet.
> 
> Viele Grüße Sven

Hi Sven,

danke für das Feedback. Ich habe es so probiert, leider funktioniert das nach wie vor nicht. Sollte das als Base-URL in Kmbi mit dem neuen API-Token funktionieren?

"https://api.hellohq.io/v2/Documents?"

LG

Peter

**Comment by monderino** [comment]
Hey,

Ah ja sorry. Da die API noch nicht öffentlich ist geht die url api.hellohq.io nicht. Nutz bitte beta.hellohq.io.

Falls das nun auch nicht gehen sollte schick mir doch bitte einmal die Antwort von deinem Request und die Url von eurem helloHQ System. 

Vielen Dank und viele Grüße 
Sven

**Comment by peterbmuc** [comment]
Hi,

unsere URL ist lobeco.helloq.io, folgenden Versuch habe ich vorgenommen mit dem neuen Token.

***@***.***

Dabei kommt folgende Fehlermeldung

***@***.***

Was mache ich falsch? 😃

Danke und LG

Peter


 
PETER BADER
JUNIOR FINANCE MANAGER
 
 
MIES-VAN-DER-ROHE-STR. 1 
| 80807 
MÜNCHEN
@ ***@***.***
________________________________________________________________________________________________________________
 
WWW.LOBECO.ORG
 
LOBECO GMBH | GESCHÄFTSFÜHRUNG: LORENZ BERINGER, SEBASTIAN IFFERT | AMTSGERICHT MÜNCHEN | HRB 212292
​HYPOVEREINSBANK | IBAN: DE87 7002 0270 0015 0356 12 | BIC: HYVEDEMMXXX | STNR. 143 157 812 65
 
Von: Svenson ***@***.***>
Gesendet: Montag, 8. April 2024 18:33
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Peter Bader ***@***.***>; Mention ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] API Finance-Prozess 2.0 (Issue #158)


Hey,

Ah ja sorry. Da die API noch nicht öffentlich ist geht die url api.hellohq.io nicht. Nutz bitte beta.hellohq.io.

Falls das nun auch nicht gehen sollte schick mir doch bitte einmal die Antwort von deinem Request und die Url von eurem helloHQ System.

Vielen Dank und viele Grüße
Sven

**Comment by peterbmuc** [comment]
Habe es via Mail geschickt, danke!
