### ISSUE TITLE
GET /ProjectTasks returns deleted tasks when only TaskTypeId is filtered

### ISSUE THREAD

**Issue by groev** [hellohq-io/hellohq.docs#159]
I accidentally created some tasks that that I wanted to delete, but they still are returned 

Deleting tasks via DELETE ProjectTasks({id])

Calling: GET  ProjectTasks
{
filter: {
TaskTypeId: {TaskTypeId}
}
When setting IsDone or some other parameter they are not returned. 

I would expect them to not show up in any request.

**Comment by monderino** [comment]
Hey @groev ,

Sorry for the later response. Could you give me the following information:
- Your helloHQ domain
- TaskId
- TaskTypeId

Then I will verify it in our DB.

Thank you and best regards
Sven
