### ISSUE TITLE
Custom Field "HubSpot ID Ansprechpartner" wird nicht gespeichert

### ISSUE THREAD

**Issue by solunic** [hellohq-io/hellohq.docs#16]
Wir schreiben bereits erfolgreich Kontakte per API ins HQ, auch das updaten funktioniert.

Nur beim Custom Field 18083 haben wir ein Problem, es wird nicht gespeichert. Alle anderen Daten werden korrekt übernommen.

Unsere HQ Url ist https://andares.hellohq.io/

So sehen die POST bzw. PUT Daten aus:

{"Salutation":"Herr","FirstName":"Max","LastName":"Mustermann","CompanyId":62050,"PhoneLandline":"07232 111111","PhoneMobile":"0664 222222","Language":"DE","DefaultAddress":{"City":"St. Martin","Street":null,"HouseNumber":"","ZipCode":"4113","Country":"AT","Email":"info@xxxxxxx.com"},"CustomFields":[{"Value":"1101","Id":18083}]}

**Comment by Schaukelking** [comment]
Hey! 

Das updaten bzw. setzen eines CustomFields erfordert eine zweite Operation und kann nicht beim Erstellen oder Updaten eines Kontakts befüllt werden. Nach dem erstellen der Kontaktperson musst du somit einen zweiten Call machen:

https://api.hqlabs.de/v1/ContactPersons({ContactPerson.Id})/CustomFields({CustomFieldDefinition.Id})

Beim Body reicht dann:
{
 "Name": "string",
 "Value": "string",
}

Zu finden in der Doku ist der call hier: 
https://developer.hellohq.io/docs/#tag/Contact-Person-Contact-Persons%2Fpaths%2F~1v1~1ContactPersons(%7BId%7D)~1CustomFields(%7BCustomFieldDefinitionId%7D)%2Fput

Ich hoffe, das hilft dir weiter!

**Comment by solunic** [comment]
Danke, es hat funktioniert.
