### ISSUE TITLE
Artikel Verwaltung via REST API

### ISSUE THREAD

**Issue by mschneidert3** [hellohq-io/hellohq.docs#160]
Hallo,

eine Frage, ich lege via REST API Artikel an, was auch funktioniert
und kann die Artikel auch via REST API löschen.

In der Web GUI werden diese Artikel aber weiterhin angelegt,
woran liegt das?

Viele Grüße,
Mike

**Comment by monderino** [comment]
Hey @mschneidert3 

"In der Web GUI werden diese Artikel aber weiterhin angelegt,
woran liegt das?" => Du meinst sichern weiterhin angezeigt, oder?

Das liegt am Cache. Dieser hat die Änderung nicht mitbekommen, daher wird der Article in der UI weiterhin angezeigt.
Du kannst mir aber gerne deine helloHQ Url nennen und die Id des Artikels und dann überprüfe ich das in der Datenbank.

Viele Grüße
Sven

**Comment by mschneidert3** [comment]
Das System ist:
https://miyu-testsystem.hellohq.io

In der Artikel Kategorie:  "MIYU HQ SAGE Datentransfer" id: 4020,
sollten keine Artikel mehr vorhanden sein.

Via REST API bekomme ich folgendes Ergebnis:

GET Call: https://miyu-testsystem.hellohq.io/v1/Articles?$filter=CategoryId eq 4020

{
    "@odata.context": "http://miyu-testsystem.hellohq.io/v1/$metadata#Articles",
    "value": []
}

Viele Grüße,
Mike

**Comment by monderino** [comment]
Hi Mike,

Danke für die Informationen. Hast du noch eine ArticleId für mich oder kann ich irgendeinen Artikel aus der Kategorie nehmen?

Viele Grüße
Sven

**Comment by mschneidert3** [comment]
Hi Sven,

ja das wäre super und danke für das schnelle Feedback!

Viele Grüße,
Mike

**Comment by monderino** [comment]
Alles klar.
Die Artikel sind schon mal gelöscht.

**Comment by monderino** [comment]
Hey Mike,

der Fix ist online.

Viele Grüße
