### ISSUE TITLE
Zeiterfassung über die REST-API

### ISSUE THREAD

**Issue by Tristan747** [hellohq-io/hellohq.docs#161]
In der Web Oberfläche kann ich über "Mein HQ" -> "Dashboard" ein Widget für die Zeiterfassung anlegen.
Darüber lassen sich Zeiten buchen, auch ohne ein Reproting zu einem Projekt anzulegen. 
Kann ich diese Zeiterfassungen auch über die API abrufen und erstellen?  

`https://api.hqlabs.de/v1/Users({ID})/Reportings` -> existiert
`https://api.hqlabs.de/v1/Users({ID})/{TimeReportings}` -> gibt es sowas?

Danke schon mal für die Auskunft.

**Comment by monderino** [comment]
Hey @Tristan747,

Nein, über die API kann keine Präsenszeit erstellt werden.

Viele Grüße
Sven

**Comment by gielians** [comment]
Schade, warum nicht?
Wäre auf jeden Fall nice to have.
Wir würden gerne die Zeiterfassung der jeweils letzten Woche in einen Wöchentlichen "Statusbericht" für jeden User integrieren, nach dem Motto: "hey, guck da noch mal drüber, du hast von Dienstag bis Donnerstag die Uhr laufen lassen, da stimmt vielleicht was nicht..."
Pausenzeiten sind demnach aber auch nicht abfragbar, korrekt?
Am einfachsten wäre natürlich eine Funktion direkt in HQ, sodass wir nichts bauen müssen, aber wenigstens die Möglichkeit zu haben es sich selber zu bauen wäre gut.
