### ISSUE TITLE
Extend for Files

### ISSUE THREAD

**Issue by lukaszauner** [hellohq-io/hellohq.docs#162]
**Describe**
I want to get a list of all our Contact Histories and certain entities related to it (Contact Persons, Users, Companies, Files)
The only thing which is still missing, are the attached Files which get returned as null. I tried to expand the following: Files, files, DocumentFiles,... but none worked. In the documentation, i cannot find a hint to the correct expand value either.

**Additional context**
Add any other context about the question here.
- Screenshots
- Curls
- etc

**Comment by monderino** [comment]
Hey @lukaszauner,

Sorry but currently there is no way to get the files related to a contact history.

Best 
Sven

**Comment by lukaszauner** [comment]
Hi @monderino 
Thanks for your reply. Is there any alternative other than manual labor? 
Best 
Lukas

**Comment by monderino** [comment]
Currently you just can download it via the UI.
But I will check if we can include it into our Files endpoint.

**Comment by lukaszauner** [comment]
It would be really neat, since our company has a lot of ContactHistories with important files attached. It would take ages to download and manage them manually..
Thanks

**Comment by monderino** [comment]
Hey @lukaszauner,

we currently work on the endpoint. I hope we can bring it online somewhere next week.

Have a great weekend.
Best
Sven

**Comment by lukaszauner** [comment]
Hey @monderino . you are my hero. thanks! hope a description will be available in the doku too!
