### ISSUE TITLE
Custom Field only send after manual Save on Projekt Page

### ISSUE THREAD

**Issue by gielians** [hellohq-io/hellohq.docs#165]
**Describe the bug**
We have added 4 custom Fields to our Projects, 3 of them are Gettable throu the API right after a Projekt is created in the Web GUI.
the 4th one is only Gettable and Puttable after one goes to the Project Page and manually hits "edit" and "save".

**To Reproduce**
Add a new project
Send Get request for Custom Fields (either expand projects or dedicated Get 
https://api.hqlabs.de/v1/Projects?$expand=CustomFields
https://api.hqlabs.de/v1/Projects(3545)/CustomFields

**Expected behavior (Response)**
```json
{
    "@odata.context": "http://api.hqlabs.de/v1/$metadata#CustomFields",
    "value": [
        {
            "Name": "Informationen",
            "Value": "",
            "Type": "TextMultiline",
            "Id": 18020,
            "CreatedBy": 0,
            "UpdatedBy": 0,
            "CreatedOn": null,
            "UpdatedOn": null
        },
        {
            "Name": "WeitereGitLabProjekte",
            "Value": "",
            "Type": "TextMultiline",
            "Id": 18043,
            "CreatedBy": 0,
            "UpdatedBy": 0,
            "CreatedOn": null,
            "UpdatedOn": null
        },
        {
            "Name": "GitLabProjektLink",
            "Value": "",
            "Type": "Link",
            "Id": 18044,
            "CreatedBy": 0,
            "UpdatedBy": 0,
            "CreatedOn": null,
            "UpdatedOn": null
        },
        {
            "Name": "Projektordner",
            "Value": "localexplorer:P:\\Aktiv\\131-SEF Kick-o-Mat _ Interlaken-142",
            "Type": "Link",
            "Id": 18045,
            "CreatedBy": 0,
            "UpdatedBy": 0,
            "CreatedOn": null,
            "UpdatedOn": null
        }
    ]
}
```
**Actual Behavior (Response)**
```json
{
    "@odata.context": "http://api.hqlabs.de/v1/$metadata#CustomFields",
    "value": [
        {
            "Name": "Informationen",
            "Value": "Allgemeiner Service für item\nWird nach Aufwand abgerechnet",
            "Type": "TextMultiline",
            "Id": 18020,
            "CreatedBy": 0,
            "UpdatedBy": 0,
            "CreatedOn": null,
            "UpdatedOn": null
        },
        {
            "Name": "WeitereGitLabProjekte",
            "Value": "",
            "Type": "TextMultiline",
            "Id": 18043,
            "CreatedBy": 0,
            "UpdatedBy": 0,
            "CreatedOn": null,
            "UpdatedOn": null
        },
        {
            "Name": "GitLabProjektLink",
            "Value": " ",
            "Type": "Link",
            "Id": 18044,
            "CreatedBy": 0,
            "UpdatedBy": 0,
            "CreatedOn": null,
            "UpdatedOn": null
        }
    ]
}
```

**Workaround for now**
got to every Project Page and hit "Edit" and "Save" (no need to actually edit anything)

**Screenshots**
Config in Admin Panel
![image](https://github.com/hellohq-io/hellohq.docs/assets/20226862/5b79105f-6c87-45d6-8a22-c961d6848f06)
(Config is the same as the other "Link" Custom Field)

**Environment (please complete the following information):**
 - OS: any
 - Browser none
 - Version ?

**Additional context**
The 3 other Custom Fields work as intendet

**Comment by monderino** [comment]
Hi @gielians,

we will check the behavior. Please can you tell me your helloHQ url.

Best 
Sven

**Comment by gielians** [comment]
https://realtime-department.hellohq.io/


ERIC GIELIANS



REALTIME DEPARTMENT
Gesellschaft für interaktive Medien mbH



OBERDÖRNEN 17

42283 WUPPERTAL

GERMANY

PHONE: +49 202 317 387 14



www.realtime-department.de<http://www.realtime-department.de/>

***@***.******@***.***>



Handelsregister Wuppertal HRB 24345, Ust.-IdNr.: DE 284912634.
Sitz der Gesellschaft ist Wuppertal. Geschäftsführer: Torsten Hauck, Christoph Gockel



Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist ausdrücklich nicht gestattet.



This e-mail may contain confidential and/or privileged information. If you are not the intended recipient (or have received this e-mail in error) please notify the sender immediately and destroy this e-mail. Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.



Save Paper =) Think before you print.

________________________________
Von: Svenson ***@***.***>
Gesendet: Dienstag, 28. Mai 2024 13:05
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Eric Gielians ***@***.***>; Mention ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] Custom Field only send after manual Save on Projekt Page (Issue #165)


Hi @gielians<https://github.com/gielians>,

we will check the behavior. Please can you tell me your helloHQ url.

Best
Sven

**Comment by monderino** [comment]
Hey @gielians,

Thank you. I will check it and let you know the result.

Best
Sven

**Comment by monderino** [comment]
Hey @gielians,

I have investigated the behavior.  
The cause lies in the data management. We save the data of the custom fields in a materialized view to make the data available more quickly. However, this materialized view is only updated if you also enter data in the custom field or if the entity to which the custom field is attached is updated.
Unfortunately, adding the custom field does not cause the materialized view to update. 

In the end, this means that if the custom field you expect is not included in the result. 
Then the field has no value.

Unfortunately, we cannot change this behavior. 

I hope this will help you a bit to update your logic.

Best
Sven
