### ISSUE TITLE
Can't find one user attribute on the API requests

### ISSUE THREAD

**Issue by eduardo-9fwr** [hellohq-io/hellohq.docs#166]
**Describe**
We are trying to retrieve the Abteilung attribute from the users.
But I can't find it on the API response.
Even expanding everything that I can think of.

The request send is /v1/Users?$expand=UserGroups,CustomFields,ResourceGroup

But we can see the "Abteilung" anywhere on the response.
The image below shows the view in HQ.

The "Weiteren Daten" on the bottom are the custom fields and these can be found in the response.

![image (1)](https://github.com/hellohq-io/hellohq.docs/assets/103043368/082fbd9e-f4a6-4a92-9aed-1cf92ce174a9)

**Comment by eduardo-9fwr** [comment]
This is the json that comes back for this user

{
  "@odata.context": "http://api.hellohq.io/v1/$metadata#Users",
  "value": [
    {
      "FirstName": "L",
      "LastName": "X",
      "UserName": "LX",
      "EMailWork": "something@gmail.com",
      "Salutation": "E",
      "Title": "",
      "EmployeeNumber": "123451251",
      "BirthDate": "1000-01-01",
      "FederalState": "Something",
      "Country": "NC",
      "BasicLoadInHours": null,
      "EntryDate": "1000-01-01",
      "LeavingDate": null,
      "PhoneLandlinePrivate": "",
      "PhoneLandlineWork": "+00 00 00000",
      "PhoneMobilePrivate": "+00 00 00000",
      "PhoneMobileWork": "",
      "Id": 00000,
      "CreatedBy": 1,
      "UpdatedBy": 1,
      "CreatedOn": "1000-01-01",
      "UpdatedOn": "1000-01-01",
      "UserGroups": [
        {
          "Name": "Consulting",
          "Description": null,
          "RightLevel": 3,
          "Id": 0000,
          "CreatedBy": 1,
          "UpdatedBy": 1,
          "CreatedOn": "1000-01-01",
          "UpdatedOn": "1000-01-01"
        },
        {
          "Name": "Abtlg.-Leiter:in",
          "Description": null,
          "RightLevel": 3,
          "Id": 00000,
          "CreatedBy": 1,
          "UpdatedBy": 1,
          "CreatedOn": "1000-01-01",
          "UpdatedOn": "1000-01-01",
        },
        {
          "Name": "Director:in",
          "Description": null,
          "RightLevel": 4,
          "Id": 0000,
          "CreatedBy": 1,
          "UpdatedBy": 1,
          "CreatedOn": "1000-01-01",
          "UpdatedOn": "1000-01-01"
        }
      ],
      "CustomFields": [
        {
          "Name": "fest/frei",
          "Value": "fest",
          "Type": "Dropdown",
          "Id": 00000,
          "CreatedBy": 0,
          "UpdatedBy": 0,
          "CreatedOn": null,
          "UpdatedOn": null
        },
        {
          "Name": "Team/Etat",
          "Value": "Tech",
          "Type": "Text",
          "Id": 0000,
          "CreatedBy": 0,
          "UpdatedBy": 0,
          "CreatedOn": null,
          "UpdatedOn": null
        }
      ],
      "ResourceGroup": {
        "Name": "Consulting Tech",
        "Description": "",
        "IsDefaultGroup": null,
        "Id": 000,
        "CreatedBy": 1,
        "UpdatedBy": 1,
        "CreatedOn": "1000-01-01",
        "UpdatedOn": "1000-01-01"
      }
    }
  ]
}

**Comment by eduardo-9fwr** [comment]
Thanks @monderino 
Looking forward to hearing from you.

**Comment by monderino** [comment]
Hey,

The change is online. You have now the department within the response. 

Best 
Sven

**Comment by eduardo-9fwr** [comment]
Great.

I see the changes already.

Thanks

**Comment by eduardo-9fwr** [comment]
@monderino 
Does the users in HQ also contain an Id to the corresponding user on Awork?

The projects we can link between HQ and Awork because the project in HQ have one dimension called AworkSyncId
Is there something similar for the users?

**Comment by monderino** [comment]
Hey,

No there is no id. But you can use the email address. This is what we use for the sync as well.
We use the work email address.

Best 
Sven

**Comment by eduardo-9fwr** [comment]
Interesting.

I will test it out.
Thanks
