### ISSUE TITLE
Permanenter API Key für Beta API

### ISSUE THREAD

**Issue by autoMarc123** [hellohq-io/hellohq.docs#170]
Hallo zusammen;

Wir haben zuletzt den Zugang zur API V2 Beta bekommen und darauf einen umfangreichen Workflow aufgebaut. Leider bekommen wir einen jetzt auf einmal einen HTTP 401 (Keine Berechtigung) zurück.

Wie ich erfahren habe, ist der von uns erstellte Key über die API nur 14 Tage nutzbar.

Könnt ihr uns einen permanenten Key ausstellen?

Vielen Dank vorab.

**Comment by monderino** [comment]
Hi @autoMarc123,

einen permanenten Key könnt ihr euch in euerm helloHQ System selber erstellen.

Unter Admin => Einstellungen => API Clients

Viele Grüße
Sven

**Comment by autoMarc123** [comment]
Hi Sven, dass hatten wir schon mehrfach versucht. Leider ohne Erfolg.

ich bekomme weiterhin einen Http 401

<img width="1298" alt="image" src="https://github.com/user-attachments/assets/4a88d9f5-cdce-42a7-ad3d-0d56d80ce5fd">

**Comment by monderino** [comment]
Hey,

Ihr seit in der Falschen UI. Das ist für die API v1.
Das ist in Admin => API Clients.
Ihr müsst aber in Admin => Einstellungen => API Clients
