### ISSUE TITLE
POST requests Users & UserReportings

### ISSUE THREAD

**Issue by salkin-hc** [hellohq-io/hellohq.docs#171]
Hallo, generelle Frage zu der API: 
Gibt es die Möglichkeit neue User und UserReportings anzulegen? Ich sehe bei Swagger keine Möglichkeit für Post Requests bzgl. User und UserReportings.

**Comment by monderino** [comment]
Hey @salkin-hc,

User anlegen geht nicht. Dies ist nur in helloHQ möglich.
In unserer API v2 (Developer Docs gehen im September online) sind wir gerade dabei die Endpoints für Reportings und Zeiterfassung zu definieren.

Viele Grüße
Sven

**Comment by salkin-hc** [comment]
Alles klar danke dir. 

Wird es dann auch die Möglichkeit gebenüber Put Requests die User Group eines Users zu ändern?

**Comment by monderino** [comment]
Das wird erstmal nicht möglich sein. 
Essentielle Funktionen bezüglich des User- und Rechte-Managements werden erstmal nicht in der API verfügbar sein.
