### ISSUE TITLE
Updated customer masterdata is not shown via API

### ISSUE THREAD

**Issue by alebasenau** [hellohq-io/hellohq.docs#172]
Hi,

when we update a customers masterdata (for example the Debitornumber) the updated value will not be shown via an API call.

I attached you some screenshots.

<img width="232" alt="db_nr_masterdata_hq" src="https://github.com/user-attachments/assets/c4a4aa22-cb3b-462e-a9a7-940f46118226">
<img width="222" alt="postman_result_masterdata" src="https://github.com/user-attachments/assets/ddc9fc54-64a6-4d76-b925-c993a6d74ff8">

I assume nothing has changed in the API handling?

Thank you in advance for any information!

Best Regards,
Alejandro

**Comment by monderino** [comment]
Hi @alebasenau,

Where do you the update of the customers data, in the helloHQ UI or via API?
When you do it via API, can you please sent us a example of the request?
Thank you.

Best
Sven

**Comment by alebasenau** [comment]
Hi @monderino 

we do it via the helloHQ UI.

Regards,
Alejandro

**Comment by monderino** [comment]
Thanks. I will check it.

**Comment by monderino** [comment]
Hey @alebasenau,

for me the Debitornumber is showing up.
<img width="1465" alt="Screenshot 2024-08-06 at 10 07 06" src="https://github.com/user-attachments/assets/8c237785-ae1f-42a8-beda-ca02668fb286">


Is it in you example still the case or is the number showing now?

If the number is not shown, please tell me the id of the company and the url of your helloHQ System.

Best
Sven

**Comment by alebasenau** [comment]
Hi @monderino 

it still does not show up. :/

URL: https://mhk.hellohq.io
I tried the following API call: https://api.hqlabs.de/v1/Companies(115606)

I just saw that the "UpdatedOn"-Timestamp isn't correct aswell:

![image](https://github.com/user-attachments/assets/3ba8d43d-e655-4b73-a14f-0ed6e80f8162)

![image](https://github.com/user-attachments/assets/d452eacb-c629-46a0-b476-b50986535292)

Thanks in advance!

Regards,
Alejandro

**Comment by monderino** [comment]
Hey @alebasenau,

I checked it in your helloHQ System and there is no debitor number set.
But there is a company with the name: Küchenstudio am Zoll Dieter Ernst e.K. and Id 113274.

Is this maybe the one you want?

Best 
Sven

**Comment by alebasenau** [comment]
Morning @monderino 

thanks, that was the problem. We had the same customer twice in our system and I pull for the wrong one.

Now it works with the other CompanyId.

Thank you!

Regards,
Alejandro
