### ISSUE TITLE
API V2: Get all documents doesn't work

### ISSUE THREAD

**Issue by timoh1** [hellohq-io/hellohq.docs#173]
Hi all,

**Describe the bug**
I'm trying to get all Documents using the API V2: https://develop.hellohq.io/v2/Documents. I get following response: 400 Bad Request, _{"message": "Conversion failed when converting date and/or time from character string."}_

**To Reproduce**
1. Use a REST Client, e.g. Postman
2. Get your Bearer Token
3. Add the token to the Get Call https://develop.hellohq.io/v2/Documents
4. As response you'll get 400 Bad request, _{"message": "Conversion failed when converting date and/or time from character string."}_

**Expected behavior**
I would expect to get the documents

**Screenshots**
![Greenshot 2024-08-07 11 22 17](https://github.com/user-attachments/assets/1540adbf-401f-46ea-a677-fb3a064c2f67)

**Environment (please complete the following information):**
 - Client: Postman

Thanks, 
Timo

**Comment by monderino** [comment]
Hey @timoh1,

Thanks for this hint. I will check it.
