### ISSUE TITLE
Getting started 

### ISSUE THREAD

**Issue by ITRvct** [hellohq-io/hellohq.docs#176]
**Describe**
I want to use your API to pull the UserReportings and summarize them. 
for this i would need to sort the Reportings according to their start and end date. 

I have several questions, as i have never worked with API before:
The access token was generated 2 Weeks ago. Is it possible that it isn't valid anymore?
Secondly, if it isn't valid anymore, do I just replace it with the refresh token? 
Third, I am having trouble finding the right documentation of the endpoints in your Database vs our User Interface. 
I was told, that I could use the API Integration for Excel but have not been able to integrate it properly. 
The requests always fails. Could this be due to the invalid access Token?

**Additional Information**
This is an example Code (Incase there is something wrong here?)
import requests
import json

HelloHQ_API_URL = "https://api.hellohq.io/v1/User"
HelloHQ_API_TOKEN = "xxxxx"

def request(FirstName):
    url = f"{HelloHQ_API_URL}"
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {HelloHQ_API_TOKEN}"
    }
    data = {
        "FirstName": FirstName
    }

    r = requests.get(url, headers=headers, data=data)
    if r.status_code == 200:
        return r.json()

    try:
        response = requests.post(url, headers=headers, data=json.dumps(data), timeout=10)
        response.raise_for_status()  # Wirft einen Fehler bei HTTP-Fehlerstatus
        return response.json()
    except requests.exceptions.HTTPError as http_err:
        print(f"HTTP error occurred: {http_err} - {response.text}")
    except requests.exceptions.ConnectionError as conn_err:
        print(f"Connection error occurred: {conn_err}")
    except requests.exceptions.Timeout as timeout_err:
        print(f"Timeout error occurred: {timeout_err}")
    except requests.exceptions.RequestException as req_err:
        print(f"An error occurred: {req_err}")
    return None

#Test request function
FirstName = "xxxx"

r = request(FirstName)

if r is None:
    print("Failed to fetch data from HelloHQ API")
else:
    print("RawData:", r)

**Comment by monderino** [comment]
Hey @ITRvct,

Thanks for your request.

First of all, which version do you want to use?
We have v1 and v2.

v2 is in beta state actually, but it went to public state in September. (https://beta.hellohq.io/swagger/index.html)

If you used a token which was valid for 2 weeks only, then it's sounds like you use v2.

Doesn't matter which version you use, you can generate a token in the helloHQ UI.
v1: Admin => API Clients
v2: Admin => Settings => API Clients

The excel-addin is currently only available in v1.

The call to get UserReportings is:
v1/UserReportings
v2/UserReportints

Best 
Sven

**Comment by ITRvct** [comment]
Hi Sven, 

Thank you for your reply. 
We did have the v1-v2 conflict, that i solved now. 
I am still getting a bad request for my URL. 
I am referencing the Code I send in with the Question. 
Is the formating wrong? I am a bit confused as I thought, that I followed your documentation correcty

**Comment by monderino** [comment]
I do not really understand your code.
But maybe the f before "Bearer {HelloHQ_API_TOKEN}" is wrong or why you have 
a body like:
}
data = {
"FirstName": FirstName
}

Maybe it make sense to use an API testing tool like postman.
Here an example curl:
`
curl --location 'https://api.hqlabs.de/v1/Users' \
--header 'Authorization: Bearer {YOUR-TOKEN}'
`

Best
Sven
