### ISSUE TITLE
"RemoteWork" wird als abwesende Tage gezählt

### ISSUE THREAD

**Issue by samat03** [hellohq-io/hellohq.docs#18]
Hallo, 

**Describe the bug**
Es ist aufgefallen, dass  der Abwesenheitstyp "RemoteWork" zu den "MissedDays" gezählt wird. Ist das so gewollt? Hat das Auswirkungen auf das Reporting bezüglich der Kapazität?
Also bei unserer, mithilfe der API gezogenen, Datei wird "Remote Arbeit" als verpasste Tage gezählt.
Im Anhang wird es nochmal deutlicher.

**Screenshots**
<img width="271" alt="hqbild" src="https://user-images.githubusercontent.com/96437381/146803390-4f7822ae-df43-4e44-951d-5b9b32a3e2f2.png">

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: chrome

Vielen Dank!

**Comment by patrickkurras** [comment]
Hallo,

ich habe mir das gerade einmal angeschaut und Remote Work und verringert nicht die Kapazität in der Projektplanung und auch nicht im Arbeitszeitkonto. 
Ich werde es aber mal aufnehmen, ob man die MissedDays bei dem Typen vielleicht nicht mehr berechnet.

Melde dich gerne, wenn du dazu noch weitere Fragen hast.

Viele Grüße 
Patrick
