### ISSUE TITLE
PUT am Endpunkt Projects

### ISSUE THREAD

**Issue by drkn-nh** [hellohq-io/hellohq.docs#180]
Hi,

wir würden gerne per API die Projektvorlage (ProjectTemplateId) ändern können.

Gibt es dafür einen (undokumentierten) Endpunkt?

**Comment by Schaukelking** [comment]
Hey @drkn-nh ,

leider haben für keinen Endpunkt zum Wechseln der Projektvorlage. Die Logik dahinter ist eher komplex und muss vieles berücksichtigen. Ich kann das Thema gerne ins Team weiter reichen und wir schauen, ob wir zukünftig in unserer v2 die Funktionalität bereitstellen können. 

Denke aber erstmal musst du leider ohne den Endpunkt arbeiten, tut mir leid.

Beste Grüße
