### ISSUE TITLE
Time entries on closed tasks

### ISSUE THREAD

**Issue by csabaokros-memtime** [hellohq-io/hellohq.docs#182]
We are using the [do.CreateReporting](https://developer.hellohq.io/apidocs/#/Projects%20-%20Projects/post_v1_Projects__Id___do_CreateReporting) endpoint to create time entries. In HQ we are not allowed to select a task that is completed, but the API accepts a completed tasks's ID, and creates a time entry for it.

Is this intended behaviour?

**Comment by monderino** [comment]
Hey @csabaokros-memtime ,

sorry for the late response.
No, we have checks for this in our API as well.

Please send me the domain of your helloHQ system and an example of your post request. Then I will check it.

Thank you an best regards
Sven

**Comment by monderino** [comment]
Hey @csabaokros-memtime,

we have 2 systemsettings in helloHQ
- to forbid reportings on finished projects
- to forbid reportings on finished tasks

and both are disabled.
Do you test the case for a customer of memtime?
I can enable the settings if you need?

Best
Sven
