### ISSUE TITLE
Issue with Lead Creation via API – Make.com Integration

### ISSUE THREAD

**Issue by geckodenny** [hellohq-io/hellohq.docs#183]
Hello Support Team,

We are experiencing an issue with the API for creating and updating leads in HQ Labs through Make.com (formerly Integromat). While we can successfully create and update leads using the API, there are two major issues:

Leads not displaying in the HQ frontend:
After creating a lead via the API (specifically, Lead ID: 4661, Number: 20240912), the lead does not properly display in the HQ user interface. When trying to view the lead, the page briefly attempts to load but turns blank immediately, leaving a white screen. This behavior occurs consistently with leads created via the API.

Volume field not being updated:
Although the API documentation indicates that the Volume field should accept a number($double) value, when sending a value for the Volume (e.g., 10000), it does not appear to be saved or updated. When retrieving the lead data afterward, the Volume field remains blank or unchanged. We have tried different formats such as integer, decimal, and string, but none seem to work.

Here is an example of the request we are sending via Make.com for lead creation:

{
  "Name": "Testlead Denny API",
  "CompanyName": "sprd.net AG",
  "Number": "20240912",
  "CompanyId": 63043,
  "StatusId": 46002,
  "ResponsibleUserId": 11025,
  "ContactPersons": [
    {
      "FirstName": "Jan",
      "LastName": "Kloth"
    }
  ],
  "ClosingProbability": 10,
  "Currency": "EUR",
  "Volume": 10000
}

We are using Make.com for HTTP requests, and the API calls are successfully processed, returning 200 OK responses. However, these leads are not displaying in the HQ UI and the Volume field is not being updated.

Please find below additional details:

Lead ID: 4661
Lead Number: 20240912
Platform: Make.com integration with HQ API
API Response: Successful 200 OK, but data inconsistencies occur when viewed in the HQ UI.
We would appreciate it if your team could investigate this issue and advise on how to resolve it, especially regarding the Volume field and the blank screen issue in the HQ UI.

Thank you for your assistance!
Denny

<img width="442" alt="Bildschirmfoto 2024-09-12 um 11 07 48" src="https://github.com/user-attachments/assets/1150e71e-cb79-49bb-88df-af919da5bc34">
<img width="926" alt="Bildschirmfoto 2024-09-12 um 11 08 46" src="https://github.com/user-attachments/assets/6e1444fd-33ce-4658-bb7f-139ec2395c12">

**Comment by monderino** [comment]
Hey @geckodenny,

please tell me your helloHQ domain. Then I can check the data.

Best
Sven

**Comment by geckodenny** [comment]
Hey Sven,

thank you!!

https://gecko-one.hellohq.io

**Comment by monderino** [comment]
Hey @geckodenny,

Thank you very much. I check you'r helloHQ system.
The data are all correct.

I guess when you are in our helloHQ UI, you have not selected a Master-Subsystem. There you are able to see the lead. 
This happen because you do not specify the subsystems the lead is related to. In this case the lead only show up in a Master-Subsystem.
Add 
"Subsystems": [
      {
         "Id": 9999999
      }
    ]
to you post to add the lead also to one or more subsystems.

Best 
Sven

**Comment by geckodenny** [comment]
Awesome! Thank you very mich Sven! :)
