### ISSUE TITLE
IBAN und BIC werden nicht übergeben

### ISSUE THREAD

**Issue by sophusrex** [hellohq-io/hellohq.docs#184]
**Describe**
Im Input übergebe ich die IBAN und BIC korrekt, jedoch werden die beiden Daten nicht richtig gesetzt und im Output auch nicht ausgegeben. Es geht um den Endpunkt: POST /v1/Companies (Creates a new company).

Die Company wird erstellt, aber nicht alle Daten richtig übergeben.

**Additional context**
<img width="453" alt="Bildschirmfoto 2024-09-19 um 14 35 27" src="https://github.com/user-attachments/assets/c61ee6f1-aed4-459d-8f15-ed1688267889">

**Comment by monderino** [comment]
Hey @sophusrex,

Thank you very much for this information. I will check it.

Best 
Sven

**Comment by monderino** [comment]
Hey @sophusrex,

I was able to find the issue. I fix will be online tomorrow.

Best 
Sven
