### ISSUE TITLE
API V2: filter date fields not working No coercion operator is defined between types 'System.Int32' and 'System.DateTime'

### ISSUE THREAD

**Issue by svend-dorn** [hellohq-io/hellohq.docs#185]
**Describe the bug**
We try to filter the user reporting like in API V1 but we receive an error message.

**To Reproduce**
1. request as Curl https://api.hellohq.io/v2/UserReportings/?$filter=startOn ge 2024-09-01
2. response: {"message": "No coercion operator is defined between types 'System.Int32' and 'System.DateTime'."}

**Expected behavior**
get the requested reportings.

**Screenshots**
![image](https://github.com/user-attachments/assets/6382a70c-721f-4080-bd28-79ea70f6039a)

**Environment (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Postman]
 - Version []

**Additional context**
Please check other date fields as well.

**Comment by monderino** [comment]
Hey @svend-dorn,

to filter dates you need to use this syntax: ge datetime'2024-08-30T23:00:00'.
This is the UTC time for the first of September.

Best
Sven

**Comment by svend-dorn** [comment]
Perfect. Could you please update your readme how to filter in V2. 
Only V1 is mentioned
/v1/Companies?$filter=UpdatedOn gt 2018-01-26T18:15:00+01:00

Best regards Svend

**Comment by monderino** [comment]
Sure,

we work on an update currently.
