### ISSUE TITLE
Getting list of invoices

### ISSUE THREAD

**Issue by Shahzeb42Digital** [hellohq-io/hellohq.docs#186]
Hi there,

I am trying to get the list of invoices, but it seems, the endpoint is not providing the correct data. We have recently started with HelloHQ interface and the oldest invoice is created on 2024-09-09 (from interface) and the endpoint is giving oldest invoice date 2017-07-01. Also I can see 23 invoices record in the HelloHQ interface and endpoint is giving just 5 (no expand/filter is used while requesting from API). 

Can you help me to figure out the issue? Thanks!

Endpoint: https://api.hellohq.io/v1/Invoices

**Comment by Shahzeb42Digital** [comment]
Hi Monderino,
sure. 

Domain: https://42digital.hellohq.io/dashboard

Executed request was in Python. Here is a snippet:
headers = {'Authorization': f'Bearer {access_token}'}
response = requests.get('https://api.hellohq.io/v1/Invoices', headers=headers)

**Comment by monderino** [comment]
I checked the helloHQ system and you work with our new finance process.

This mean you need our new API v2 and not v1.
Currently the documentation is in progress because this API is in beta state. We hope the documentation will go online in the next weeks.

A swagger documentation you can find here: https://beta.hellohq.io/swagger/index.html

To get the documents you can use:
https://api.hellohq.io/v2/Documents

**Comment by monderino** [comment]
That is what I tried to explain.
There is no OAuth flow via App Id and secret implemented yet.

You can only generate an access token in helloHQ.
<img width="462" alt="Screenshot 2024-09-25 at 17 10 53" src="https://github.com/user-attachments/assets/ea4ab413-7fa9-43cf-9518-55313a1c1558">

**Comment by Shahzeb42Digital** [comment]
I got it, I was looking at API Clients section. Thanks!

**Comment by Shahzeb42Digital** [comment]
Hi Monderino,
I am using the endpoint https://beta.hellohq.io/v2/Documents. As it is in Beta version, can you mention the expected time of in production?

I want to get the custom fields and it is unclear how to get them. Can you help me in this regard as well?

BR,
Shahzeb

**Comment by monderino** [comment]
Hey,

the API will go in production mode in October. But this doesn't mean we have then more endpoints or you get more data.
Currently there is no plan to add the custom fields.
Your company can get in touch with your customer success manager to bring this topic more in focus.

Best 
Sven
