### ISSUE TITLE
Endpoint information regarding UserWorkingHours in V2

### ISSUE THREAD

**Issue by YashaErgon** [hellohq-io/hellohq.docs#188]
In HQ V1, we are accessing one endpoint called UserWorkingHours. In HQ V2, we did not find this endpoint.
Where can we find this information in HQ V2?

**Comment by YashaErgon** [comment]
Hi Sven,
Thank you for your reply. Do you know the timeline roughly when these endpoints will be availble in V2 as well?

Best regards,
Yasha

**Comment by monderino** [comment]
Hey,

Sorry but there is no timeline yet.

Best
Sven
