### ISSUE TITLE
Zapier Schnittstelle

### ISSUE THREAD

**Issue by UgurEroglu68** [hellohq-io/hellohq.docs#19]
**Describe**
Hallo, wir haben Factorial als führendes HR Tool im Einsatz bzw. werden wir im Einsatz haben, daher benötigen wir eine Schnittstelle von Factorial nach HQ, zumindest sollten folgende Punkte abgedeckt werden:

- Neuer Mitarbeiter
- Austritt Mitarbeiter
- Abwesenheiten

zusätzlich wäre noch:
- Zeiteintragungen

In Zapier sehe ich nur sehr wenige Schnittstellen, alles nur Projekt oder Lead relevantes aber nichts in Bezug auf Personal.

Könnt Ihr die oben erwähnten Schnittstellen in Zapier noch freischalten?
Bitte um Info
Danke
Lg
ugur

**Comment by monderino** [comment]
Hi @UgurEroglu68,

aktuell haben wir das nicht vorgesehen und können das auch nicht so einfach freischalten. 
Du kannst das aber gerne als Feature Request einreichen. Dafür schicke bitte eine mail an support@hellohq.io.

Vielen Dank und viele Grüße
Sven

**Comment by UgurEroglu68** [comment]
soweit ich weiß hat HQ eine offene API Schnittstelle, müsste kein großer Aufwand sein, diese in die Schnittstelle von zapier einzubauen. Wir möchten nicht die Abwesenheiten doppelt eintragen. Dass zumindest nur die Abwesenheiten übertragen werden würde uns in erster Linie auch reichen.

**Comment by monderino** [comment]
Das kann sein, da kenne ich mich zu wenig in Zapier aus. Es handelt sich hierbei jedoch um kein API Problem. Daher würde ich dich bitten den Weg über deinen Customer Success Manager zu gehen oder dich beim Support zu melden.

Danke dir.

Viele Grüße Sven
