### ISSUE TITLE
API V2 Pagination

### ISSUE THREAD

**Issue by mkaay** [hellohq-io/hellohq.docs#190]
Moin,
bei der V2 API scheint die Generierung des hellohq-nextlink Headers nicht richtig zu funktionieren.
Beispiel:

url: https://beta.hellohq.io/v2/Absences
hellohq-count: 17102
hellohq-nextlink: http://beta.hellohq.io/v2/Absences?$top=1000&orderby=id&$skip=1000

url: http://beta.hellohq.io/v2/Absences?orderby=id&$top=1000&$skip=1000
hellohq-count: 17102
hellohq-nextlink: http://beta.hellohq.io/v2/Absences?$top=1000&$top=1000&$orderby=id&$skip=1000

- Das Scheme ist http statt https
- $top wird dupliziert
- $skip nicht erhöht
- orderby mal mit, mal ohne $ prefix (was ist richtig?)

Wenn ich die richtigen Parameter für $skip generiere, bekomme ich zu wenig (?) Ergebnisse:
Bei $top=1000&$skip=0 -> 1000
Bei $top=1000&$skip=1000 -> 706
Bei $top=1000&$skip=2000 -> 0
hellohq-count Header sagt 17102 Ergebnisse, was ist korrekt?
Der hellohq-nextlink Header wird bis $skip=17000 zurückgegeben (aber ist weiterhin kaputt).

Viele Grüße,
Marius

Instanz: https://ameo-agentur.hellohq.io

**Comment by patrickkurras** [comment]
Moin @mkaay,

ich werde das direkt einmal genauer prüfen und mich danach hier nochmal bei dir melden.

Viele Grüße
Patrick

**Comment by patrickkurras** [comment]
Moin @mkaay ,

ich habe die Probleme gefunden und behoben. Bis das allerdings online ist, kann es ein klein wenig dauern. Ich vermute Anfang nächster Woche, aber Ich werde dir dann aber nochmal bescheid geben.

Zu dem "Count": dieser war falsch. Es gibt nur 1706 Abwesenheiten.

Viele Grüße
Patrick

**Comment by mkaay** [comment]
Super, danke dir! :)

**Comment by monderino** [comment]
Der Fix ist Online.

Viele Grüße
Sven
