### ISSUE TITLE
API v2 PlannedRevenue due date

### ISSUE THREAD

**Issue by sebjak11** [hellohq-io/hellohq.docs#191]
Hi,

ich habe leider keine Möglichkeit gefunden über die API schnittstelle (PowerBI) mir das Fälligkeitsdatum oder Enddatum eines Plansatzes zu ziehen. Das Date in der Documents Tabelle bezieht sich vermutlich auf das Erstellungsdatum oder Offerdatum und das validUntilDate ist für mich nicht nachvollziehbar.

Gibt es hier eine Möglichkeit mir ein Datum aus den Planumsatzeinstellungen zu ziehen? Oder muss man hier mit einem custom field arbeiten? Oder habt ihr vllt hier einen ganz anderen Ansatz?

Danke für die Hilfe!

Grüße
Basti

**Comment by monderino** [comment]
Hey @sebjak11,

wenn du ein get call machst auf die Version 1 unserer API, solltest du das DueDate als Ergebnis bekommen.
<img width="950" alt="Screenshot 2024-10-10 at 11 56 07" src="https://github.com/user-attachments/assets/0dabf344-5cc7-4fcb-87b5-81ed91c470d8">


Viele Grüße
Sven

**Comment by sebjak11** [comment]
Hi @monderino ,

danke für deine Antwort. Aber greift nicht v1 und v2 auf verschiedene Datenbanken zu? Hab ich jetzt ein Denkfehler?
Bekomme bei v1 die neuen Plansätze gar nicht erst angezeigt.

Beste Grüße,
Basti

**Comment by monderino** [comment]
Ah, Sorry.
ich habe das v2 im Titel übersehen.

In der V2 API haben wir aktuell noch keine Endpoints für Planumsätze.
Diese werden erst in den kommenden Monaten kommen.

Du kannst sie zwar mit dem Documents Endpoint abrufen, aber da fehlen die spezifischen Felder eines Planumsatzes.

Viele Grüße
Sven
