### ISSUE TITLE
API v2 - manual vs automatic Authentication

### ISSUE THREAD

**Issue by RetsonOcin** [hellohq-io/hellohq.docs#192]
Hello,

I would like to migrate our internal system to your new API 2.0, even though it is still in development.

I’ve just noticed that I can’t access /v2/ without the required authorization. So I would like to update this as well.

However, from what I understand from your dev documentation, you need to create an access token in the admin interface for each user who logs in via HQ with their corresponding account, correct?

In other words, authorization for v2 is currently not handled via the API but manually by creating access tokens for the users?

This is, of course, inconvenient and not practical for our system. Have I missed an alternative approach or misunderstood something?

Could you perhaps share a method to authorize a user via an API call, as is currently possible with v1 using a GET request to https://api.hqlabs.de/Account/Authorize?response_type=code&...?

I would appreciate your feedback.

Kind Regards,
  Nico

**Comment by monderino** [comment]
Hey @RetsonOcin,

thanks for your question.
True, currently you cannot use the OAuth flow in v2. This will probably available in 2025.

Currently you can create a token in our Admin section. One for all or for every user a token. This depends on your use case.
Could you explain what you want to achieve with our API?

Best Sven
