### ISSUE TITLE
V1 ProjectTasks endpoint delivers some incomplete or false metrics

### ISSUE THREAD

**Issue by DominikFischer86** [hellohq-io/hellohq.docs#193]
**Describe the bug**
I am using the API to fetch data in order to create internal reports.
Right now I am using the projectTasks endpoint to fetch information about the Id, Name, PlannedEffort and IsDone status. This works fine so far.

I was tasked to also retrieve the actual effort, however I cannot seem to find the metric that is ought to be tracked.

See this example:
![hq_actual_result](https://github.com/user-attachments/assets/5800b6de-3378-4eb5-b4f6-4fc9b75d2ae5)

As you can see, the **PlannedEffort** is 20h. The task is marked as done, but only _87%_ of the time was needed (or _17.59h_).
I would expect the API to deliver the **actualEffort** as _17.59_, but there is no value representing that.

This is the data I receive when fetching the endpoint:
![hq_api-result](https://github.com/user-attachments/assets/f3d50641-8b2b-4c88-b4d1-d9cfc094aef6)

At the very least I would expect these existing metrics to have the following values:
```
PercentDone: 87
Remaining: 2.01
```

This way I could at least calculate the **actualEffort**, but as you can see the values are not correct in the response data. 
It claims **PercentDone** is _100_ and **Remaining** is _0.0_ ( and seems to be in all other projectTasks that I checked, too). 
I found the occasional **PercentDone** between _0_ and _100_, but that doesn't appear to be reliable, given it should be not _100_ in this particular case.

Also I don't think I should need to have to calculate the **actualEffort** on my end, when the data might as well just get delivered as is.

Am I missing something? Or could this be a bug on your end?

Any help would be greatly appreciated.

**Comment by monderino** [comment]
Hey @DominikFischer86,

Thank for the information. I will check this and let you know.

Best
Sven

**Comment by patrickkurras** [comment]
Hallo @DominikFischer86,

I checked it and there is no issue at our side. Both field are part of out "Task" modal and can be set manually in project plan. 
The sum of all reportings is not part of the modal, so you can only get the value via the API by doing an other call of all reportings and calculating the value yourself from the sum and the PlannedEffort.

Please get in touch if you have any further questions.

Best regards,
Patrick

**Comment by DominikFischer86** [comment]
I see. Thanks for checking it out.
It still would be a better experience if the total effort was a metric on this endpoint, where I expect it, together with the PlannedEffort. I hope you take it into consideration for the future.

Best regards
Dominik
