### ISSUE TITLE
V2 Endpoints: IncomingInvoices, Invoices, 

### ISSUE THREAD

**Issue by drkn-nh** [hellohq-io/hellohq.docs#194]
Is there a roadmap for currently missing V2 endpoints, such as IncomingInvoices or Invoices?

We would love to switch to the new Finanzprozess 2.0, but need the incoming invoices API to do so.

Thanks in advance!

**Comment by patrickkurras** [comment]
Hi @drkn-nh, 

We have decided not to separate the endpoint by document type in the V2 version. When creating and also when getting, you can simply filter according to the document type.

So the changeover would already be possible for you.

Feel free to get in touch if you have any further questions.

Kind regards,
Patrick
