### ISSUE TITLE
Wo finde ich in der API v2 Tasks, Planumsätze, etc

### ISSUE THREAD

**Issue by vonBartsch** [hellohq-io/hellohq.docs#195]
guten tag,
wir planen zum ende des jahres hq auf die version 2 umzustellen. da wir für unser unternehmensweites controlling die api benötigen konnte ich aus der dokumentation noch nicht entnehmen wie es mit den planumsätzen sowie plankosten, projekt-tasks gehen soll.

könnt ihr hier weiterhelfen oder einen ansatz geben wo ich dies nachlesen kann?

vielen dank, dominique

**Comment by Schaukelking** [comment]
Hey @vonBartsch 

die Endpunkte befinden sich aktuell in der Entwicklung und werden bald möglichst online gestellt. Ich kann dir gerne hier Bescheid geben, sobald das der Fall ist. 

Beste Grüße
Patrick

**Comment by Schaukelking** [comment]
Hey @vonBartsch 
wir haben die API Endpunkte für die Projekt-Tasks nun online (zu finden unter "Projects").

Außerdem haben wir nun auch GET Endpunkte für Planumsätze und Plankosten (unter "PlannedRevenues" und "PlannedCosts"). 

Weitere Endpunkte für Planumsätze/-kosten sind grade in Planung. Brauchst du gezielt weitere Endpunkte oder hat sich dein Problem mit den neuen Endpunkten jetzt gelöst? 

Beste Grüße
