### ISSUE TITLE
GET /v1/Users({Id})/UserWorkingHours in v2?

### ISSUE THREAD

**Issue by RetsonOcin** [hellohq-io/hellohq.docs#196]
Hallo,

kommt man über einen v2 Endpunkt an die working hours eines Users? Leider habe ich dazu keinen passenden Endpunkt in swagger gefunden.

Viele Grüße,
  Nico

**Comment by monderino** [comment]
Hey @RetsonOcin,

du meinst das gleiche Verhalten wie hier: /v1/Users({Id})/UserWorkingHours aus der API v1 oder Zeiten die ein User tatsächlich gearbeitet hat?

Viele Grüße
Sven

**Comment by RetsonOcin** [comment]
ja genau

**Comment by RetsonOcin** [comment]
Ja exakt!

Viele Grüße,
   Nico

**Comment by monderino** [comment]
Hey Nico,

das war eine oder Frage ;). 
Also zu dem Ersten: Da gibt es aktuell noch kleinen Endpoint. Wir werden den aber demnächst einplanen.
Zum 2: Da kommen Endpoints zum nächsten Release.

Viele Grüße
Sven
