### ISSUE TITLE
Expanding Users API call by UserWorkingHours returns 500 error

### ISSUE THREAD

**Issue by chrgruber** [hellohq-io/hellohq.docs#2]
**Describe the bug**
When trying to expand the Users API call by UserWorkingHours I simply get an internal server error as a response.

**To Reproduce**
1. curl https://api.hqlabs.de/v1/Users?$expand=UserWorkingHours
2. Response: Oops! Sorry, something went wrong. Please contact us in our developer portal at https://developer.helloHQ.io so we can assist you.

**Expected behavior**
I expect this call to return a list of all registered users in HQ along with the field UserWorkingHours

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Postman
 - Version 8.0.5

**Additional context**
Works when expanding with other parameters

**Comment by monderino** [comment]
Hi @chrgruber,

thanks for trying our api.
I will check your issue and come back with a solution.

Best regards 
Sven

**Comment by monderino** [comment]
Hi @chrgruber,

the issue is fixed by now. Thanks for reporting it.

Have a nice day.

Best regards
Sven
