### ISSUE TITLE
Unter welchem API Endpoint werden die "Lieferantengutschriften" geliefert?

### ISSUE THREAD

**Issue by efandy** [hellohq-io/hellohq.docs#20]
Ich würde gerne die Lieferantengutschriften mittels API abfragen. Wenn ich die v1/Invoices Abfrage sehe ich die Stornos und die Rechnungen, die Lieferantengutschriften sehe ich leider nicht.

Vielen Dank für ein kurzes Feedback.

**Comment by monderino** [comment]
Hi @efandy,

Gutschriften kannst du unter /v1/Quotations abrufen. Hier der Link zu Dokumentation https://developer.hellohq.io/docs/#tag/Documents-Quotations

Viele Grüße
Sven

**Comment by efandy** [comment]
@monderino Ich meine nicht die Angebote sondern "Lieferantengutschriften". Über den Quotations Endpoint kriege ich die Angebote. Hier die Belege-Übersicht:

<img width="313" alt="grafik" src="https://user-images.githubusercontent.com/95030081/148374917-f8aac051-27ca-43df-b74b-c814147d4d27.png">

Ich meine das GS-### Element.

**Comment by monderino** [comment]
Ah, sorry da habe ich mich verlesen.
Aktuell geben wir keine Gutschriften über die API aus. 

Für welchen Kunden möchtest du diese gerne abrufen?

**Comment by efandy** [comment]
@monderino das wäre für den Kunden Emil Frey Digital.

**Comment by monderino** [comment]
Hi @efandy, 

da wir hier aktuell keine Endpoints für haben, habe ich eurem Customer Success Manager bescheid gegeben. Er wird sich bei euch melden und klären wie wir hier weiter vorgehen können.

Viele Grüße
Sven
