### ISSUE TITLE
How do I retrieve the PDF of an offer?

### ISSUE THREAD

**Issue by kfina-planxy** [hellohq-io/hellohq.docs#200]
**Describe**
Is there a way to retrieve the PDF file of a document (offer) in the API? (If not, please consider this a feature request)

**Additional context**
Preferably in the v2 API.

**Comment by monderino** [comment]
Hey @kfina-planxy,

yes there is. When you fetch a document it has an attachments object include. There you find all attachments and alink to download them from our files endpoint.
![Screenshot 2024-11-25 at 14 04 35](https://github.com/user-attachments/assets/ba8e5366-5c41-4e19-adf0-46aa44a859db)

Best 
Sven

**Comment by kfina-planxy** [comment]
Hello Sven,

thanks for the quick replies! :)

the api returns `"attachments": null` for me for all our documents.
Maybe you misunderstood, I am not talking about attachments, I would like to download the document itself as a PDF.
The same PDF that you would get by clicking "Dokument herunterladen" in the UI. (see image below)
![image](https://github.com/user-attachments/assets/43857e1b-5c70-45e7-9e9f-ea4d11320f1b)

Kind regards,
Kenten Fina

**Comment by monderino** [comment]
Hey,

the PDF of the document should be part of the attachments.
Can you please try to add expand=attachments to your url. 
Example: /v2/Documents/id?expand=attachments

If this is not working, please tell me you helloHQ domain and the Id of the document and I will check it.

Best Sven

**Comment by kfina-planxy** [comment]
Thank you!

`?expand=Attachments` did the trick.

Kind regards,
Kenten Fina

**Comment by monderino** [comment]
Ah Perfect. 
With the next release in December, the documentation in Swagger will bet better. Then you can see if you need an expand or not.

Best 
Sven

**Comment by kfina-planxy** [comment]
Hey again,

sorry, but I have another question about this. When I query a Document, which was created via the API, the attachments array is empty, even when querying with ?expand=Attachments. Is that a bug?

our domain: `https://mobile-spaces.hellohq.io/`
created via API: `/v2/Documents/1538?expand=Attachments` (attachments is empty)
created via UI: `/v2/Documents/1530?expand=Attachments` (attachment contains file)

**How I created the document:**
1. POST /Documents { documentType: 'Quotation', ...data }
2. POST /DocumentPositions/ServicePosition { documentEntityId: 1538, documentTableId: ..., servicePriceId: ... } // multiple times

Kind regards,
Kenten Fina

**Comment by monderino** [comment]
Hey @kfina-planxy,

Thanks for the question. I will check it.

Please do me a favor and create a new issue next time. Because we do not screen closed issues.

Thank you

**Comment by monderino** [comment]
Hey,

I checked it now. Currently when you create document via the API we do not create a PDF directly. We do not expect that the PDF is need until the Document was changed into a final state. This means when you change the status to 'sent' as example, we generate a PDF.

What is your use case behind it? 

Regarding your note. I was not able to check what happen in the UI because the document with id 1543 was deleted already.
If you have this again please do not delete the document and send it to us. Then we will check again.

Thanks.

**Comment by kfina-planxy** [comment]
> Hey @kfina-planxy,
> 
> Thanks for the question. I will check it.
> 
> Please do me a favor and create a new issue next time. Because we do not screen closed issues.
> 
> Thank you

Okay, will do that next time.



> Hey,
> 
> I checked it now. Currently when you create document via the API we do not create a PDF directly. We do not expect that the PDF is need until the Document was changed into a final state. This means when you change the status to 'sent' as example, we generate a PDF.
> 
> What is your use case behind it?
> 
> Regarding your note. I was not able to check what happen in the UI because the document with id 1543 was deleted already. If you have this again please do not delete the document and send it to us. Then we will check again.
> 
> Thanks.

Our use case it to preview the pdf document and let a user check it before it is sent out.
Using the `POST v2/Document/{id}/ChangeStatus` with `{"documentStatusId": 3}` (for accepted) and then `{"documentStatusId": 1}` to put it back to draft, worked.

Thank you!
