### ISSUE TITLE
v2 API - How to obtain PricePositions for Services

### ISSUE THREAD

**Issue by kfina-planxy** [hellohq-io/hellohq.docs#201]
**Describe**
When browsing the website > services > choose an article: There is a list of possible prices listed below. (In our example price for rent for 1 month, price for rent for 2 months... 12 months). It shows only these 12 entries.
When using the "api.hellohq.io/v2/Services" endpoint, I was looking for those entries, but I can only find them in "documentPositionEntities", where they are mixed with all instances of that service that have been added to some invoice or offer at some point and there isn't even a flag provided that would allow me to filter these documentPositionEntities. Much preferably, since we plan on regularly using the "Services" endpoint to obtain up to date prices, we would prefer an endpoint, where we ONLY get the services and the same price articles listed in the UI, without all the instances on some offer.

**Steps to reproduce**
via UI:
1. Go to services -> create a new article
2. Add a single price position to that article
3. Go to documents -> offers and create an offer
4. Add a ServicePosition to that document, by selecting the new created article and its price
5. api.hellohq.io/v2/Services/{id} endpoint now returns 2 "documentPositionEntities" instead of one.

**Comment by monderino** [comment]
Hey @kfina-planxy,

this sound like a Bug. Thanks for pointing this out.
I will have a look into it.

Best 
Sven

**Comment by monderino** [comment]
Fix is online
