### ISSUE TITLE
v1. Missing Subsystem Field in Server Response

### ISSUE THREAD

**Issue by ilyaart1972** [hellohq-io/hellohq.docs#203]
I receive all project fields except for the **subsystem** field(s). 
What could be the reason, and how can I resolve this issue? 

Thank you!

**Comment by ilyaart1972** [comment]
v1/Projects?$expand=Subsystems I tried this.
I can see Subsystems in the helloHQ UI.
The result does not depend on the project.
Subsystems are missing in all requests, for all projects.
The domain is omniphon3. Thank you!

**Comment by monderino** [comment]
I tested it and when I do a call like this:
https://api.hellohq.io/v1/Projects?$expand=Subsystems

The result contains the subsystems.

Best 
Sven

**Comment by ilyaart1972** [comment]
It really works. I don’t know what I was doing wrong before. Thank you!
