### ISSUE TITLE
v2 API - Adding a service position reports 404: 

### ISSUE THREAD

**Issue by kfina-planxy** [hellohq-io/hellohq.docs#204]
**Describe the bug**
When adding a DocumentPosition to a Document from an existing servicePosition, the API returns 404 with `{"message": "Parameter textFieldId: is not valid"}`, but textFieldId is not mentioned in the docs.

**To Reproduce**
1. Create a new document via `POST /v2/Documents`
2. Add an existing service position to it: `POST /v2/DocumentPositions/ServicePosition` with payload
```
{"documentEntityId":1586,"documentTableId":"562e1c6b-2ab3-41d1-8509-601737a525f3","servicePriceId":1038}
```

**Expected behavior**
The servicePosition is added to the document.

**Actual behavior**
`POST /v2/DocumentPositions/ServicePosition` returns a 404 with the following error:
`{"message": "Parameter textFieldId: is not valid"}`

**Environment (please complete the following information):**
 - Version2 API

**Additional context**
- I previously added servicepositions successfully to the document successfully with this setup. It stopped working recently.
- using `POST /v2/DocumentPositions/FreeTextPosition` returns the same error.

**Comment by monderino** [comment]
Hey @kfina-planxy 

Thanks, I will check it immediately.

**Comment by monderino** [comment]
The issue will be fixed by tomorrow.

**Comment by kfina-planxy** [comment]
Thank you for the quick responses!
That sounds great!

**Comment by monderino** [comment]
Issue fixed
