### ISSUE TITLE
Get all ProjectTasks for a given ProjectId

### ISSUE THREAD

**Issue by TristanWie** [hellohq-io/hellohq.docs#21]
Moin Moin,
wir möchten eure API nutzen um Reportings anzulegen. Unser eigenes Tool hat die Projekte aus HQ mit der dazugehörigen ID in einer eigenen Datenbank abgelegt. Mit der ID kann ich problemlos Reportings anlegen. 

Im Regelfall haben die Projekte bei uns aber auch Tasks, die ihnen zugewiesen sind (s.unten). 
Wenn ein user unseres Tools ein Reporting für einen Projekt MIT einem Task anlegen möchte, fehlt ihm jetzt die TaskId.  
Ist es möglich, nur mit der ProjectId (1234) einen Request zu machen, um alle Tasks mit der ProjectId 1234 zu bekommen?

Project {
id: 1234
name: Ein Projekt
...
}

ProjectTask {
id:1
name: Task 1
ProjectId: 1234
...
}
ProjectTask {
id:2
name: Task 2
ProjectId: 1234
...
}

RESPONSE:
ProjectTasks = [
  {
    id:1
    name: Task 1
  },
  {
    id:2
    name: Task 2
  }
]

**Comment by Schaukelking** [comment]
Hey Tristan!
Wenn du alle Tasks eines Projects haben willst kannst du den ProjectTasks endpoint nutzen und nach der ProjektId filtern:
http://api.hqlabs.de/v1/ProjectTasks?$filter=ProjectId eq [id]

Mehr zum Thema Filter findest du hier: https://developer.hellohq.io/#filter-by-date-and-time
Informationen zu ProjectTasks findest du hier: https://developer.hellohq.io/docs/#tag/Projects-Project-Tasks

Hoffe ich konnte dir weiter helfen, wenn nicht melde dich nochmal (: 

Beste Grüße
Padsen

**Comment by TristanWie** [comment]
Hey Padsen!
Das war genau, wonach ich gesucht habe. 
Mega danke und beste Grüße!!
