### ISSUE TITLE
ResponsibleUser nicht in API Abfrage für Companies enthalten

### ISSUE THREAD

**Issue by medienkontorFulda** [hellohq-io/hellohq.docs#22]
Hallo zusammen,

da man über das Excel-API Addin nicht an den Wert für den Verantwortlichen für einen Kunden herankommt, habe ich auf Anraten eures Supports versucht, die Abfrage über Excels PowerQuery laufen zu lassen. In der API Doku steht beim [GET für die Companies-Tabelle](https://developer.hellohq.io/apidocs/#/Companies%20-%20Companies/get_v1_Companies), dass es das Feld "ResponsibleUsers" gibt. Doch dieses taucht bei keiner Abfrage auf, weder über die PowerQuery, noch via Postman.
Existiert das Feld noch, oder muss ich die Query anpassen, damit er es ausgibt?
Wie komme ich an den Verantwortlichen für eine Firma ran?

Vielen Dank!

**Comment by patrickkurras** [comment]
Hallo @medienkontorFulda,

die ResposibleUser bekommst du von dem Companies nur mit einem expand zurück. Dazu muss die URL so aussehen:
`https://api.hqlabs.de/v1/Companies?$expand=ResponsibleUsers`

Ich hoffe das hilft dir weiter und melde dich gerne, wenn du noch weitere Fragen dazu hast.

Viele Grüße
Patrick
