### ISSUE TITLE
Bei der autom. Übergabe von Jobs werden von HQ keine Tasks generiert.

### ISSUE THREAD

**Issue by dkluesener** [hellohq-io/hellohq.docs#23]
**Describe**
Zeitweise werden bei der autom. Übergabe keine Tasks mehr im Projektplan generiert.

**Comment by monderino** [comment]
Hi @dkluesener,

kannst du uns bitte weitere Informationen dazu liefern?
- Welchen Endpoint rufst du auf
- Welche Daten sendest du
- In welchem HQ System arbeitest

Viele Grüße
Sven

**Comment by dkluesener** [comment]
Hallo Sven,
ich rufe keinen Endpoint auf, die Daten werden von unserer EtoE-Bridge automatisch übergeben/-nommen.
Ich arbeite im System von Landwirtschaftsverlag GmbH Münster.

Viele Grüße 
Dirk

**Comment by monderino** [comment]
Hi Dirk,

danke für die Infos. Tritt das beim anlegen eines Projektes auf?
Kannst du mir Beispiele nennen? Also bei welchem Projekt welche Tasks angelegt würden und welche nicht?

Viele Grüße
Sven

**Comment by dkluesener** [comment]
Hallo Sven,

zuletzt trat das Problem beim Job: "22-00127 - Buch > AT Kapuzinerkochbuch" auf.
Es gab nur den Task "Administration". 
Gefehlt haben:
+ GESTALTUNG
+ SATZ/LAYOUT
+ ANZEIGEN SATZ/LAYOUT
+ BILDBEARBEITUNG
+ AUSGABE
+ KORREKTORAT
+ PROJEKTARBEIT
+ DIGITAL
+ BILD UND TON
diese konnten wir nachträglich über Bearbeiten - Projektplan importieren hinzufügen.

Viele Grüße
Dirk

**Comment by monderino** [comment]
Hi Dirk,

Wenn ich das richtig verstehe geht es hier um den Opix-Sync, Korrekt?
Ich schaue mir das an und geben dir eine Rückmeldung.

Viele Grüße und ein schönes Wochenende
Sven

**Comment by dkluesener** [comment]
Hi Sven,

ja das ist richtig.

Dir auch erst mal ein schönes Wochenende und Danken schon mal.
Dirk

**Comment by monderino** [comment]
Hallo Dirk,

wir haben den Opix Sync noch einmal untersucht und einige Änderungen vorgenommen. Dies behebt die Probleme hoffentlich.
Sollte es doch wieder zu dem Fehler kommen, melde dich bitte bei uns direkt im Support.

Viele Grüße
Sven
