### ISSUE TITLE
HQ x Power BI

### ISSUE THREAD

**Issue by WCLightning** [hellohq-io/hellohq.docs#24]
Hi, 
I am currently working on the interface between HQ and Power BI via the API and I am looking for a way to filter invoices by articels contained in them. For example, I would like to display all invoices in which a certain articel was sold.

Unfortunately, I can't find any columns in the default transmitted data about invoices or projects that highlight info about the articles that are on the invoice. 

I then tried to expand the BaseUrl of the query --> "https://api.hqlabs.de/v1/Invoices?$expand=Positions". 
Unfortunately, also without success.

The same applies to the query of custom fields (leads and projects). Which BaseUrl do I need to enter to transfer these fields to Power BI?

**Comment by monderino** [comment]
Hi @WCLightning,

if you fetch invoice created with articles you able to see it in the positions. If I use these calls in my test system:
https://api.hqlabs.de/v1/Invoices(1449)?$expand=Positions // 1449 is an id of an invoice
https://api.hqlabs.de/v1/Invoices?$expand=Positions

Then I can see the article id n the position:

![Screenshot 2022-02-16 at 09 12 43](https://user-images.githubusercontent.com/23459030/154222850-eed71202-b27f-4a3e-943b-c63050a432f0.png)

To fetch leads or projects with custom fields you need to expand it:
https://api.hqlabs.de/v1/Leads?$expand=CustomFields
https://api.hqlabs.de/v1/Projects?$expand=CustomFields

Not sure if this is the answer of your question. If not please send me more information:
- Your System
- The call and what you expect

Best regards 
Sven

**Comment by WCLightning** [comment]
Hi Sven,

thank you very much for the quick reply.
Unfortunately this doesn't work. 
I would like a column to be transferred into Power BI from which the article positions in the respective invoices originate. 

Here is a screenshot of my query (I have hidden API token) and the error message:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/99743965/154229346-1f77fb3b-3cee-46ab-9e60-5ec63cd38276.png">
<img width="562" alt="image" src="https://user-images.githubusercontent.com/99743965/154229427-67b20585-7a57-4307-a5fe-581d5cc4ca17.png">

I get the same error message for the custom fields.

**Comment by monderino** [comment]
Hi @WCLightning,

from the error I can see that you missed some & sign.
The correct call looks like this: https://api.hqlabs.de/v1/Invoices?$expand=Positions&$top=10&$skip=0&$count=true

Best regards
Sven
