### ISSUE TITLE
ResponsibleUserId in GUI

### ISSUE THREAD

**Issue by fdutenho** [hellohq-io/hellohq.docs#26]
Your API (see https://developer.hellohq.io/apidocs/#/Projects%20-%20Projects/get_v1_Projects__Id__) answers with a JSON describing a project. In that JSON is a field called "ResponsibleUserId". How/where do I set/edit this information in the GUI?

**Comment by Schaukelking** [comment]
Hey!

With GUI you mean the HQ itself? 
This field is just for internal projects. In internal projects the contact person you select while creating the project will be someome from the own company. This is the responsible user.

You can change it then in the "Customer" tab in the project details. 

Hope this helps you out. If not please hand out more details about what you are looking for.

Best Regards
Padsen

**Comment by fdutenho** [comment]
Thanks. Got it. Thought it's the internal responsible employee for external projects. Guess I have to go for project mangers of the project team...

**Comment by fdutenho** [comment]
Thanks. Got it. Thought it's the internal responsible employee for external projects. Guess I have to go for project mangers of the project team...
