### ISSUE TITLE
API Läd zu lange, kann ich auch nur bestimmte Teile Laden

### ISSUE THREAD

**Issue by MichaelPolaris** [hellohq-io/hellohq.docs#27]
Moin moin,
ich hab folgendes Problem.
Wenn ich die "UserReportins" mit Excel oder Power Bi herunterladen will dauert es ewwwwwigkeiten.
Kann ich nur einen bestimmten Teil herunterladen?
Datum von bis z.B.
oder nur aktive Kunden UserReportings
oder nur Reportings einer bestimmten Person.

Ich hoffe Ihr könnt mir Helfen.

Michael 
Polaris Media

**Comment by monderino** [comment]
Hi @MichaelPolaris,

wir benutzen den OData Standard. Daher kannst nach beliebigen Properties filtern.
Einen Link zu OData und ein Beispiel zu den Filtern findest du auf developer.hellohq.io.

Hier noch ein Bespiel für einen Filter auf einen Zeitbereich: https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn gt 2022-01-26T18:15:00Z and UpdatedOn lt 2022-02-26T18:15:00Z

Wenn du noch weiter Hilfe benötigst meld dich gerne wieder.

Viele Grüße
Sven

**Comment by MichaelPolaris** [comment]
Moin moin Sven,
ich bekomme leider eine Fehlermeldung. Hab LEIDER nie programmieren gelernt, hatte deinen Zusatz drangesetzt und bekomme dann eine Fehlermeldung (unten dann noch die abfrage):

DataSource.Error: Fehler beim Abrufen von Inhalten von "https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn%20gt%202022-01-26T18:15:00Z%20and%20UpdatedOn%20lt%202022-02-26T18:15:00Z$count=true&$top=0" (400) durch "Web.Contents": Bad Request
Details:
    DataSourceKind=Web
    DataSourcePath=https://api.hellohq.io/v1/UserReportings
    Url=https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn%20gt%202022-01-26T18:15:00Z%20and%20UpdatedOn%20lt%202022-02-26T18:15:00Z$count=true&$top=0


------


let 
    BaseUrl         = "https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn gt 2022-01-26T18:15:00Z and UpdatedOn lt 2022-02-26T18:15:00Z",
    Token           = "LMWeAft5ZqBLnbLifQn2BbWRlhZMVKUW7TTCT484dFu0aytP4iQ4XhYi4rpXHtM2ZU4m_cs4UAQukuh9qcC4Hkt-DOSVqbmkxhlp8JqpbPr2NCoO3dOEpQYVPJuIDvLw8ns7zWqd9UXx8KzUcKy6rJhJ_v083OAF13B5R0Z_EKF2YQdiS-q4yqJ0rCVNCHORYSIS5bidPennnUXQv4SR-oTrRYb7c0Uwp32TZfTJdjI",
    EntitiesPerPage = 1000,
 
    GetJson = (Url) =>
        let Options = [Headers=[ #"Authorization" = "Bearer " & Token ]],
            RawData = Web.Contents(Url, Options),
            Json    = Json.Document(RawData)
        in  Json,
 
    GetEntityCount = () =>
        let Url   = BaseUrl & "$count=true&$top=0",
            Json  = GetJson(Url),
            Count = Json[#"@odata.count"]
        in  Count,
 
    GetPage = (Index) =>
        let Skip  = "$skip=" & Text.From(Index * EntitiesPerPage),
            Top   = "$top=" & Text.From(EntitiesPerPage),
            Url   = BaseUrl & Skip & "&" & Top,
            Json  = GetJson(Url),
            Value = Json[#"value"]
        in  Value,
 
    EntityCount = List.Max({ EntitiesPerPage, GetEntityCount() }),
    PageCount   = Number.RoundUp(EntityCount / EntitiesPerPage),
    PageIndices = { 0 .. PageCount - 1 },
    Pages       = List.Transform(PageIndices, each GetPage(_)),
    Entities    = List.Union(Pages),
    Table       = Table.FromList(Entities, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
in
    Table

**Comment by monderino** [comment]
Hey Michael,

kein Problem wir schauen uns das an.
Ich haben mal deinen Kommentar editiert und den Token entfernt.... Bitte NIEMALS solche Informationen veröffentlichen, da sonst jeder der diesen Token hat auch potentiel Zugriff auf eure Daten bekommt.

**Comment by monderino** [comment]
Es fehlte ein & vor dem $count
Hier die richtige Abfrage:
https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn gt 2022-01-26T18:15:00Z and UpdatedOn lt 2022-02-26T18:15:00Z&$count=true&$top=0

Wenn du count mit in der URL hast bekommst du aber nur die Anzahl wie viele Daten vorhanden sind. Damit du Daten bekommst musst du das count entfernen, also am besten so:
https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn gt 2022-01-26T18:15:00Z and UpdatedOn lt 2022-02-26T18:15:00Z

Viele Grüße
Sven

**Comment by MichaelPolaris** [comment]
moin moin und Danke. Kann den Chat hier jeder sehen ? (wegen dem token)

**Comment by MichaelPolaris** [comment]
BaseUrl         = "https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn gt 2022-01-26T18:15:00Z and UpdatedOn lt 2022-02-26T18:15:00Z",
wenn ich die abfrage jetzt so rein kopiere, kommt dieser Fehler:
DataSource.Error: Fehler beim Abrufen von Inhalten von "https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn%20gt%202022-01-26T18:15:00Z%20and%20UpdatedOn%20lt%202022-02-26T18:15:00Z$count=true&$top=0" (400) durch "Web.Contents": Bad Request
Details:
    DataSourceKind=Web
    DataSourcePath=https://api.hellohq.io/v1/UserReportings
    Url=https://api.hellohq.io/v1/UserReportings?$filter=UpdatedOn%20gt%202022-01-26T18:15:00Z%20and%20UpdatedOn%20lt%202022-02-26T18:15:00Z$count=true&$top=0

**Comment by monderino** [comment]
> moin moin und Danke. Kann den Chat hier jeder sehen ? (wegen dem token)

Ja, das hier ist öffentlich

**Comment by monderino** [comment]
Es fehlt immer noch ein &, das count ist auch noch enthalten und top=0 führt dazu das du keine Daten bekommst.
<img width="843" alt="Screenshot 2022-04-01 at 10 59 48" src="https://user-images.githubusercontent.com/23459030/161231625-f4e5b1d9-383d-4f7e-a0d9-8610885ae97d.png">

Ich denke du musst da etwas in deinem Skript anpassen

**Comment by monderino** [comment]
Hi Michel,

kannst du da bitte Kontakt mit deinem Success Manager aufnehmen? Der kann dir da besser weiterhelfen.
