### ISSUE TITLE
Zahlungseingang vermerken

### ISSUE THREAD

**Issue by libako-360** [hellohq-io/hellohq.docs#29]
Der Support Chat hat mir empfohlen hier meine Frage zu stellen. :-)

**Frage**
Ist es möglich über die API den Zahlungseingang bei einer Rechnung zu vermerken?

**Hintergrund**
Ich möchte GetMyInvoices (GMI) bitten, hier die Integration zu verbessern. Zwar gibt es einen Import von Rechnung von HQ nach GMI und GMI gleicht das Konto ab ob eine Zahlung beglichen wurde - allerdings müsste man hier wieder manuell tätig werden und dann in HQ manuell den Zahlungseingang vermerken.

**Comment by patrickkurras** [comment]
Moin,

leider ist es aktuell nicht möglich direkt einen Zahlungseingang über die API zu vermerken. Rechnungen können aber in der API auf den Status "Vollständig bezahlt" gestellt werden. Im HQ selber ist damit dann der Rechnungsbetrag nicht mehr offen.

Generell bauen wir gerade den ganzen Finanzprozess neu und im Zuge dessen wird es man auch einen Zahlungseingang über die API setzen können. Dies wird allerdings noch ein wenig dauern bis dieser abgeschlossen ist.

Viele Grüße
Patrick
