### ISSUE TITLE
Wie komme ich an einen Access Token, um per Python Skript auf die Rest-API zugreifen zu können?

### ISSUE THREAD

**Issue by septemberAndreas** [hellohq-io/hellohq.docs#30]
**Describe**

**Additional context**
Add any other context about the question here.
- Screenshots
- Curls
- etc

**Comment by monderino** [comment]
Hi @septemberAndreas ,

Wenn du dich in dein HQ einloggst, findest du im Menu unter Admin => API Clients den Token.

Viele Grüße
Sven
