### ISSUE TITLE
Extract total planned hours for each project

### ISSUE THREAD

**Issue by theresa-sporn** [hellohq-io/hellohq.docs#32]
**Describe**
Hello! How can I extract the total planned hours for each project (see screenshot)? I can't find the information in the documentation. Thank you!

**Additional context**
![image](https://user-images.githubusercontent.com/72218893/166936885-c7f0b5c6-5d68-481f-a5de-d5eae5879c83.png)

**Comment by patrickkurras** [comment]
Hi Theresa,

unfortunately we don't have these values in our API right now. Please contact you Customer Success Manager to find a solution for that.

I wish you a great weekend.

Cheers, Patrick

**Comment by theresa-sporn** [comment]
Hi Patrick, 

thank you for your answer. Could you please provide me with the contact details of the Customer Success Manager?

Thanks a lot!
Cheers, Theresa

**Comment by patrickkurras** [comment]
Hi,

Normally, each of our customers is assigned a permanent customer success manager. But you can send me the name of your company and I'll ask who it is in your case.

Cheers, Patrick

**Comment by theresa-sporn** [comment]
Hi Patrick, 

the company is called Speedinvest Heroes Consulting Gmbh, thank you!

Best, Theresa

**Comment by patrickkurras** [comment]
Hi Theresa, 

Marion Fischer is your customer success manager at HQLabs. You can just contact him by mail at marino@hellohq.io with a short descriptions of the issue and for what exactly you need these values.

Cheers, Patrick
