### ISSUE TITLE
API Call für Ressource Gruppen

### ISSUE THREAD

**Issue by septemberAndreas** [hellohq-io/hellohq.docs#33]
Hi HQ-Dev Team, ... gibt es einen API Call (GET) für die Ressourcegruppen?
Danke! -a

**Comment by monderino** [comment]
Hi @septemberAndreas,

aktuell haben wir keinen Endpoint um die die Ressourcengruppen abzurufen.
Du könntest sie dir aber über die User holen : https://api.hellohq.io/v1/Users?$expand=ResourceGroup außer du hast Gruppen die keinen User besitzen. Diese kannst du nicht bekommen.

Viele Grüße
Sven
