### ISSUE TITLE
Projektleiter in Stammdaten Projekt / API endpoint projects

### ISSUE THREAD

**Issue by septemberAndreas** [hellohq-io/hellohq.docs#34]
Hi,  ich suche nach dem Projektleiter in den Projektstammdaten.
Endpoint: Projects
Aber die "ResponsibleUserId gibt mir nicht den im Frontend sichtbaren PL, sondern ein Teammitglied.
Wo kann ich pro Projekt den PL auslesen? THX -a

**Comment by monderino** [comment]
Hi @septemberAndreas,

dies wird ja in der Projektrolle spezifiziert. Diese kannst du mit einem expand abrufen, hier ein Beispiel:
Alle Projekte: 
https://api.hellohq.io/v1/Projects?$expand=Members($expand=ProjectRole)
Einzelnes Projekt:
https://api.hellohq.io/v1/Projects(320)/Members?$expand=ProjectRole

Viele Grüße
Sven
