### ISSUE TITLE
potenzieller Wechselkurs-Bug?

### ISSUE THREAD

**Issue by ilia-piabo** [hellohq-io/hellohq.docs#36]
Hallo, 

mein Name ist Ilia und ich entwickle momentan Dashboards anhand Google Data Studio für meine Firma und ziehe dazu Daten aus HelloHQ (über eure API). Das Problem, das ich gestern entdeckt habe ist folgendes - meine Firma hat dieses Jahr einige Rechnungen nicht nur in EUR, sondern auch in USD ausgestellt. 
Alle Datensätze, die anhand des `GET`-Requests über `{{baseURL}}/v1/Invoices` übermittelt werden, enthalten in der Spalte `ExchangeRate` immer denselben Wert -> **1**, auch bei Dollar. Daher können Umsätze und viele anderen Merkmale nicht genau gerechnet werden, da die Dollar-Rechnungen so interpretiert werden, als ob sie in Euro sind. 

Wie kann ich auf den richtigen Wechselkurs zugreifen, den ihr unter _'Belege -> Rechnungen'_ verwendet? 
Und warum sind in der Datenbank die falschen Wechselkurse abgespeichert? 

Herzlichen Dank im Voraus!

Mit freundlichen Grüßen, 
Ilia Sokolovskiy

![image](https://user-images.githubusercontent.com/107248726/173040431-79898f99-c740-4285-9bef-73950f3fa866.png)

**Comment by monderino** [comment]
Hi Ilia,

bin ich richtig in der Annahme das du für Piabo arbeitest?
Wenn ja habe ich mal in eure DB geschaut und auch eine API abfrage gemacht. Hier bekomme ich keine Rechnung in der ich dieses Verhalten nachstellen kann.
Mein API-Call: https://api.hellohq.io/v1/Invoices?$filter=Currency eq 'USD'
<img width="240" alt="Screenshot 2022-06-10 at 13 15 00" src="https://user-images.githubusercontent.com/23459030/173053837-f1115b47-4944-4323-81ec-1f3900abf1a4.png">

Kannst du mir die Nummer oder Id eines Beleges nennen indem du das hast?

Ich habe keine Erfahrung mit dem Google Data Studio, aber kann es sein das hier ein Falscher Datentyp verwendet wird und daher keine Nachkommastellen vorhanden sind?

Viele Grüße
Sven

**Comment by ilia-piabo** [comment]
Hi Sven, 

ja, ganz genau, ich bin bei PIABO. :)
Du hast tatsächlich Recht, ich habe über Postman jetzt alle USD Rechnungen abgefragt und bei allen scheint richtiger Wechselkurs zu stehen! 
Sorry für jegliche Verwirrung, my bad. 

Es liegt wirklich an GDS, was ich ziemlich interessant finde.. 
Die Datentypen sind dort korrekt konfiguriert, da alle anderen Parameter mit Nachkommastellen werden hingegen korrekt dargestellt. Ich glaube es hat vielleicht etwas mit Default-Formatierung zu tun.
Ich probiere mal paar Sachen aus und melde mich nochmals, wenn ich welche weiteren Fragen habe.

Vielen Dank!

Liebe Grüße,
Ilia

**Comment by monderino** [comment]
Super, Danke für die Info

**Comment by ilia-piabo** [comment]
Hej Sven, 

ich habe alles mögliche ausprobiert und komme irgendwie leider auf keine richtige Lösung. 
Eine Frage - hat der Wechselkurs einen abweichenden Datentyp im Vergleich zu den anderen Feldern mit Dezimalwerten? 

VG, 
Ilia

**Comment by monderino** [comment]
Hey,

nein alle haben den Type decimal.

Viele Grüße
Sven

**Comment by ilia-piabo** [comment]
Hi, 

okay, dann wende ich mich direkt an Google.
Danke!

Viele Grüße,
Ilia
