### ISSUE TITLE
Power BI - automatische Aktualisierung

### ISSUE THREAD

**Issue by libako-360** [hellohq-io/hellohq.docs#37]
Ich habe mir in Power BI ein Dashboard erstellt. Das habe ich auch anschließend veröffentlicht, sodass ich auch über Web auf das Dashboard Zugriff habe.

Wenn ich nun im Web aktualisieren möchte (oder eine automatische Aktualisierung planen möchte), erhalte ich die folgende Meldung:
_Dieses Dataset umfasst eine dynamische Datenquelle. Da dynamische Datenquellen im Power BI-Dienst nicht aktualisiert werden, wird dieses Dataset nicht aktualisiert._

Mache ich etwas falsch ... oder geht das mit HQ nicht?

Vielen Dank! :-)

**Comment by engel-007** [comment]
Soweit ich die PBI Architektur verstehe, kannst du die Daten nur manuell in der Datei unter PBI Desktop aktualisieren und dann musst du wieder neu publishen. Aber ich wäre begeistert, wenn ich da falsch liegen würde, da das Thema für mich ebenfalls relevant ist.

**Comment by patrickkurras** [comment]
Hallo @libako-360,

wie engel-007 ist dies leider aktuell nicht möglich. Ich habe das Thema aber einmal als Feedback an das Produktteam weitergegeben, ich kann dir allerdings nicht versprechen das sich das in naher Zukunft ändern wird.

Viele Grüße
Patrick

**Comment by MariusLuding** [comment]
Moin,
Hatte das Problem auch gehabt und gelöst (Hier am Beispiel für Reports):
```
let 
    BaseUrl         = "https://api.hqlabs.de/",
    Token           = "<Hier Token Einfügen>",
    EntitiesPerPage = 1000,
    API_Version = "v1",
    ObjectName      = "UserReportings?",
    UrlPostfix      = "/" & API_Version & "/" & ObjectName,
 
    GetJson = (Pagination) =>
        let PaginatedUrlPostfix = UrlPostfix & Pagination,
            Options = [Headers=[ #"Authorization" = "Bearer " & Token ], RelativePath=PaginatedUrlPostfix],
            RawData = Web.Contents(BaseUrl, Options),
            Json    = Json.Document(RawData)
        in  Json,
 
    GetEntityCount = () =>
        let Pagination   = "$count=true&$top=0",
            Json  = GetJson(Pagination),
            Count = Json[#"@odata.count"]
        in  Count,
 
    GetPage = (Index) =>
        let Skip  = "$skip=" & Text.From(Index * EntitiesPerPage),
            Top   = "$top=" & Text.From(EntitiesPerPage),
            Pagination   = Skip & "&" & Top,
            Json  = GetJson(Pagination),
            Value = Json[#"value"]
        in  Value,
 
    EntityCount = List.Max({ EntitiesPerPage, GetEntityCount() }),
    PageCount   = Number.RoundUp(EntityCount / EntitiesPerPage),
    PageIndices = { 0 .. PageCount - 1 },
    Pages       = List.Transform(PageIndices, each GetPage(_)),
    Entities    = List.Union(Pages),
    Table       = Table.FromList(Entities, Splitter.SplitByNothing(), null, null, ExtraValues.Error)
in
    Table
```
Das Problem in der offiziellen Doku ist, dass sich die BaseURL nicht verändern darf, damit das mit der Online-Aktualisierung klappt. Daher die verwendung von dem Postfix.

**Comment by libako-360** [comment]
@MariusLuding 
Oh wow klasse - ich hatte damals deine Antwort gar nicht bemerkt! Vielen Dank!

Ich habe das mal so in Power BI Desktop hinzugefügt und es klappt! :-)

Ene Frage zu Power BI Web: Hier bekomme ich beim Aktualisieren die Fehlermeldung:
_"Die geplante Aktualisierung ist deaktiviert, weil für mindestens eine Datenquelle Anmeldeinformationen fehlen. Um die Aktualisierung erneut zu starten, wechseln Sie zur Einstellungsseite dieses Datasets, und geben Sie Anmeldeinformationen für alle Datenquellen ein. Aktivieren Sie dann die geplante Aktualisierung erneut."_

Laut der HQ Doku ist die Anmeldung anonym - das klappt aber hier leider nicht. Wie hast du das bei dir eingestellt?
![image](https://user-images.githubusercontent.com/97038856/217929497-3068d3a1-63a4-4788-8af2-d45675bfa33a.png)


Vielen Dank! :-)

**Comment by MariusLuding** [comment]
Moin,

Das ist leider bei mir auch immer sehr frickelig. 
Ich habe die "Testverbindung überspringen" bei mir eingeschaltet.
