### ISSUE TITLE
HQ :: Relationenmodell

### ISSUE THREAD

**Issue by ilia-piabo** [hellohq-io/hellohq.docs#38]
Hi, da bin ich wieder. 👋 😃 

Ich hoffe, es geht euch allen gut! Das vorherige Problem habe ich erfolgreich behoben und nun habe ich eine neue Frage.
Ich benötige _das relationale Datenbankmodell_ mit Primär- und Fremdschlüsseln, um besser zu verstehen, was und wo gespeichert wird.
Das würde mir eine Menge Zeit ersparen!

Wenn die Daten wegen ihrer Vertraulichkeit nicht öffentlich geteilt werden dürfen, hier ist meine geschäftliche Email-Adresse : ilia.sokolovskiy@piabo.net

Vielen Dank!

Liebe Grüße,
Ilia

**Comment by Schaukelking** [comment]
Hey Ilia! 

Tut mir leid dir mitteilen zu müssen, dass wir sowas momentan nicht haben und somit nicht bereitstellen können. Werde es nochmal intern Anstoßen, aber auf die Schnelle werden wir dir da leider nicht helfen können. 

Beste Grüße!
