### ISSUE TITLE
Feld "Vertriebsaktion" in Leads wird nicht mitgeliefert

### ISSUE THREAD

**Issue by engel-007** [hellohq-io/hellohq.docs#39]
**Describe**
Das Feld "Vertriebsaktion" in Leads wird nicht mitgeliefert über die API. kann das sein? oder liegt das Feld in einer anderen Tabelle? 

**Additional context**
Add any other context about the question here.
- Screenshots
- Curls
- etc

**Comment by Schaukelking** [comment]
Hey!

Um die Vertriebsaktionen (SalesCampaigns) abzufragen, musst du einen expand Befehl auf der Query ausführen. 
Die Abfrage muss dann so aussehen:

`
https://api.hellohq.io/v1/Leads?$expand=SalesCampaigns
`

Ich hoffe das löst dein Problem. Wenn nicht kannst du dich gerne nochmal hier melden.

Beste Grüße
