### ISSUE TITLE
How to get base load or Grundlast

### ISSUE THREAD

**Issue by chrgruber** [hellohq-io/hellohq.docs#4]
**Describe**
I need to get the base load of a user. The only value that sound similar is "base load in hours", but that is not the same value as it is in the HQ interface. 

**Additional context**
Example 1:
Grundlast in HQ: 20h
Base load in hrs: 1

Example 2: 
Grundlast in HQ: 17h
Base load in hrs: 1

**Comment by monderino** [comment]
Hi @chrgruber,

from where within the HQ you collect these information? If you use a controlling, the base load is accumulated by the pivot based on your filter settings.

From the API you get the base load of the user per day.

Best regards
Sven

**Comment by chrgruber** [comment]
Hi @monderino,

multiplying the base load with the working days did the trick.

Thank you and best regards,
Christoph
