### ISSUE TITLE
API Abfrage für neue Standardfelder IBAN und BIC

### ISSUE THREAD

**Issue by ripperdeitronde** [hellohq-io/hellohq.docs#40]
**Describe**
Ich versuche die in den neuen Standardfeldern eingetragenen Bankinformationen der IBAN und BIC für ein angelegtes Unternehmen über die API (GET) auszulesen. 
Aber diese Felder sind nicht in der API-Dokumentation unter dem Punkt Companies vorhanden, bei dem diese in HQ beim Anlegen des Unternehmens angegeben werden. Auch bei den anderen Eigenschaften unter Companies sind die beiden Felder nicht zu finden. Auch bei Abfragen an die API sind diese beiden Felder nicht bei dem Unternehmen (Companies) vorhanden.

Wie komme ich per API Abfrage an diese beiden Felder (IBAN, BIC)?

**Additional context**
Screenshots 1:
![grafik](https://user-images.githubusercontent.com/108054087/175246833-3e70834f-a8cd-4227-a951-ade57f4d43bf.png)

**Comment by monderino** [comment]
Hi @ripperdeitronde,

vielen Dank für die information. Die Felder stehen dir ab Montag im Companies Endpoint zur Verfügung.

Viele Grüße und ein schönes Wochenende.
Sven
