### ISSUE TITLE
Eigene Datenfelder abfragen

### ISSUE THREAD

**Issue by libako-360** [hellohq-io/hellohq.docs#41]
Hallo zusammen,

wir haben für die Projekte Datenfelder angelegt. Wie kann ich diese über die API auswerten?

Vielen Dank!

**Comment by libako-360** [comment]
Gibt es hierzu irgendwelche Infos? :-)

**Comment by monderino** [comment]
Hi @libako-360 ,

Entschuldige bitte die verspätete Antwort.
Du kannst die Custom Fields mittels **expand** abrufen und auch nach spezifischen filtern wenn du das benötigst.

Abrufen aller Custom Fields:
`https://api.hellohq.io/v1/Projects?$expand=CustomFields`

Filter für fas Custom Field 'Nachrichten' (Beispiel):
`https://api.hellohq.io/v1/Projects?$expand=CustomFields&$filter=CustomFields/any(cf: cf/Value eq 'Test Nachricht') and CustomFields/any(cf: cf/Name eq 'Nachrichten')`

Ich hoffe das hilft dir weiter.

Viele Grüße
Sven

**Comment by libako-360** [comment]
Hi @monderino 

Evtl. mache ich einen Fehler, aber bei mir klappt das nicht.

Unser Ziel ist es, eigene Felder über PowerBi auszuwerten. Es wird aber folgender Fehler angezeigt:

```
DataSource.Error: Fehler beim Abrufen von Inhalten von "https://api.hqlabs.de/v1/Projects?$expand=CustomFields$count=true&$top=0" (400) durch "Web.Contents": Bad Request
Details:
    DataSourceKind=Web
    DataSourcePath=https://api.hqlabs.de/v1/Projects
    Url=https://api.hqlabs.de/v1/Projects?$expand=CustomFields$count=true&$top=0
```

Was habe ich falsch gemacht?

**Comment by Schaukelking** [comment]
Hey, in Sachen PowerBi können wir leider nicht weiterhelfen, allerdings haben wir deine Abfrage überprüft und festgestellt, dass vor dem "$count=true" ein "&" fehlt.

`https://api.hqlabs.de/v1/Projects?$expand=CustomFields&$count=true&$top=0`

Die Abfrage sollte funktionieren. Allerdings wird "&$top=0" dafür sorgen, dass du keine Elemente angezeigt kriegst (weil du dir damit nur die obersten 0 Elemente anzeigen lässt). 

Hoffe das hilft dir weiter.

Beste Grüße!

**Comment by libako-360** [comment]
@Schaukelking 
Vielen Dank! Ich glaube das fehlende & war der Fehler.

Bzgl. top=0 das ist Teil der Anleitung auf den Support Seiten. Das sollte meines Wissens nicht verändert werden. So hat es auch zum Schluss funktioniert. :-)
