### ISSUE TITLE
Project template name for each project

### ISSUE THREAD

**Issue by theresa-sporn** [hellohq-io/hellohq.docs#42]
**Describe**
I am looking for a way to get the project template name for each project.

**Additional context**
Until now I could only extract the list of projects and the list of templates using the API. Is there a way to connect them? Thank you!

**Comment by patrickkurras** [comment]
Hallo @theresa-sporn,

Du kannst die ProjectTemplate zusammen mit dem Projects mittels expand abrufen. Dies würde dann so aussehen.

`https://api.hellohq.io/v1/Projects?$expand=ProjectTemplate`

Viele Grüße
Patrick

**Comment by theresa-sporn** [comment]
Vielen Dank für die super schnelle Antwort, es klappt! :)
