### ISSUE TITLE
Getting duration of time tracked on no specific project (no ProjectId)

### ISSUE THREAD

**Issue by theresa-sporn** [hellohq-io/hellohq.docs#44]
**Describe**
Getting duration of time tracked on no specific project (no ProjectId)

**Additional context**
I managed to get the duration of time tracked on projects but am looking for a way to sum up all the hours tracked by users, even if they didn't choose a specific project

**Comment by monderino** [comment]
Hi @theresa-sporn,

Can you tell me more about your use case?
Because in helloHQ every reporting is related to a project. The others are user working times, but for this entity we do not have any endpoints yet.

Best regards
Sven

**Comment by theresa-sporn** [comment]
Hi Sven, 

thank you for your help! I'll figure out how I can use this!

Best regards,
Theresa
