### ISSUE TITLE
Authentifizierung mit 2.0 API

### ISSUE THREAD

**Issue by ojboettger** [hellohq-io/hellohq.docs#46]
Guten Tag,

wir haben für für Frima Treo einen Software gebaut, die mit Ihren HQ redet. Anscheinend wurde dort noch die Version 1.9 verwendet. Jetzt wollten wir die Software anpassen. Leider wenn wir versuchen mit der neuen Base URL (https://api.hellohq.io/) den Authorization Request zu senden, bekomme wir leider nur eine Seite mit 404 nicht gefunden. Machen wir da noch etwas falsch? Anbei einmal den Authorization Request  den wir erstellen.

https://api.hellohq.io/Account/Authorize?response_type=code&client_id=601571-hq-sync&state=log&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcheck.html&scope=read_all%20write_all

Sehr Vielen Dank
Otto-J.Böttger

**Comment by shubhamwebdeveloper** [comment]
i have Run oauth URL but getting 404 page error :

**Comment by patrickkurras** [comment]
Hi @ojboettger, @shubhamwebdeveloper,

the redirect url isn't working with the new url right now, but you can just replace the the hellohq.io with hqlabs.de. Both urls will work in the future. Then it should look like this:

https://api.hqlabs.de/Account/Authorize?response_type=code&client_id=601571-hq-sync&state=log&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcheck.html&scope=read_all%20write_all

Best regards,
Patrick

**Comment by shubhamwebdeveloper** [comment]
Hi @patrickkurras  

Thank you for your suggestion. API is working now.

**Comment by ojboettger** [comment]
Hi @patrickkurras  

Yes, thank you. That works for us as well

**Comment by shubhamwebdeveloper** [comment]
Hi team,

another help for creating leads via API. so, please provide PHP supported API document or Postman Collection
