### ISSUE TITLE
Leads API run - CustomFields data not added via API

### ISSUE THREAD

**Issue by shubhamwebdeveloper** [hellohq-io/hellohq.docs#50]
Hi Team

I have run API for Leads create but "CustomFields" data not added in leads. please help me

curl --location --request POST 'https://api.hqlabs.de/v1/Leads' \
--header 'Content-Type: application/json' \
--header 'accept: application/json' \
--header 'Authorization: Bearer jr_QruC...V' \
--data-raw '{
    "Name": "DP4 P",
    "CompanyName": "",
    "Number": "",
    "CompanyId":61027,
    "StatusId": 46002,
    "ContactPersons" : [
        {
            "Id" : 56036
        }
    ],
    "CustomFields": [
    {
      "Name": "Email",
      "Value": "deepesh@gmail.com",
      "Type": "TextMultiline"
    }
  ]
}'

**Comment by monderino** [comment]
Hi @shubhamwebdeveloper,

this is a public area. Please never put secure information into your posts. I will remove the token for you.

First when you create a entity you have to add "Id" = 0 to your post model.

The Custom fields are defined in hellohq and you need to create the entity first. Then we create the customfields as well.
After the creation you can fetch the lead with the customfields to get the ids. 
=> https://api.hqlabs.de.io/v1/Leads(leadId)?$expand=CustomFields

With the ids you can use the following call to add the data to your custom fields.
<img width="1507" alt="Screenshot 2022-08-04 at 17 23 31" src="https://user-images.githubusercontent.com/23459030/182885297-06717791-fbfb-4ce6-9438-5add22288c71.png">

Best regards
Sven

**Comment by shubhamwebdeveloper** [comment]
I am try but getting error
curl --location --request POST 'https://api.hqlabs.de/v1/Leads(28)/CustomFields' \
--header 'Content-Type: application/json' \
--header 'accept: application/json' \
--header 'Authorization: Bearer jr_QruCg8Hz8RRhSQwieDG8pEXM9MuraOKnAw2-rfIMO4dZQcG2r-iZfPkLvK5QH16ne4LWOEl-8-lgomIe0_evpe26OLS3MX_T-i8yJJHU51o42JclgHmIQQX2Jvk3obq8gXzGQ5P6BqakW2KdOK3E1TIAmcVe2kXjnKm2_k0XaP-iYEY_4Ygm9QCe1hJ1L08T1H78Aupb9sI6YB1ZSUaV0ly4dcNmjUFPJoMvcfBL9Sdf4SUgltBGgqKMAFK3V' \
--data-raw '{
    "Id":0,
    "Name": "Email",
    "Value": "deepesh@gmail.com",
    "Type": "Text",
    "CreatedBy": 0,
    "UpdatedBy": 0,
    "CreatedOn": null,
    "UpdatedOn": null
}'

**Comment by monderino** [comment]
Again, please NEVER add secret information like token or a password into your post!
You allow other to access you system for a specific amount of time!

**Comment by shubhamwebdeveloper** [comment]
oky. please solve my problem how to add custom fields in /Leads post API

**Comment by monderino** [comment]
As I told you in the post before.
After create the lead you have to get them including the custom fields.
https://api.hqlabs.de/v1/Leads(28)?$expand=CustomFields
Then you have the id of the custom field and you can update it.

`curl --request PUT \
  --url 'https://api.hqlabs.de/v1/Leads(28)/CustomFields(18038)' \
  --header 'Authorization: Bearer jr_....' \
  --header 'Content-Type: application/json' \
  --data '{
"Id":18038,
"Name": "Projekt Beschreibung",
"Value": "test update"
}'`


You did a Post, but this is not possible. You can just update the custom fields and not create new ones.

**Comment by shubhamwebdeveloper** [comment]
@monderino 

Thanks. solve my problem
