### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by jon-ovan** [hellohq-io/hellohq.docs#51]
**Context**
I am currently working on a flutter app that does its login through hellohq.
And I would like to authenticate without using any browser.

**Question**
Do you provide any other authentication type rather than OAuth 2.0 Authorization Code?

**Comment by Schaukelking** [comment]
Hey jon-ovan!

You could also just use a bearer token. You can find the token you need in the helloHQ under Admin > Api Clients.

Best regards,
Padsen

**Comment by jon-ovan** [comment]
My users do not have access to their bearer token, so they need to authenticate with Oauth2.0 to obtain it.
On your documentation you use Oauth2.0 Authorization Code, but that requires the use of a web browser.
I need Oauth2.0 Password Credentials to authenticate with username and password.

Otherwise I can not log my user with username and password from my app.

**Comment by jon-ovan** [comment]
Hi again, could you please provide any feedback on my previous comment?  

Thanks in advance.
Jon

**Comment by Schaukelking** [comment]
Hey, sorry for the late response. 

Sadly I don't see a way to verify your user without logging in on our login page. I will keep this issue open and talk about this with our api responding person next week (currently on vacation). I don't think we can deliver a quick solution. Sorry for that!

Kind regards
Padsen

**Comment by jon-ovan** [comment]
Hello, 
I am using hellohq to do the authentication, even if the token was the same for the whole company there is still no way for me to validate the user credentials with the api. It needs to be done through the Auth2.0 I understand. Please provide me some feedback once your api developer is back from vacation. 

Thanks.

Jon

**Comment by jon-ovan** [comment]
Hello, is there any feedback for me regarding this issue?

Jon.

**Comment by Schaukelking** [comment]
Hey Jon, 

I had a talk with our api developer and he mentioned that it is not possible to finalize an OAuth flow without user verification via browser. There is no other way to verify users. Sorry about that

Padsen
