### ISSUE TITLE
User Telephone numbers not accessible

### ISSUE THREAD

**Issue by MariusLuding** [hellohq-io/hellohq.docs#52]
**Describe**
Not-A-Bug: When accessing the /Users attributes, there is no mention of the telephone numbers. Is there a deliberate reasoning behind this, or has just no one ever needed this?

**Additional context**
This is mostly due to me wanting to sync some of our user-data from HQ to O365 so we don't have to manually do it.
The field "department" would also be nice :)

**Comment by Schaukelking** [comment]
Hello Marius,
we evaluated your request and will add "Department" and the work phone numbers to the Api model. Or do you need the private numbers, too? 

Best Regards,
Padsen

**Comment by MariusLuding** [comment]
Hey padsen,
private (mobile) number would be great as well. (Just to be sure, for work phone, I also meant the work mobile number)
Do you have an eta when this is going to be worked on?
Greetings,
Marius

**Comment by Schaukelking** [comment]
Hey, sorry for the late response.
Due to current low capacity it takes some time. We try to update our API this week, so you can access the phonenumbers. I'll keep you up to date

**Comment by Schaukelking** [comment]
Hey @MariusLuding,

you should be able to access all phonenumbers by now via api call!

Have a great day (:
