### ISSUE TITLE
API for user Assignments don't return assignments from resource groups

### ISSUE THREAD

**Issue by rfranz22** [hellohq-io/hellohq.docs#53]
If I use the following endpoint  "https://api.hellohq.io/v1/Users(ID)/Assignments" I only get the assignments directly assigned to the user. I am missing the assignments, which are assigned to the resource group of the user.

**Comment by Schaukelking** [comment]
Hey rfranz2,

currently it is not possible to get the assignments depending on the resource group. We will schedule this request in our development process and add a way to get this done. But this might take some days. 

Best regards,
Padsen

**Comment by rfranz22** [comment]
When can I expact this to be done? I need to know If I can wait or find a work around on my own!

**Comment by Schaukelking** [comment]
Hey, sorry for the late response!

I think it makes sense that you try to find a work around by your own. I guess we will not be able to deliver a satisfactory solution for this very soon since we are currently working on other, bigger topics. Sorry for that! 

Best Regards,
Padsen
