### ISSUE TITLE
Project Change Status Error

### ISSUE THREAD

**Issue by rt012** [hellohq-io/hellohq.docs#54]
I try to change the status of an Project but I always get following error 

Error message: Invalid parameter: No 'Project' found

My request looks like this: 

url https://api.hqlabs.de/v1/Projects(100434)/do.ChangeStatus
body: {
                     ProjectStatusId: 20
                 }

status entry:
{
    Name: 'Fertig umgesetzt',
    IsInProgress: true,
    Id: 20,
    CreatedBy: 11016,
    UpdatedBy: 11016,
    CreatedOn: '2020-12-20T16:28:26.15Z',
    UpdatedOn: '2020-12-20T16:28:37.7866667Z'
  }

the project is 100% available. I can open it in hq and get details from the api. 

Do I miss something?

**Comment by Schaukelking** [comment]
Hey @rt012,
what is your .helloHQ hostname? So I can have a look if all your settings are set correctly. This message appears when it either cannot find the project by it's id or the according template which is linked to the project. To be sure the id of the project is correct, you can just go to the project overview in the helloHQ and in the url you'll find a "&projektid=" param.


Kind regards,
Padsen

**Comment by Schaukelking** [comment]
Hey, i just found an issue in the api code. 
Your query looks right and should work tomorrow.

Sorry for that (:

**Comment by Schaukelking** [comment]
Hey @rt012,

the set status action should work by now.

Have a great day!
