### ISSUE TITLE
"HTTP Error 500" bei einem Expand /v1/Users -> Assignments

### ISSUE THREAD

**Issue by ilia-piabo** [hellohq-io/hellohq.docs#56]
Hallo Leute, ich hoffe, es geht euch gut!😊 

Ich stehe vor einem Problem beim Testen einer der REST API Request Expands für das Verzeichnis /v1/Users, nämlich - Assignments.

Zuerst habe ich es mit anderen Expands kombiniert, was zu demselben Fehler führte.  Wenn ich alle anderen Parameter weglasse, außer "count", gibt Postman immer noch denselben Internal Server Error Code (500) zurück.

Habt ihr eine Idee, warum es derzeit nicht funktioniert? 
Alle anderen Erweiterungen funktionieren einwandfrei.

Ich freue mich auf eure Antwort nächste Woche!
Schönes Wochenende!

---
Request -> **GET** https://api.hqlabs.de/v1/Users?$expand=Assignments&$count=true
Response -> _500 Internal Server Error_

![Bildschirmfoto 2022-09-16 um 18 51 44](https://user-images.githubusercontent.com/107248726/190697021-cd39a32f-7b89-4486-b171-f155e2de4cce.jpg)

**Comment by Schaukelking** [comment]
Hey Ilia, hoffe du hattest ein schönes Wochenende! 

Leider muss ich dir mitteilen, dass die Assignments nicht via expand abrufbar sind. Das liegt an der Datenbankstruktur, die Daten können wir momentan nur via sub-route holen. Der einzige Weg userspezifische Assignments zu kriegen ist via UserId -> ` v1/Users(UserId)/Assignments` endpoint.

Guten Start in die Woche dir!
Padsen
