### ISSUE TITLE
Tracking total hours

### ISSUE THREAD

**Issue by MarySas** [hellohq-io/hellohq.docs#57]
Hello,

I would like to track the total time users are working. When I am pulling from the code .../UserWorkingHours I have two problems:
1) It doesn't show the total hours they add to the tracking time. Seems that it only shows hours applied to a certain project.
2) when I compare the numbers to the report in HQ, the numbers are not the same.

Thank you,

Mary

**Comment by patrickkurras** [comment]
Hi Mary, 

the UserWorkingHours are the target working hours and not the tracked time. Unfortunately, we don't have the tracked working hours in the API at the moment either, only reportings.

This will not change, at least not in the near future.

Kind regards,
Patrick

**Comment by MarySas** [comment]
Hi Patrick,

Thank you for answering.
I still have some doubts about question n.2
2. when I compare the numbers from the automatic report generated via API to the report extracted directly in HQ, the numbers are not the same. 32% of the table (hours related to projects) is not matching.

Could you please help me with this issue?

Kind regards,

Mary

**Comment by monderino** [comment]
Hi @MarySas ,

this is really hard to tell!
My guess, in hellohq you have a particular time frame set and in the api you fetch all data.

But without further information it is really hard to say.
Can you provide:
- your api calls
- the hellohq url you open
 If available the user name and if you use a stored view  as well

Thank you.

Best regards
Sven

**Comment by monderino** [comment]
Hi @MarySas,

Thank you, but you do not deliver the information about the second part...
Which hellohq module you use to compare the data with the api repsonse?

I need the url and the user with which the module is called up.

Thank you.

Best regards
Sven

**Comment by MarySas** [comment]
Hello,

Do you have a more private channel so we don't expose the data on a shared
GitHub page?

Best Regards,

Mary

Em seg., 26 de set. de 2022 às 17:09, Svenson ***@***.***>
escreveu:

**Comment by monderino** [comment]
Hi,

sure, you can create a bug ticket in hellohq with all information or you write a mail to support@hellohq.io. Then the support team will path the information further.

Best regards 
Sven

**Comment by monderino** [comment]
Hi,

I got all information now.

I think the issue is that you do not implement a pagination in your code. This means you only fetch the first 1000 entries every time. But there are more! In the response you get a value which is called nextLink, if there are more entries to fetch.

Also I would recommend to filter the result directly... then you do not need to fetch data of the past you probably not need.
For example (Reportings of Januar):
https://api.hellohq.io/v1/Users(xxxxx)/Reportings?$filter=StartOn ge 2022-01-01 and StartOn lt 2022-02-01

Best regards.

**Comment by XLAY2022** [comment]
Hello,

We are trying to consume in our system the new API that you created for the Credit Note.
And we have some questions.
The situation AS IS:
- Invoice endpoint: we are receiving Invoices with the Type: "Invoice" and Invoice Cancellation with the Type "Cancellation" and Credit Note Cancellation with Type "Cancellation".

- Credit Note endpoint: we are receiving the Credit Note with Type "CreditNote".

Is it possible to receive the Credit Note Cancellation from the Credit Note endpoint at least we can differentiate between Invoice Cancellation and Credit Note Cancellation?
If not, you can keep the Credit Note Cancellation coming from the Invoice endpoint but with a different "Type" for example <CreditNoteCancellation>?


Is there another channel of communication we can use to discuss this issue?
If so please let me know.

Thank you

Best regards

Xhulia

**Comment by monderino** [comment]
Hi,

Sorry but it is not possible to change the behaviour. Is it not possible to identify the canceled credit not with the number of the document?

Best Regards
Sven

**Comment by XLAY2022** [comment]
Hello,

Yes, that would be an option, but we do not have a field in the Cancellation document where there is available information regarding the original document (Invoice or Credit Note) for which this Cancellation was created. 

<img width="864" alt="image (3)" src="https://user-images.githubusercontent.com/116287751/197511455-d8683fa6-0c62-49e5-ab39-8c53d6765aee.png">


If you can provide such field in the API we can use this to link the two documents.
Do you think this can be done?

Thank you,

Xhulia

**Comment by monderino** [comment]
Let me check... I will try to find a solution

**Comment by monderino** [comment]
So, 

my idea:
When you add a specific expand to the get call, for example: /CreditNotes?$expand=CancellationInformation
The result will have a new property with this data:
```
"CancellationInformation": [
{
	"Id": 914,
	"Number": "ST-22-0000"
}
]

```

Will this help you?

The problem will be, that this can slowdown the call a lot. related to the number of data you fetch!

**Comment by monderino** [comment]
Hey @XLAY2022,

Any updates on that?

**Comment by XLAY2022** [comment]
Hi,
We tried with the solution you suggested but we get the following error:
![image (4)](https://user-images.githubusercontent.com/116287751/199442450-47874103-c638-4e17-9a67-5680d330b329.png)

Can you suggest how we can bypass this?

Thank you,

Xhulia

**Comment by XLAY2022** [comment]
Hey,
We thought this was already created. 
Yes, this can help us. Let us know when we can test it.

Thank you.

Xhulia

**Comment by monderino** [comment]
Ok. I tell you when the change is online.

**Comment by monderino** [comment]
Hi @XLAY2022,

it's done. The change is online.

Best regards
Sven

**Comment by monderino** [comment]
Hi Xhulia,

This is currently not possible. The only thing I can do is to create a new Endpoint to get all the cancellations and the related data of the invoice or credit note!

But this needs to go into the planning first and will take some time.

It is possible to talk to your customer success manager and explain him your issues... Maybe he has other ideas to solve the issue.


Best regards
Sven
