### ISSUE TITLE
Post Request for IncomingInvoices

### ISSUE THREAD

**Issue by septemberAndreas** [hellohq-io/hellohq.docs#58]
Hallo zusammen, 

Wir managen unsere Eingangsrechnungen von Dienstleistern und Lieferanten noch außerhalb von HQ. Für das Projektreporting sollen diese aber per API aber auf die Projekte eingebucht werden. Leider ist es mir noch nicht gelungen, eine vernünftige Buchung per POST-request hochzuladen. Beim Absetzen des Requests bekomme ich immer folgende 400er Fehlermeldung: 

```
{
  "error": {
    "code": "",
    "message": "The request is invalid.",
    "innererror": {
      "message": "invoice : Requested value 'string' was not found.\r\n",
      "type": "",
      "stacktrace": ""
    }
  }
}
```

Irgendwie fehlt mir noch irgendeine Info beim Upload, aber ich weiss nicht genau welche das ist?
Anbei der Body meiner Dummyrechnung, die ich gerne hochladen möchte. Danke für Eure Hilfe

```
{
  "InvoiceDate": "2022-10-23",
  "DueDate": "2022-11-01",
  "BookingDate": "2022-10-23",
  "Status": "CompletelyPaid",
  "Positions": [
      {
        "IsFactorizable": false,
        "IsOptional": null,
        "Tax": 19,
        "Price": 800,
        "Discount": 0,
        "Margin": 0,
        "ExcludeFromEarlyPayment": true,
        "TotalPrice": 800,
        "TotalUnitPrice": 800,
        "TotalVat": 152,
        "Text": "Text",
        "Unit": "string",
        "Type": "string",
        "Order": 0,
        "ArticleId": null,
        "ProjectId": 734,
        "Article": null,
        "Amount": 952,
        "ProjectBudgetId": null,
        "CostTypeId": 56017,
        "BookingAccount": null,
        "CostCenter1": null,
        "CostCenter2": null,
        "DocumentId": null,
        "Id": 10,
        "CreatedBy": 11070,
        "UpdatedBy": 11070,
        "CreatedOn": "2022-10-23",
        "UpdatedOn": "2022-10-23"
      }
  ],
  "IsPaid": true,
  "PaymentDate": "2022-10-23",
  "Currency": "EUR",
  "ExchangeRate": 1.00000,
  "DeliveryDate": null,
  "PaymentConditionId": null,
  "DeliveryConditionId": null,
  "DiscountType": null,
  "Discount": null,
  "Margin": null,
  "TaxOption": "VatApplicable",
  "ServiceOption": "Service",
  "NetTotal": 0.00000,
  "GrossTotal": 0.00000,
  "VatTotal": 0.00000,
  "PaidTotal": 0.00000,
  "Type": "IncomingInvoice",
  "TypeText": "IncomingInvoice",
  "AddressText": "Irgendwo Adresse",
  "CompanyAddressId": null,
  "Subject": "Dummy Rechnung von Andreas",
  "CalculatedSubject": "Dummy Rechnung asdfl",
  "Header": null,
  "Footer": null,
  "DocumentTemplateId": 4012,
  "Number": "XXYYZZ 86609",
  "ContactPersonId": null,
  "CompanyId": 61024,
  "InternalContactPersonId": 11070,
  "LeadId": null,
  "SyncId": null,
  "ProjectId": 734,
  "Note": null,
  "CompanyPurchaseOrderNumber": null,
  "Language": "DE",
  "Id": 0,
  "CreatedBy": 11070,
  "UpdatedBy": 11070
}
```

**Comment by monderino** [comment]
Hi @septemberAndreas ,

benutzt du die Post Methode auf den Endpoint v1/IncomingInvoices?
Kannst du mir sagen für welchen Kunden diese Abfrage ist, damit ich die Id's überprüfen kann?

Danke und viele Grüße
Sven

**Comment by septemberAndreas** [comment]
Hi Sven,  danke für die schnelle Reaktion. Wir sind september Strategie & Forschung aus Köln.
Meinst Du das mit Kunde?

**Comment by monderino** [comment]
hey,

ja das reicht mir, Danke ;)
Ich prüfe das und melde mich so schnell wie möglich zurück.

**Comment by monderino** [comment]
Das Problem liegt bei den folgenden Feldern in der Position:
"Unit": "string",
"Type": "string",

Diese müssten wie folgt aussehen:
"Unit": "Stück",
"Type": "Freetext",


Viele Grüße
Sven

**Comment by septemberAndreas** [comment]
Hi Sven, 

danke für Deine schnelle Hilfestellung, damit krieg ich die Buchung jetzt rein, allerdings sind mir noch einige Dinge nicht klar u. i.d. API-Doku habe ich das jetzt nicht direkt gefunden. Folgende Fragen hätte ich noch:

POST-REQUEST https://api.hellohq.io/v1/IncomingInvoices
> Wo kann ich die Belegnummer (die ReNr. des Lieferanten) mitgeben? (POST) ... momentan steht da immer (Entwurf)
> Wo kann ich die Lieferanten-ID (z.B. HQLabs GmbH = 61033) mitgeben? (POST)
> Im Frontend erscheint die so gebuchte Rechnung mit "Vollst. bezahlt", aber mit blauem Kreis-Icon anstatt grünem Haken?

GET https://api.hellohq.io/v1/IncomingInvoices
> Wenn ich mir die Rechnungen mit GET aus dem System hole bekomme ich keine Positionen mit (auch nicht mit expand?!)
> Im Frontend gelöschte Rechnungen kommen immer noch beim GET Request mit?

**Comment by monderino** [comment]
Hey, 

Wo kann ich die Belegnummer (die ReNr. des Lieferanten) mitgeben? (POST) ... momentan steht da immer (Entwurf)
=> Die Nummer wird aus dem Feld number übernommen. Aber nur wenn der Status der Eingangsrechnung Draft ist. Dein Status ist aber aktuell Vollst. Bezahlt. Daher wird die Nummer nicht übernommen. Dies ist auch nicht richtig, da der Status für diesen Belegtyp nicht existiert. (Siehe übernächste Antwort)

Wo kann ich die Lieferanten-ID (z.B. HQLabs GmbH = 61033) mitgeben? (POST)
=> Das ist die CompanyId

Im Frontend erscheint die so gebuchte Rechnung mit "Vollst. bezahlt", aber mit blauem Kreis-Icon anstatt grünem Haken?
=> "Status": "CompletelyPaid" Diesen Status gibt es für Eingangsrechnungen nicht. Erlaubt sind Draft, Approved, WaitingForApproval. Werde dafür intern ein Ticket aufmachen

Wenn ich mir die Rechnungen mit GET aus dem System hole bekomme ich keine Positionen mit (auch nicht mit expand?!)
=> https://api.hellohq.io/v1/IncomingInvoices(XXX)?$expand=Positions liefert mir die Position mit.

Im Frontend gelöschte Rechnungen kommen immer noch beim GET Request mit?
=> Hier müsstest du mir ein Beispiel geben, Id des Belegs zum Beispiel.

**Comment by monderino** [comment]
Hey Andreas,

sehr gerne. 
Ja Leider ist die Dokumentation nicht so gut wie wir es gerne hätten. Wir arbeiten gerade an einem größeren Update, da wird sich auch die im laufe des nächsten Jahres ein API Update ergeben. Hier wird es dann eine bessere Dokumentation geben.

Das du diese Eingangsrechnung abrufen kannst ist ebenfalls ein Bug. Habe dafür ein Ticket erstellt.

Zu deinem Wunsch mit dem Status: Hier können wir dir aktuell leider nicht weiterhelfen. 

ich schreibe dir hier wenn die Bugs behoben sind.

Viele Grüße
Sven

**Comment by septemberAndreas** [comment]
Danke Sven!

**Comment by monderino** [comment]
Moin,

die fixes gehen Morgen online.

Viele Grüße

**Comment by monderino** [comment]
Hallo again,

Heute nacht kam es zu einem Fehler in unserem Deployment. Daher gehen die Fixes erst Morgen online.

Entschuldige bitte die Verzögerung.
Viele Grüße.

**Comment by septemberAndreas** [comment]
Servus Sven, ist das Deployment für das Bugfixing jetzt über die Bühne gegangen?
Danke für ne kurze Rückmeldung! Thx -a


Herzliche Grüße
Andreas


PS. ACHTUNG NEUE MOBILNUMMER: +49 175 495 9703


Andreas Barth 
Digital Transformation Architect

» september Strategie & Forschung GmbH
» Schanzenstraße 36, 51063 Köln
» Mobile +49 (0) 175 495 9703 
» www.september-online.com 
» Geschäftsführer C. Schenkel, M. Küppers, O. Spitzer
 » Amtsgericht Köln, HRB 65112
» Datenschutz-Informationen finden Sie auf unserer Website

The information contained in this message may be privileged, confidential, and protected from disclosure. If the reader of this message is not the intended recipient, or an employee or agent responsible for delivering this message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. Thanks!

Am 26.10.2022 um 11:35 schrieb Svenson ***@***.***>:



Hallo again,

Heute nacht kam es zu einem Fehler in unserem Deployment. Daher gehen die Fixes erst Morgen online.

Entschuldige bitte die Verzögerung.
Viele Grüße.

**Comment by Schaukelking** [comment]
Hey Andreas,

ich habe grade eben nachgefragt, der Fix ist online. Du kannst es gerne ausprobieren und falls noch etwas nicht klappen sollte uns Rückmeldung geben.

Beste Grüße
Patrick

**Comment by septemberAndreas** [comment]
Hallo Patrick, 
es sieht so aus, als ob das Löschen von Einangsrechnungen (ER), zwar im HQ-Front-End funktioniert (Ansicht EINGANGSRECHNUNGEN zeigt keine Einträge), allerdings bekomme ich nach wie vor 9 ER zurückgeliefert, wenn ich einen GET-Request mit https://api.hellohq.io/v1/IncomingInvoices absetze. 
Der Request liefert mir Daten für folgende ER: ID 51, 57 bis 63 und 69
Ich hatte eigentlich erwartet, dass im aktuellen Status keine ER mehr zurückkommen (Zumindest sollte das doch der Bug sein, der gefixt worden war, ...oder?)
