### ISSUE TITLE
Getting information about projekt team and company number

### ISSUE THREAD

**Issue by IsabellaMStock** [hellohq-io/hellohq.docs#59]
**Describe**
1. How do I get the Project Leader/the project leaders via API
2. How do I get the company Number (not the internal ID) via API?
**Additional context**
1. We want to receive an overview about the project, Therefore, it is necessary to get the name of the responsible persons in a project.
2. We work more with the number of a company than with the name (as it changes from time to time), but we did not see how we could get this information via API.
![grafik](https://user-images.githubusercontent.com/25083873/199274196-280f663b-b529-4769-b96c-f49a439633ca.png)

**Comment by Schaukelking** [comment]
Hey Isabella! 

1. I guess you are looking for the project member with the project role "Projektleiter/in". You can get this by getting the project members and filtering by projectrole id, e.g. "Projektleiter/in" is ProjectRoleId 1
The filter is optional, without the ?$filter block you get all members
`https://api.hqlabs.de//v1/Projects({ProjectId})/Members?$filter=ProjectRoleId eq 1`

2. You can access this number by expanding the company types
`https://api.hqlabs.de//v1/Companies({CompanyId})?$expand=CompanyTypes
`
You can find more information about company type filtering in the **Filter by CompanyType** section on the [main page of our documentation](https://developer.hellohq.io/)

This is hopefully what you are looking for! 
Best regards
Patrick
