### ISSUE TITLE
API token route returns 404

### ISSUE THREAD

**Issue by chrgruber** [hellohq-io/hellohq.docs#6]
**Describe the bug**
Token request route returns a 404, since Aug. 30 2021. In our case this happens when requesting an access token through a refresh token.

**To Reproduce**
1. curl https://api.hqlabs.de/Token
2. 404

**Expected behavior**
A refresh token request response

**Comment by monderino** [comment]
Hi @chrgruber,

it should work again.

Best regards Sven
