### ISSUE TITLE
How to access positions of Documents - Planned Revenues

### ISSUE THREAD

**Issue by lukeoiler** [hellohq-io/hellohq.docs#60]
Hi guys,

we're trying to gather relevant data for our business case directly from the REST API. 
It's about the **Documents - Planned Revenues** interface. Below the Planned Revenues we have individual positions related to the revenues that we would need to extract.
But the GET-Request to  "/PlannedRevenues({Id})" does not reveal any information on the underlying Positions. Yet "/PlannedRevenues({Id})/Positions" does not exist as a GET-Request, only GET "/PlannedRevenues({Id})/Positions({Id})", but for that we would need to know the ID of the related Position, which we have no way of accessing. 

And thus we get to the question, how do I get to this connection? How do I access the Positions of the PlannedRevenues?

Hope this was clear, otherwise feel free to ask.

Best,
Lukas

**Comment by monderino** [comment]
Hi @lukeoiler,

to get further details on entities you need to use and expand. This will look like this: PlannedRevenues?$expand=Positions.
You can find this in our documentation as well.

Thank you and have a great day.
Best regards 
Sven
