### ISSUE TITLE
Integration of HelloHQ API as a Connector for Microsoft Services

### ISSUE THREAD

**Issue by OrtiMussPrime** [hellohq-io/hellohq.docs#61]
Hi dear HelloHQ team,

I want to create a connector based on the Swagger documentation that you have provided in your guides.
My goal is to create a connector for Microsoft Services so that I can use the connector in automated flows, for example in Power Automate or Power Apps.

Currently, I am trying to get an request running. I have the Bearer Token and validated that I can run queries on the API via Postman.
The header needs the Accept: application/json and the Authorization: Bearer [Token] properties to be able to accept the request.
When I follow this step and do a request via postman everything seems to be working.

After calling the API via a connector with the same properties, I receive an 500 Error Code. The message payload does not provide any real information about why it isn't accepting the call. Your Swagger documentation does not provide any additional information as well.
By the way, I had this Issue with PowerApps, Power Automate and Microsoft Connectors.
Any ideas on what might be causing this?
Is it possible that it is some kind of cross-origin issue, or the calls made by Microsoft application being not whitelisted?
Or is it caused by some redirect_uri property that is missing?

Are there any plans for the future to integrate a Microsoft Connector?

**Additional context**
- Screenshot: https://powerusers.microsoft.com/t5/image/serverpage/image-id/534470iD30030CD51D35340/is-moderation-mode/true/image-dimensions/2500?v=v2&px=-1
- Screenshot: https://powerusers.microsoft.com/t5/image/serverpage/image-id/534525iC117D8384D447175/is-moderation-mode/true/image-dimensions/2500?v=v2&px=-1
- Post on MS Automate:
https://powerusers.microsoft.com/t5/Power-Automate-Desktop/Using-Bearer-Token-with-HTTP-Request/m-p/1813937#M19011

**Comment by monderino** [comment]
Hi @OrtiMussPrime,

sorry for the delay. I don't think it is a cross-origin issue. Other tools like Zapier can work with our API as well.
The message 'The message payload does not provide any real information about why it isn't accepting the call.' is not from our API, maybe the response is empty? Has MS Automate some kind of debug mode? So that we can see the raw data?

Best regards
Sven

**Comment by monderino** [comment]
I tested it shortly and got data

<img width="666" alt="Screenshot 2022-11-09 at 09 17 46" src="https://user-images.githubusercontent.com/23459030/200776014-19b8d349-b974-4e02-b4f9-9cad0254e8f1.png">

**Comment by OrtiMussPrime** [comment]
Hi @monderino, I did not try the HTTP Request in the flow but rather tried to create a custom connector.
When I try to do a request I receive the following issue:

![Screenshot 2022-11-09 114130](https://user-images.githubusercontent.com/20162797/200809626-19e5412c-5e7a-43d6-91e5-edc8e44b4998.png)
![Screenshot 2022-11-09 114204](https://user-images.githubusercontent.com/20162797/200809667-19b1f58d-2bac-4ced-9716-2d3531905a55.png)
![Screenshot 2022-11-09 114217](https://user-images.githubusercontent.com/20162797/200809722-62309dec-43fd-4820-a903-09d58b01ecbf.png)

**Comment by OrtiMussPrime** [comment]
As I previously mentioned the header and the bearer token works just fine in Postman, however when I try to use it in the connector this is what I receive

**Comment by OrtiMussPrime** [comment]
> The message 'The message payload does not provide any real information about why it isn't accepting the call.' is not from our API, maybe the response is empty?

The error message is in the schema check at the bottom at the pictures.
It states that there is a type conflict at property "". Expected: Array, Got: String

May it be because MS Connectors use OpenAPI definitions instead of OData?

**Comment by monderino** [comment]
Maybe this is the case.
Sorry I guess I cannot help you further.

**Comment by OrtiMussPrime** [comment]
Sad to hear that, but that's unfortunate I guess.
Is there anything planned towards having a connector for MS Services?

**Comment by monderino** [comment]
Sorry, not yet.

But is it necessary to use the connector?

**Comment by OrtiMussPrime** [comment]
The advantages of a connector outweight the manual requests.
I wanted to have a connector, where you can basically summarize all requests in one place, set triggers to start logical request flows and more, instead of configuring the request each time anew.

Additionally Custom Connectors don't need a premium subscription, while HTTP requests does.

**Comment by OrtiMussPrime** [comment]
Somehow I was able to get the "GET" queries up and running by creating a new connector. The "POST" queries are resulting in a 404.

**Comment by monderino** [comment]
Hi,
this sounds really good.

We do not have a post for ProjectStatuses.

**Comment by OrtiMussPrime** [comment]
Thanks for the hint. I got it up and running, but I got to say that the responses that I receive from the API if there is something wrong is not really helpful or explanatory. Just as a Feedback. Plus I created another question ticket regarding the expanding and filter functionality of the API

**Comment by OrtiMussPrime** [comment]
My solution to get it running was just to create a new connection under the data tab in the sidebar and create a new connector. This somehow solved the issue with the 500 results.
