### ISSUE TITLE
GET all users abscences

### ISSUE THREAD

**Issue by Brunoogts** [hellohq-io/hellohq.docs#63]
Hello i am having trouble getting ALL users Absences.
I know in the Excel version you can get a table with all absences independent of user.
but in powerBI the only code suggested is dependent of the user E.g:

BaseUrl = "https://api.hqlabs.de/v1/Users(1)/Absences?"

i wanted ALL Absences independent of user. is that possible?

Thanks

**Comment by Schaukelking** [comment]
Hello!

Sorry, but we don't have a an endpoint currently to get all absences. The closest thing you could do is getting all users with their absences in one call:

`https://api.hellohq.io/v1/Users?$expand=Absences `

You won't have a list of all absences direclty, but a list of all users including their absences. I don't know what you do but if you have an application you can select the Absences and put them into a list. 

Hope this helps out.
Best regards,
Patrick

**Comment by Brunoogts** [comment]
Hello, Patrick! thank you for your reply!

this one somehow did not work here, this is the error code:
![image](https://user-images.githubusercontent.com/93668743/201802953-09a87270-2562-4ce1-a056-da198eb7819a.png)

i tried both:
https://api.hellohq.io
and
https://api.hqlabs.de

im using PowerBI

**Comment by Schaukelking** [comment]
Hey!

I don't have experience with PowerBi but your query is missing an '&' after Absences (: 

This should work:
`https://api.hellohq.io/v1/Users?$expand=Absences&$count=true&$top=0`

**Comment by Brunoogts** [comment]
That Worked pefectly, thank you so much!
