### ISSUE TITLE
TaskTypeStatusId

### ISSUE THREAD

**Issue by libako-360** [hellohq-io/hellohq.docs#64]
Hallo zusammen,

wie kann ich in der Tabelle "Tasks" die Spalte "TaskTypeStatusId" aufschlüsseln? 

Die Tabelle "TaskTypes" ist für die Spalte "TaskTypeId". Aber so wie ich es sehe, gibt es keine Tabelel für die Spalte "TaskTypeStatusId".

Viele Grüße

**Comment by Schaukelking** [comment]
Hey!

Genau, wir haben keinen Endpoint für den TaskTypeStatus. Wenn du den TaskTypeStatus zu einem speziellen Task willst, kannst du einfach ein expand auf der Property ausführen.

`http://api.hellohq.io/v1/ProjectTasks?$expand=TaskTypeStatus`

Der TaskTypeStatus macht generell nur Sinn im Kontext zum Task selber oder zum TaskType. 

Du kannst dir auch alle möglichen Status für einen speziellen TaskType ausgeben lassen per expand:

`http://api.hellohq.io/v1/TaskTypes?$expand=TaskTypeStatus`

Ein Task kann nur einen TaskTypeStatus annehmen, wenn der TaskTypeStatus dem TaskType des Tasks zugehörig ist. 

Hoffe das war verständlich formuliert 😆 

Beste Grüße

**Comment by libako-360** [comment]
Hey,

vielen Dank! Ich meine ich habe dich richtig verstanden, aber evtl. nicht richtig umgesetzt.

Die von dir verwendete URL sieht irgendwie anders aus. Normalerweise verwende ich "https://api.hqlabs.de", du schriebst "http://api.hellohq.io". Egal ob an deine oder an meine URL den expand hinzufüge, bekomme ich einen error:
![image](https://user-images.githubusercontent.com/97038856/206830673-266f279e-7ccd-4f8a-a882-9b0e37595976.png)

Das heißt, ich schaffe es nicht einen expand auszuführen. Ich sehe auch gerade, dass ich es im Eingangspost nicht erwähnt hatte: Ich baue mit Power BI die entsprechenden Reports.

Vielen Dank!

**Comment by monderino** [comment]
Hey @libako-360,

Es liegt nicht an hqlabs.de oder hellohq.io. Deine Parameter sind falsch. Es sollte so aussehen:
https://api.hellohq.io/v1/TaskTypes?$expand=TaskTypeStatus&$count=true

&$top=0 solltest du nicht verwenden, denn das besagt das du die ersten 0 Ergebnisse bekommst. Also dein Ergebnis leer ist.
 
Viele Grüße
Sven
