### ISSUE TITLE
Authorization failure

### ISSUE THREAD

**Issue by David4kraftwerk** [hellohq-io/hellohq.docs#66]
Liebes HQ-Development-Team,

wir brauchen in unserem Unternehmen, einen eigenen Service, bei dem wir auch eure API verwenden.
Um diese zu testen verwende ich Postman. Nachdem ich alle, für die Autorisierung, notwendigen Variablen erstellt habe, wird die URL aufgerufen, die mich eigentlich zur Eingabe meiner Userdaten auffordern sollte. Allerdings gibts dann in der Sekunde einen redirect auf 404. Ohne diesen Auth-Code aus der response kann ich folglich auch kein Access-Token generieren und würde euch bitten mich hier zu unterstützen. 

Danke schon mal!

LG,
David

Edit:
Wenn ich es nur mit Bearer Token versuche, bekomme ich auch 404, allerdings ändert sich dieses auch jedes mal wenn ich im HQ unter Admin > Api Client meine Seite neu lade.

Edit 2:
Wenn ich die alte Base-Url versuche, verweigert er meine Credentials. Kann das daran liegen, dass wir AD angebunden haben?

URL: 
https://api.hellohq.io/Account/Authorize?response_type=code&client_id=615122-repoExpo&scope=read_all write_all&redirect_uri=https://oauth.pstmn.io/v1/browser-callback

Erst wird diese Seite aufgerufen:
![image](https://user-images.githubusercontent.com/119495092/204774966-2a0bf1cc-f71c-45b8-995f-c55787d7bf1b.png)

Danach gleich 404:
![image](https://user-images.githubusercontent.com/119495092/204775179-e2d3632a-1c94-4133-8b19-c5d85921577c.png)

**Comment by patrickkurras** [comment]
Hi @David4kraftwerk,

wir aktuell lauf die Authorization nur mit der alten URL, wir planen diese auch mit der neuen Endung zur Verfügung zu stellen, allerdings ist das bis jetzt noch nicht der Fall. Du kannst einfach in der URL das "hellohq.io" durch "hqlabs.de" ersetzten und dann solltest du zur richtigen Eingabemaske kommen.

Diese würde dann so aussehen:
https://api.hqlabs.de/Account/Authorize?response_type=code&client_id=615122-repoExpo&scope=read_all write_all&redirect_uri=https://oauth.pstmn.io/v1/browser-callback


Viele Grüße
Patrick

**Comment by David4kraftwerk** [comment]
Hi @patrickkurras,

alles klar danke! Hab ich grade auch in den geschlossenen issues gefunden, allerdings habe ich hier noch immer das Problem, dass mein User nicht erkannt wird. Hängt das vielleicht wie bei der App mit dem ActiveDirectory zusammen?

LG,
David

**Comment by patrickkurras** [comment]
@David4kraftwerk,

habe gehört das du auch mit unseren Support schon Kontakt hattest. Konntest du das Problem mit dem Bearer Token lösen?

Viele Grüße
Patrick

**Comment by David4kraftwerk** [comment]
@patrickkurras 

habe jetzt ein Ticket für den Support erstellt. Das Bearer-Token ist leider nur ein Workaround, steht aber alles genauer im Ticket!

LG,
David
