### ISSUE TITLE
API endpoint to submit working hours

### ISSUE THREAD

**Issue by chripo** [hellohq-io/hellohq.docs#68]
The API does not provide an endpoint to submit working hours 
**nor** to mark or submit the information within a reporting.

I know there is an global setting to let reports count as working hours,
but this is **sadly** not available on account basis.

**Comment by monderino** [comment]
Hi @chripo 

Yes, currently we do not have endpoints for working times. You can only work with reportings. 
All about working times need to control in helloHQ itself.

Best regards
Sven

**Comment by chripo** [comment]
Is there a roadmap to extend the API?

**Comment by monderino** [comment]
Not in this area.

But you can open a feature request to our support team by sending a mail to support@hellohq.io and a detailed description about your case.

Best 
Sven

**Comment by rene-piel** [comment]
Hi @monderino,

we also have the same request about an endpoint to submit working hours. 

Currently we implementing  a solution to record our working hours via a simple voice message and a subsequent speech recognition. We won't abstain from this solution, so we are also interested in an extended API...

**Comment by chripo** [comment]
I suggested the following features

- separate endpoint to submit working hours
- extend the [CreateReporting](https://developer.hellohq.io/apidocs/#/Projects%20-%20Projects/post_v1_Projects__Id___do_CreateReporting)

it go's as feedback to the product team.
feature request closed.

stay tuned.

**Comment by monderino** [comment]
Thank you.

**Comment by chripo** [comment]
i would like to keep the issue open, because it's not solved.

https://support.hellohq.io/hc/de/articles/360015225540-Bisherige-Updates-HQ-Updatehistorie-
https://www.hellohq.io/glasqgel/

**Comment by bsc310** [comment]
Hi @monderino ...
Any news about Feature Request: 40765
Still waitung for the Endpoint to sumbit working hours...

**Comment by nfech01** [comment]
Urgently needed. Any road map on that?

**Comment by j0k3rabg** [comment]
hey any updates regarding this feature? It would be quite useful for a use case that we have :)
