### ISSUE TITLE
Subsystem assignment during project creation on /v1/Projects/do.Create endpoint

### ISSUE THREAD

**Issue by FutureErik** [hellohq-io/hellohq.docs#69]
Hello,

when creating a project over the /v1/Projects/do.Create endpoint, it is beeing created in our "Admin" subsystem.
In the API documentation for this endpoint there is no parameter given for selecting the desired subsystem.

Is this by design or is it there a parameter for the target subsystem?

thanks,
Erik

**Comment by monderino** [comment]
Hi @FutureErik,

Yes, this is by design. And currently we do not have any plans to add this.

Best regards
Sven

**Comment by FutureErik** [comment]
Hi Sven, 

thank you for your answer. So the process would be to put all projects over the API, then go to master subsystem ("Admin" in our case) and assign the projects to their designated subsystem(s) by hand?

Also a correction for my previous post: created projects don't get any subsystem assigned and are thus only visible in the master subsystem.

Erik

**Comment by monderino** [comment]
Hi Erik,

yes this is currently the way. you need to go to every project and assign a subsystem by hand.

Sorry for the inconvenience.

Best regards
Sven
