### ISSUE TITLE
Set parent Project via API

### ISSUE THREAD

**Issue by latenzio** [hellohq-io/hellohq.docs#7]
**Describe**
Is it possible to set a parent Project on Project creation?

**Comment by monderino** [comment]
Hi @latenzio,

currently we do not have this possibility in our API. If you really want this feature you can create a feature request.
Just send a mail to support@hellohq.io (Subject: Feedback) and tell us about the feature you are missing and for which (HQ) customer it shall be.

Thank you and best regards
Sven
