### ISSUE TITLE
Problem bei Erstellung von Projekt mit AworkSyncId

### ISSUE THREAD

**Issue by BID-Equity** [hellohq-io/hellohq.docs#70]
**Describe**

Passing the parameter AworkSyncId when wanting to create a new project through the REST API results in an error.

**Additional context**
Erstellung von Projekt mit minimalen Daten funktioniert.
![create project minimal data](https://user-images.githubusercontent.com/91619247/209823587-7e2b035b-fab6-4c4e-a7b8-843e8b01cfc5.png)
Wenn versucht wird ein Projekt mit dem Param AworkSyncId zu erstellen, führt dies zu einem Fehler
![AworkSyncId not recognised as param](https://user-images.githubusercontent.com/91619247/209823590-21b02382-126e-45af-bedc-51fed5fac7fa.png)
Das Feld AworkSyncId hat einen anderen Namen in der Weboberfläche - "Awork Projekt Id"
![AworkSyncId name in project overview](https://user-images.githubusercontent.com/91619247/209823592-ec95c735-1ea0-453f-83fd-030515652d30.png)
Wenn versucht wird mit dem Namen ein Projekt zu erstellen, führt das auch zum Fehler
![Creating project with alternate AworkSyncId name](https://user-images.githubusercontent.com/91619247/209823593-563fb92a-bd06-48bc-96aa-f29b232f0eb6.png)
Versucht ein bestehendes Projekt zu updaten um evtl. so die AworkSyncId im Nachhinein hinzuzufügen - existiert nicht.
![Put method doesnt exist](https://user-images.githubusercontent.com/91619247/209823595-3fa470fc-c911-482a-8f3e-636f49980778.png)

**Comment by monderino** [comment]
Hi @BID-Equity,

aktuell ist es nicht möglich die awork Id über die API zu setzen. Diese kann nur abgerufen werden. 
Die awork Id muss aktuell in helloHQ eingetragen werden, da danach eine spezielle Synchronisation zu awork gestartet wird welche nicht in der API vorhanden ist.

Viele Grüße
Sven
