### ISSUE TITLE
API PUT request not working

### ISSUE THREAD

**Issue by FSalphanauten** [hellohq-io/hellohq.docs#71]
Hello, 

When making a PUT request, I get the following return message "No object created" and no error code is returned.

This issue has been observed on the following endpoint: /v1/Users({Id})/Reportings({ReportingId}), all other requests are working.

![grafik](https://user-images.githubusercontent.com/122805221/212707167-f0b3dc6d-c45f-4789-ac92-8c457a8b8d65.png)

**Comment by monderino** [comment]
Hi @FSalphanauten,

are you sure that the user and the reporting you try to update exist?
Can you please provide the Id's and the name of your organisation? Then I can check what happened.

Best 
Sven

**Comment by FSalphanauten** [comment]
Hello, I would appreciate it if we could continue this conversation via email. Could you please provide me with your email address so we can continue our discussion in a more private setting? 
Thank you.

**Comment by monderino** [comment]
Do you see my mail address in my profile ?

**Comment by monderino** [comment]
For documentation:

Solution was that the PUT model wasn't complete. It is necessary to send the complete modal of the reporting.
