### ISSUE TITLE
Zuordnung von BookingAccount (Erlöskonto) über API nicht möglich

### ISSUE THREAD

**Issue by Dylane69** [hellohq-io/hellohq.docs#72]
**Describe the bug**
wir versuchen über die HQ API Invoices anzulegen. Innerhalb der Invoices gibt es Rechnungspostionen denen Erlöskonten (BookingAccount) zugeordnet werden können. Das funktioniert aber leider nicht, weder als POST eines neuen Invoice, noch als PUT einer Rechnungsposition.

**To Reproduce**
1. Add request as Curl
curl --location --request PUT 'https://xxx.hellohq.io/v1/Invoices(xxx)/Positions(xxx)' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer TOKEN' \
--data-raw '{
    "Text": "This is a text",
    "BookingAccount": "999999"
}'
3. Add response
{
    "@odata.context": "http://xxx.hellohq.io/v1/$metadata#DocumentPositions/$entity",
    **"Text": "This is a text",**
    "Unit": "",
    "Type": "Article",
    "Order": 0,
    "ArticleId": null,
    "ProjectId": null,
    "Amount": 0.0,
    "ProjectBudgetId": null,
    "CostTypeId": null,
    **"BookingAccount": null,**
    "CostCenter1": null,
    "CostCenter2": null,
    "DocumentId": xxx,
    "Id": xxx,
    "CreatedBy": xxx,
    "UpdatedBy": xxx,
    "CreatedOn": "2023-01-18T14:07:59.93Z",
    "UpdatedOn": "2023-01-19T11:27:28.8250792Z",
    "IsOptional": null,
    "Tax": 0.0,
    "Price": 0,
    "Discount": 0,
    "Margin": 0,
    "ExcludeFromEarlyPayment": null,
    "TotalPrice": 0,
    "TotalUnitPrice": 0,
    "TotalVat": 0
}

**Expected behavior**
Eine Zuordnung von BookingAccount (Erlöskonto) zu einer Rechnungsposition.

**Screenshots**

**Environment (please complete the following information):**
 - getestet in Postman unter Ubuntu

**Additional context**

Vielen Dank im Voraus für die Unterstützung.

**Comment by monderino** [comment]
Hi @Dylane69 ,

um das Buchgungskonto bei einer Position hinzufügen gibt es das Feld BookingAccount. Hier einfach den Namen des Buchungskonto angeben und dann wird das der Position hinzugefügt. Dies hast du ja schon gemacht.
Das Buchungskonto muss aber auch in helloHQ existieren...

Bitte beachte das du ein PUT nutzt, hier muss du alle Daten der Position senden. Wenn du nur einen Teil sendest kann der Endpoint nicht richtig funktionieren oder wird im schlimmsten Fall die Daten aus der Position löschen die nicht im PUT vorhanden sind.

Ich hoffe das Hilft dir weiter. 

Viele Grüße
Sven

**Comment by Dylane69** [comment]
Hallo @monderino,

erst mal vielen Dank für deine Rückmeldung. Habe ich gerade ausprobiert und wenn ich den Namen anstatt der Nummer übergebe, funktioniert es auch.

 Wir haben aber leider nur die Nummer zur Verfügung beim Datenimport. Deswegen folgende Fragen:

1. Warum wird, das beim Artikel hinterlegte Erlöskonto, nicht automatisch mit gesetzt, wenn ich eine Position mit einem entsprechenden Artikel erstelle? Oder gibt es dafür eine Option, die ich mit übergeben kann?  Das wäre natürlich die einfachste Variante für uns.

Oder 

2. Gibt es eine Möglichkeit anhand der Nummer, den Namen des hinterlegt Erlöskonto zu erhalten? 
Wenn ich den Artikel abfrage, bekomme ich die Nummer anstatt den Namen zurück. Die kann ich aber leider nutzen, da ich den Namen benötigt beim anlegen der Position. Oder gibt es einen Entpunkt zum Abfragen der hinterlegten Erlöskonten?


Vielen Dank schon mal für deine Mühe. Ich hoffe, ich konnte unser Problem  verständlich darstellen.

Viele Grüße,

Dylane

**Comment by monderino** [comment]
Hey Dylane,

danke für deinen Input. Da hast du natürlich recht.
Option 1 wäre die Beste, ich kann prüfen, inwieweit wir das umsetzen können, ohne dabei das Verhalten für andere Kunden zu verändern.
Was wir dir auf jeden Fall zur Verfügung stellen können, ist Version 2.
Wir setzen uns Montag dran, dann ist es im Laufe der Woche online. Das Feld wird sich dabei nicht ändern.

Viele Grüße
Sven

**Comment by Dylane69** [comment]
Das hört sich doch schon mal super an. 

Vielen Dank für Ihre Mühen.

Ich freu mich von Dir zu hören und wünsche Dir ein schönes Wochenende.

Viele Grüße,

Dylane.

**Comment by monderino** [comment]
Moin,

Version 2 ist online.
Version 1 können wir aktuell nicht sicherstellen.

Viele Grüße
Sven

**Comment by Dylane69** [comment]
Hallo Sven,

kannst du uns bitte sagen, über welchen Endpunkt die Information angefragt werden kann?

Viele Grüße, Dylane

**Comment by monderino** [comment]
Moin Dylane,

also du fragst die Daten weiterhin über den Artikel ab. Und du kannst nun die Nummer das Buchungskonto einfach im Feld BookingAccount übergeben.

So hatte ich es verstanden. Hoffe das war so und hilft dir weiter?

Viele Grüße
Sven
