### ISSUE TITLE
Hinterlegte Texte zu Template abfragen

### ISSUE THREAD

**Issue by Dylane69** [hellohq-io/hellohq.docs#74]
Hallo,

gibt es eine Möglichkeit die hinterlegten Text zu einem Dokumententyp abzufragen? Speziell geht es darum, dass wir verschiedene Rechnungstemplates haben. Wenn  wir die "DocumentTemplateId" beim anlegen einer Rechnung angeben, werden die hinterlegten Text (Subject, Header und Footer) nicht automatisch übernommen. 
Gibt es einen Möglichkeit/Endpunkt der uns diese Informationen zurückliefert, damit wir diese mit angeben können?

Wiedermal, vielen Dank im voraus.

Dylane

**Comment by monderino** [comment]
Hi Dylane,

leider geht dies aktuell nur über die UI. 
Dieses Thema gab es vor kurzem schon mal: https://github.com/hellohq-io/hellohq.docs/issues/73

Viele Grüße
Sven

**Comment by Dylane69** [comment]
Hallo Sven,

vielen Dank für die schnelle Antwort.

Schade, da kann man dann erst mal nichts machen.

Viele Grüße,
Dylane
