### ISSUE TITLE
Keine Gesamtsumme in der Vorschau

### ISSUE THREAD

**Issue by Dylane69** [hellohq-io/hellohq.docs#75]
Hallo Sven,

ich muss leider noch mal nerven.

Wir haben noch Phänomen, welches wir uns nicht ganz erklären können. Wenn wir eine neue Rechnung über die API anlegen,  wird in der UI alles richtig angezeigt. Wenn wir aber auf die PDF Vorschau klicken, dann wird der Bereich der Gesamtsumme nicht generiert - die Positionen werden aufgelistet.

Erst wenn wir in der UI einmal in bearbeiten wechsel und wieder zurück (ohne etwas zu ändern),  wir auch der Block mit der Gesamtsumme in der Vorschau angezeigt.

Ich hab die Rechnungsdaten mal über die API vergleichen. Bevor wir in UI auf bearbeiten klicken, mit den Daten nachdem wir auf bearbeiten geklickt haben. Ich konnte keinen Unterschied feststellen. Ich hatte mir erhofft, dass ich eventuell ein benötigten Parameter entdecke, den wir nicht mitschicken.

Wir haben auch probiert ob es einen Unterschied macht, wenn wir die Felder
"NetTotal": ,"GrossTotal": ,"VatTotal" mit schicken oder berechnen lassen. Leider auch ohne Erfolg.

Hier einmal ein Beispiel  JSON-Daten, die wir senden:

`{
    "InvoiceDate": "2023-02-01T00:00:00Z",
    "BookingDate": "2023-02-01T00:00:00Z",
    "Currency": "EUR",
    "PaymentConditionId": 4007,
    "DeliveryConditionId": 4005,
    "DiscountType": "NetValue",
    "NetTotal": 10.00000,
    "GrossTotal": 11.90000,
    "VatTotal": 1.90000,
    "PaidTotal": 0,
    "Type": "Invoice",
    "TypeText": "Invoice",
    "AddressText": "Adresse",
    "CompanyAddressId": 51290,
    "Subject": "Sunject",
    "Header": "F&uuml;r bisher angefallene Fremdkosten und Agenturleistungen berechnen wir Ihnen:",
    "Footer": "Dieser Beleg wird elektronisch versandt ",
    "DocumentTemplateId": 4189,
    "CompanyId": 107183,
    "InternalContactPersonId": 11065,
    "Language": "de-DE",
	"Positions": [
		{
		"Text": "FTP-Zugriff (100 MByte)",
		"Type": "Article",
		"Order": 5,
		"ArticleId": 4279,
		"ProjectId": null,
		"Amount": 1.0,
		"BookingAccount": "839610",
		"DocumentId": 12374,
		"Id": 27234,
		"Tax": 19.0,
		"Price": 10.00000,
		"TotalPrice": 10.00,
		"TotalUnitPrice": 10.00000,
		"TotalVat": 1.9
		}
	]
}`

Nochmals vielen Dank für deine Hilfe.

Viele Grüße,
Dylane

**Comment by monderino** [comment]
Hi Dylane,

vielen Dank für die Info. Diese Werte sollten eigentlich direkt angezeigt werden. Ich checke das und melde mich wieder.

Viele Grüße
Sven

**Comment by Dylane69** [comment]
Hallo Sven,

zunächst einmal danke für deine/eure Unterstützung. 
Das gesamte HQ-Projekt steht und fällt mit der erfolgreichen Erstellung von Rechnungen. Daher ist es ganz wichtig und dringend, dass wir eine Lösung für das Problem finden.

Ich sende dir noch mal zwei Screenshots zu. 

In der Preview und natürlich auch in der PDF der (über die API) erstellten Rechnung fehlt der ganze Teil mit der Summe, Steuern etc.

Im UI wird alles ordentlich dargestellt.

![2023-02-02_hq_invoice_preview_screenshot](https://user-images.githubusercontent.com/123076197/216300669-458e6f5e-2856-4eef-a82e-046fdec2f4f7.png)
![2023-02-02_hq_invoice_screenshot](https://user-images.githubusercontent.com/123076197/216300671-e6a0f9b2-8057-4faa-b35b-e75c402de41e.png)

Erst wenn wir in der UI auf bearbeiten und speichern klicken, ohne sonst etwas zu machen, wird alles in der Vorschau und im PDF angezeigt.

Das Problem ist aber leider, dass wir das nicht für jede übertragene Rechnung machen können.

Vielleicht müssen wir noch ein event auslösen oder irgend einen Parameter setzen. 

Hoffentlich findet ihr schnell eine Lösung für das Problem.

Viele Grüße
Dylane

**Comment by monderino** [comment]
Danke für die weiteren Informationen. Die Daten sollten auf jeden Fall sichtbar sein ohne das Ihr den Beleg bearbeiten müsst.

**Comment by Dylane69** [comment]
Bitte prüfe mal die PDF bzw. die PREVIEW! Dort sind die Informationen nicht sichtbar. 
Ich kann dir noch weitere Screeshots machen, wenn erforderlich.

**Comment by Dylane69** [comment]
Previewansicht. Die Rechnungsdaten fehlen.
![2023-02-02_hq_invoice_pv_screen](https://user-images.githubusercontent.com/123076197/216321304-164d13b5-e540-4995-bff0-08eac3f97172.png)

**Comment by monderino** [comment]
Ist zu morgen gefixt.

Viele Grüße
