### ISSUE TITLE
Rechnung versenden

### ISSUE THREAD

**Issue by Dylane69** [hellohq-io/hellohq.docs#76]
Hallo Sven,

ich habe noch eine Frage. Gibt es über die API die Möglichkeit Rechnung direkt zu versenden? Also praktisch die Funktionalität, die uns der Button "Versenden", in der Rechnung zur Verfügung stellt?

Vielen Dank und einen schönen Abend,

Dylane

**Comment by monderino** [comment]
Hi Dylane,

nein dies geht nur über die UI.

Viele Grüße
Sven
