### ISSUE TITLE
HTML Tags in Planned Revenue description

### ISSUE THREAD

**Issue by David4kraftwerk** [hellohq-io/hellohq.docs#78]
Liebes HQ-Team!

Mit Bezug auf Issue "Custom PowerBi Report #77", wollte ich fragen weshalb das die Spalte "Description" vom Endpoint GET v1/PlannedRevenues nicht nur eine Beschreibung, sondern auch HTML beinhaltet.

Wir hätten gerne nur die Beschreibung in dieser Spalte und möchten daher wissen wie man dieses Verhalten vermeiden bzw. umgehen kann.

Danke schon mal!

LG,
David

![Screenshot_20230203_173926](https://user-images.githubusercontent.com/119495092/216657702-92d87439-1bc6-4cda-af8d-dd46ceb5a3b7.png)

**Comment by patrickkurras** [comment]
Hallo @David4kraftwerk ,

hier geben wir leider direkt die Felder so wieder wie sie in der Datenbank stehen. Deshalb gibt es hier leider aktuell keine Möglichkeit dieses Feld ohne HTML Styling aus der API zu bekommen.

Viele Grüße
Patrick

**Comment by David4kraftwerk** [comment]
Hey @patrickkurras,

danke für die schnelle Antwort. Ok, dann werde ich schauen, dass ich das auf unserer Seite Filtern kann!

LG,
David
