### ISSUE TITLE
HQ API-Access - Daten aktualisieren in Excel

### ISSUE THREAD

**Issue by Ferassdd** [hellohq-io/hellohq.docs#81]
Halo zusammen,
ich kann mit dem Excel Addin  HQ API-Acess Daten aus HQ in Excel importieren - wenn ich die Daten aber aktualisieren will (z.B. Alle Aktualisieren ) wird mir eine Fehlermeldung angezeigt (dass die Verbindung anonym hergestellt werden muss - siehe Anhang) - ich weiß aber nicht wo ich die Einstellungen für anonyme Abfrage finden kann - wenn ich in Excel bei PowerQ auf "Datenquelleneinstellungen" gehe, wird mir auch keine Datenquelle angezeigt. Ich benutze einen Mac.
<img width="372" alt="Bildschirm­foto 2023-02-09 um 10 27 10" src="https://user-images.githubusercontent.com/125861402/220043297-8a2c6418-1238-4d49-8fa1-0b926b3f0d39.png">

Kann jmd mir dabei helfen ?

Danke im Voraus.

**Comment by monderino** [comment]
Hi @Ferassdd,

Was genau meinst du mit 'Alle Aktualisieren'? Mit unserem Add-In kannst du nur Daten herunterladen aber nicht verändern und dann wieder hochladen.

Viele Grüße
Sven

**Comment by Ferassdd** [comment]
Hi Sven,
danke für deine Rückmeldung.
ich meine das Feld hier:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/125861402/220295511-3a5a0dd5-731b-4dc3-8963-16b3c449460b.png">

**Comment by monderino** [comment]
Das hat nichts mit unserem Add-In zu tun.
Hast du eine die Daten mit einer Power-Query abgerufen?

**Comment by Ferassdd** [comment]
ja, ich bekomme dann diese Fehlermeldung:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/125861402/220297746-6a42c25d-14ca-4c35-be73-5f9a1af4323e.png">

**Comment by Ferassdd** [comment]
<img width="891" alt="image" src="https://user-images.githubusercontent.com/125861402/220298004-0ce372ab-8f81-4bf3-a0ae-99e694b1ecaf.png">

**Comment by monderino** [comment]
Könntest du mir eine Anleitung schreiben wie du das in Excel eingerichtet hast?
Vielleicht kann ich das dan nachvollziehen und dir besser helfen. So ist es leider sehr schwierig.

**Comment by Ferassdd** [comment]
Hi, sorry für die verspätete Antwort.
Ich importiere die Daten via HQ Api-Access in Excel und bearbeite diese in Power-Query. Bislang war das alles problemlos möglich. Wenn ich jetzt aber die Daten in PQ aktualisieren will, poppt diese Fehlermeldung auf.
Die Fehlerquelle ist meines Wissens die nicht anonym konfigurierte Verbindung.

Ich habe es jetzt von einem anderen Rechner probiert und es hat funktioniert. Zwar kam zuerst auch diese Fehlermeldung, es gab aber ein Button "Verbindung" anstelle von "Details anzeigen", wo ich die Verbindung konfigurieren und auf "anonym" umstellen konnte. _**Mit meinem aktuellen Rechner finde ich diese Option nicht**_, weder bei Eigenschaften noch bei den Datenquelleneinstellungen. Ich benutze einen MacBook Air.
Mir würde helfen, diese Option zur Verbindungskonfiguration zu finden.

**Comment by monderino** [comment]
hey @Ferassdd,

ich habe auch noch mal verschiedene Kollegen gefragt, leider weiß niemand was man da in Excel einstellen bzw. hinterlegen muss. Tut mir sehr leid aber ich denke wir können dir hier nicht weiterhelfen.

Viele Grüße
Sven

**Comment by monderino** [comment]
Hey @Ferassdd,

Denke wir konnten was finden. Was du da nutzt ist ein Windows Feature. Gibt es auf Mac nicht.
https://support.hellohq.io/hc/de/articles/360000534939-API-Excel-Zugriff-mit-Windows-via-Daten-abrufen-

Viele Grüße
