### ISSUE TITLE
Auswertung Fortschritt

### ISSUE THREAD

**Issue by GeekMichel** [hellohq-io/hellohq.docs#83]
Guten Tag!

Wir wollen einen automatischen Mailversand wenn eine Phase/Task einen Report-Wert von 80% erreicht und einmal ab 100%. Ich habe mir die RestAPI Doku unter https://developer.hellohq.io/apidocs/ angeschaut und ein bisschen getestet. Über https://api.hellohq.io/v1/ProjectTasks kann ich mir alle Tasks anzeigen lassen. In dem jeweiligen Task steht auch „PlannedEffort“ als Stunde drin, also die geplanten Stunden. Dort stehen aber nicht die bereits darauf verbuchten Reports. Gibt es den Wert irgendwo abzufragen?
 
Ich habe nur unter https://api.hellohq.io/v1/UserReportings die Möglichkeit alle Reports zu ziehen. Man müsste dann ja alle Tasks aufzählen und pro Task alle Rückmeldungen der ID durchsuchen, addieren und dann mit dem „PlannedEffort“ vergleichen. Die Frage ist ob es auch "besser" geht.
 
Im Frontend sieht man ja auch die Werte, mit denen wir arbeiten wollen.:
 
![hellohq-reports](https://user-images.githubusercontent.com/127857732/225008236-a922eed1-ff0d-4170-92c3-7a945d4243e8.jpg)
 
 
Kann man diese Werte „anzapfen“? Gibt es eine bessere Methode wie die von mir oben beschrieben?

**Comment by Schaukelking** [comment]
Hey! Sorry für die späte Antwort!

1. Ihr könnt euch dafür auch einfach einen Workflow anlegen lassen. Workflows sind eine helloHQ interne Funktionalität, die genau für so etwas vorgesehen ist. Man kann dort konfigurieren, dass bei einem Projektfortschritt von 80 oder 100% eine Email an eine bestimmte person / ProjektRolle gesendet wird oder eine Aufgabe im helloHQ dafür erstellt wird. Ob dieser Schwellwert überschritten wird überprüfen wir bei jedem neuen Reporting.
2.  Sonst ist dein Ansatz schon richtig, allerdings kannst du dir einen call sparen, indem du ein expand auf die UserReportings des ProjectTasks machst
=> `https://api.hellohq.io/v1/ProjectTasks?$expand=UserReportings`
Der call liefert dir alle tasks inklusive der Reportings in einem Objekt zurück. Damit sparst du dir den zweiten call und den ID-Abgleich.

Ich hoffe das hat dir weiter geholfen.
Beste Grüße
Patrick
