### ISSUE TITLE
API call zum Suchen von ContactPersons

### ISSUE THREAD

**Issue by vogelskamp** [hellohq-io/hellohq.docs#87]
Hi, wir können in der API Doku keinen Call zum Suchen von Kontakten finden. Wir speichern die helloHQ-Id nicht innerhalb unserer Anwendung und würden gerne via Such-Call über die Telefonnummer unseren Kontakt zur helloHQ-Entity matchen, damit wir diese im Folgenden updaten/löschen können.

Die einzige Alternative aktuell wäre es, beim Update alle helloHQ-Kontakte zu fetchen und dann in-memory die Telefonnummer zu matchen, was hoch ineffizient und belastend ist.

[Hier](https://desk.zoho.com/DeskAPIDocument#Search) ein Beispiel aus einem anderen CRM. Wird dieses Feature in Zukunft verfügbar sein?

**Comment by monderino** [comment]
Hi @vogelskamp,

wir unterstützen aktuell den OData Standard zum Filtern in der API. Wenn du in der Doku nach Filter suchst findest du auch einige Beispiele dazu.
In deinem Fall wäre die Abfrage diese:
`https://api.hellohq.io/v1/ContactPersons?$filter=PhoneLandline eq '123455'`

Ich hoffe das hilft dir weiter.

Viele Grüße
Sven
