### ISSUE TITLE
API Limitations

### ISSUE THREAD

**Issue by vogelskamp** [hellohq-io/hellohq.docs#88]
Damit wir unseren Kund:innen genau kommunizieren können, was wir mit unserer HelloHQ Integration bieten können, wollten wir uns erkundigen was für API Limitierungen ihr habt. Habt ihr da Regeln in Richtung X Anfragen pro Sekunde an bestimmte Endpunkte bevor Fehlercode 123 kommt? Je mehr Infos desto besser.

**Comment by monderino** [comment]
Moin @vogelskamp,

aktuell haben wir kein Rate-Limiting implementiert. Aktuell implementieren wir jedoch die v2 Version unserer API. Diese wird ein Rate-Limiting besitzen. Wie dies aussehen wird steht jedoch noch nicht fest.

Viele Grüße
Sven
