### ISSUE TITLE
Question about API

### ISSUE THREAD

**Issue by EXEO2022** [hellohq-io/hellohq.docs#89]
Hi, I`m trying to change Leads using API. https://developer.hellohq.io/apidocs/# . There I found following endpoint for this case: https://api.hellohq.io/v1/Leads{id}/CustomFields{id} . When I trying to make request using swagger I`ve got 500 Error. I understand that this error from your side, but I think that in this case i can make request wrong. Could you help me with it? 

request body: {
    "id": 26940,
    "created_at": null,
    "arrival_at": "2023-01-30",
    "customer_name": "Schichtplan Test",
    "contact_person": "Frau Bappe Bockelmann",
    "status": "Open",
    "required_trainers_amount": 3,
    "location": "Noch offen / Raum Deutschland",
    "location_ev": "",
    "automobile": "",
    "attention_peculiarity": "",
    "hotel_bill": "",
    "called_asp": "",
    "event_title": "TeamEvent mit Action Painting o. Nipa",
    "event_title_gmbh": "",
    "event_title_ev": "",
    "tn": "119",
    "offload": "",
    "expenditure": "",
    "daily_rate": "225",
    "subsystem": "GmbH",
    "hq_labs_synced": false,
    "program_block_names": "Action Painting GmbH;Nipa GmbH",
    "required_language": "German",
    "departure": "2023-02-01",
    "programPeriod": "24.01.2023",
    "difference": [
        "2023-01-30",
        "2023-01-31",
        "2023-02-01"
    ],
    "special": null,
    "specialFeature": null,
    "cache": "123$",
    "title": "TeamEvent mit Action Painting o. Nipa",
    "start": "2023-01-30",
    "end": "2023-02-01",
    "allDay": true
}
![image](https://user-images.githubusercontent.com/97952023/231411302-2f8badbe-9715-4b68-8064-5d3c9cd42ad4.png)

Response: Oops! Sorry, something went wrong. Please contact us in our developer portal at https://developer.helloHQ.io so we can assist you.

![image](https://user-images.githubusercontent.com/97952023/231411497-2e9f3d37-03f5-481e-a50f-6bef56a81e3f.png)

Thanks a lot

**Comment by EXEO2022** [comment]
Thank`s a lot. I understand how to get leads and now I would like to try create a Lead. In postman I`ve got following Error
![image](https://user-images.githubusercontent.com/97952023/231725562-5a0c7b63-4e50-4661-b789-bb9ad78f12cc.png)
In body I put following data: {
  "Name": "TestFromSchichtplan",
  "CompanyName": "EXEO",
  "Number": "231074",
  "Company": {
    "Name": "Schichtplan TestFromSchichtplan",
    "IndustrialSector": "",
    "Description": "Test",
    
    "Addresses": [
      {}
    ],
    "ResponsibleUsers": [
      {}
    ],
    "CustomFields": [
      {}
    ],
    "CompanyTypes": [
      {}
    ],
    "Files": [
      {}
    ],
    "Subsystems": [
      {}
    ],
    "Id": 0,
    "CreatedBy": 0,
    "UpdatedBy": 0,
    "CreatedOn": "2023-04-13T08:41:08.316Z",
    "UpdatedOn": "2023-04-13T08:41:08.316Z"
  },
  "Status": {
    "Name": "Absage / Keine Rückmeldung",
    "Type": "NotSet",
    "Id": 0,
    "CreatedBy": 0,
    "UpdatedBy": 0,
    "CreatedOn": "2023-04-13T08:41:08.316Z",
    "UpdatedOn": "2023-04-13T08:41:08.316Z"
  },
  "StatusId": 0,
  "CashOn": "2023-04-13T08:41:08.316Z",
  "ClosingProbability": 0,
  "Currency": "str",
  "Volume": 0,
  "CompanyId": 0,
  "CustomFields": [
    {
      "Name": "Anreise Tr.",
      "Value": "Mon Mar 20 2023 02:00:00 GMT+0200 (Eastern European Standard Time)",
      "Type": "string",
      "Id": 0,
      "CreatedBy": 0,
      "UpdatedBy": 0,
      "CreatedOn": "2023-04-13",
      "UpdatedOn": "2023-04-13"
    }, {
      "Name": "Abreise Tr.",
      "Value": "Mon Mar 20 2023 02:00:00 GMT+0200 (Eastern European Standard Time)",
      "Type": "string",
      "Id": 0,
      "CreatedBy": 0,
      "UpdatedBy": 0,
      "CreatedOn": "2023-04-13",
      "UpdatedOn": "2023-04-13"
    }, {
      "Name": "Programmbausteine",
      "Value": "Action Painting GmbH;Bombenentschärfung GmbH",
      "Type": "string",
      "Id": 0,
      "CreatedBy": 0,
      "UpdatedBy": 0,
      "CreatedOn": "2023-04-13",
      "UpdatedOn": "2023-04-13"
    }
  ],
  "ResponsibleUserId": 0,
  "ResponsibleUser": {
    "FirstName": "Baptiste",
    "LastName": "Bockelman",
    "UserName": "Baptiste",
    "EMailWork": "",
    "Salutation": "",
    "Title": "",
    "EmployeeNumber": "",
    "BirthDate": "2023-04-13T08:41:08.316Z",
    "FederalState": "",
    "Country": "Germany",
    "BasicLoadInHours": 0,
    "EntryDate": "2023-04-13T08:41:08.316Z",
    "LeavingDate": "2023-04-13T08:41:08.316Z",
    "PhoneLandlinePrivate": "",
    "PhoneLandlineWork": "",
    "PhoneMobilePrivate": "",
    "PhoneMobileWork": "",
    "UserWorkingHours": [
      {}
    ],
    "CustomFields": [
      {}
    ],
    "UserGroups": [
      {}
    ],
    "ResourceGroup": {},
    "Absences": [
      {}
    ],
    "Assignments": [
      {}
    ],
    "Reportings": [
      {}
    ],
    "ProjectMembers": [
      {}
    ],
    "Id": 0,
    "CreatedBy": 0,
    "UpdatedBy": 0,
    "CreatedOn": "2023-04-13T08:41:08.316Z",
    "UpdatedOn": "2023-04-13T08:41:08.316Z"
  },
  "SalesCampaigns": [
    {
      "Name": "Exeo",
      "Id": 0,
      "CreatedBy": 0,
      "UpdatedBy": 0,
      "CreatedOn": "2023-04-13T08:41:08.316Z",
      "UpdatedOn": "2023-04-13T08:41:08.316Z"
    }
  ],
  "ContactPersons": [
    {
      "FirstName": "Baptiste",
      "LastName": "Bockelman",
      "Position": "manager",
      "CompanyId": 0,
      "PhoneLandline": "",
      "PhoneMobile": "",
      "Salutation": "",
      "Birthdate": "",
      "SalutationForm": "",
      "Title": "",
      "Language": "German",
      "DefaultAddressId": 0,
      "DefaultAddress": {},
      "Company": {},
      "Id": 0,
      "CreatedBy": 0,
      "UpdatedBy": 0,
      "CreatedOn": "2023-04-13T08:41:08.316Z",
      "UpdatedOn": "2023-04-13T08:41:08.316Z"
    }
  ],
  "Subsystems": [
    {
      "Name": "GmbH",
      "IsMaster": true,
      "Id": 0,
      "CreatedBy": 0,
      "UpdatedBy": 0,
      "CreatedOn": "2023-04-13T08:41:08.316Z",
      "UpdatedOn": "2023-04-13T08:41:08.316Z"
    }
  ],
  "ProjectId": 0,
  "Project": {
    "Number": "",
    "Name": "",
    "Status": "NotSet",
    "PlannedStartDate": "2023-04-13T08:41:08.316Z",
    "PlannedEndDate": "2023-04-13T08:41:08.316Z",
    "StartDate": "2023-04-13T08:41:08.316Z",
    "EndDate": "2023-04-13T08:41:08.316Z",
    "AworkSyncId": "string",
    "Subsystems": [
      {}
    ],
    "ProjectTemplateId": 0,
    "ProjectTemplate": {},
    "ProjectStatusId": 0,
    "CompanyId": 0,
    "LeadId": 0,
    "InvoiceAddressId": 0,
    "DeliveryAddressId": 0,
    "ResponsibleUserId": 0,
    "ProjectStatus": {},
    "Company": {},
    "ResponsibleUser": {},
    "DeliveryAddress": {},
    "InvoiceAddress": {},
    "Lead": {},
    "CustomFields": [
      {}
    ],
    "Reportings": [
      {}
    ],
    "Files": [
      {}
    ],
    "Members": [
      {}
    ],
    "ContactHistories": [
      {}
    ],
    "ContactPersons": [
      {}
    ],
    "Articles": [
      {}
    ],
    "ProjectBudgets": [
      {}
    ],
    "Id": 0,
    "CreatedBy": 0,
    "UpdatedBy": 0,
    "CreatedOn": "2023-04-13T08:41:08.316Z",
    "UpdatedOn": "2023-04-13T08:41:08.316Z"
  },
  "Id": 0,
  "CreatedBy": 0,
  "UpdatedBy": 0,
  "CreatedOn": "2023-04-13T08:41:08.316Z",
  "UpdatedOn": "2023-04-13T08:41:08.316Z"
}

As far as I understand the main error in CustomFields: "Type": "string". I tried to remove this field and get error, also I tried to replace "string" to custom name(f.e. "CustomName") and I`ve get error again. Could you explain me, what HQ expect get from my side? And according to my body, which data I put wrong, could explain it too, please? Thanks a lot for your support

**Comment by EXEO2022** [comment]
I figured out how to update data in custom Fields . The only thing left is to create a Lead. I have in postman following error: 
![Screenshot 2023-04-14 at 13 11 47](https://user-images.githubusercontent.com/97952023/232017283-d2c8f0f3-58d3-4988-bd38-f8f08552ad28.png)
But when I remove ContactPerson property I`ve get : 
![image](https://user-images.githubusercontent.com/97952023/232017483-c08d857b-a7dc-4cd2-8233-266239cd102b.png)
. What should I do in this case?

**Comment by Schaukelking** [comment]
I see 2 issues, one from your side one from our side :D 

1. The error message when you remove ContactPerson is wrong, it should say "ContactPersons", so the field name is ContactPersons and not ContactPerson :D 
2. As you see in the body example, "ContactPersons" is an array and you can add multiple ContactPersons
`{
    "Name": "new Lead",
    "Number": "12345",
    "StatusId": 46005,
    "CompanyId": 61066,
    "ContactPersons": [
        {
            "FirstName": "Name",
            "LastName": "Last Name"
        }
    ]
}`

This works for me

**Comment by EXEO2022** [comment]
I got it, It works fine. What about updating customFields, where can I check id of CustomFields? Because when I`m trying to update customField in existed Lead(which was created in HQ) - then would be enough to make request to `Leads(Id)/CustomFields`, and then check id of customFields. According to your advice: 
`You created a Lead via POST Leads-> Got an Id of the Lead in Response
You requested the CustomFields with GET Leads(Id)/CustomFields -> There you get an CustomFieldId back
Then you tried to call PUT Leads(id)/CustomFields(CustomFieldId) -> your body wasnt correct`
When I create lead outside of HQ - it doesn`t work, because I create Lead from my App and when I would like to check id of CustomField - I get empty array(because in HQ Lead doesn`t have any of customFields). You wrote me that I cannot put customField when I create Leads. Then I would like to understand how to update this customFields if in HQ they are not exist in common. Thanks a lot

**Comment by Schaukelking** [comment]
I guess you are right! Seems like the creation of CustomFields is missing while creating Leads via api. I will create a ticket for it, but since we are currently working on a v2 for the API and there is an other way to achieve what you want, i cannot promise that we work on it before.

The workaround:
instead of calling:
 `Leads(Id)/CustomFields`
 you can call 
`https://api.hellohq.io/v1/CustomFieldDefinitions?$filter=Category eq 'Lead'` 
to get all custom field definitions for Leads. 

You need the Id and the Name from the custom fields - and then you can call the put on the Leads(id)/CustomFields(id) endpoint

**Comment by Schaukelking** [comment]
@EXEO2022 since here was no new message from i i'm closing this issue. If there is still something bothering you just comment again! 

Best Regards

**Comment by Schaukelking** [comment]
Yes, in our UI you either can chose an existing company or directly create one. Our Api only allows existing companies, so you have to create on before, if needed.

For a Lead in our system an according company is required. Also in the ui you are forced to either chose an existing or creating one. 

Endpoint: 
POST  v1/Companies 

Example body:
{
  "Name": "new company",
  "IndustrialSector": "Kunde",
  "Description": "a Customer",
  "DefaultAddress": {
    "City": "City",
    "Street": "Street",
    "HouseNumber": "123",
    "ZipCode": "123123",
    "Country": "DE"
  }
}
