### ISSUE TITLE
deactivated users

### ISSUE THREAD

**Issue by Thomstar87** [hellohq-io/hellohq.docs#91]
Hello all,

You write:
You can add a parameter to the user call so that deactivated users are taken over: http://api.hellohq.io/v1/Users?includedeactivated=true
 
Where exactly can/must I adjust this? When I click on the link, I only get an error message....

if i download user data per API, i need the deactivated users, too! 

Thnak you

**Comment by Schaukelking** [comment]
Hey @Thomstar87 
What do you mean exactly? The call looks good and it works for me when i test it via Postman. 
You cannot just click on the link, because the call needs authorization so we know that you are allowed to see the data.

**Comment by Thomstar87** [comment]
Hello,

if i click on the link:
***@***.***

What do i have to do?

Thank you

Kind regards

Thomas Winkels
Junior Finance Manager
T +49 211 54038 130
F +49 211 54038 150
***@***.******@***.***>
www.add2.de
***@***.***
add2 GmbH | Kaistraße 16a | 40221 Düsseldorf | Germany
HR 39514 Amtsgericht Düsseldorf | CFO/COO Burkhard Rischer | CEO Simon Kathmann

Diese Nachricht kann vertrauliche Informationen enthalten und ist nur für den Adressaten bestimmt.
Sollten Sie diese Nachricht irrtümlich erhalten haben, teilen Sie dies bitte dem Absender mit
und vernichten Sie diese Mail mitsamt den Anlagen. Vielen Dank.

This message may contain confidential and privileged information. If received in error,
please reply to advise the sender of the error and delete this message. Thank you.


Von: Padsen ***@***.***>
Gesendet: Freitag, 21. April 2023 12:10
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Thomas Winkels ***@***.***>; Mention ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] deactivated users (Issue #91)


Hey @Thomstar87<https://github.com/Thomstar87>
What do you mean exactly? The call looks good and it works for me when i test it via Postman.
You cannot just click on the link, because the call needs authorization so we know that you are allowed to see the data.

**Comment by Schaukelking** [comment]
Which link? I guess it got hidden due to data security by github. 

If you want to access the data you will need to send an API request with an Authorization header. E.g. in Postman you can pass your URL, then navigate to the Authorization tab (see screenshot), select Bearer in the dropdown and then pass the API token of your system into the Token field. 
![image](https://user-images.githubusercontent.com/48789562/233994466-481bbc43-858a-4ffc-9a3d-cd92eae245bf.png)

To have access to your api client you have to be an Admin in your helloHQ system. Navigate in the menu to: Admin > Api Clients and copy the Api Token and pass it into the Token field of the screenshot. Then you should be able to access the data. We cannot hand out your system data by just clicking the link due to the missing data protection!

**Comment by Thomstar87** [comment]
Thanks for your  answer. Do i have to download "Postman" or is there any other way?

Best

**Comment by Thomstar87** [comment]
Hello,

something went wrong. Can you tell me where my fault is?

***@***.***

Best,

Thom
Thomas Winkels
Junior Finance Manager
T +49 211 54038 130
F +49 211 54038 150
***@***.******@***.***>
www.add2.de
***@***.***
add2 GmbH | Kaistraße 16a | 40221 Düsseldorf | Germany
HR 39514 Amtsgericht Düsseldorf | CFO/COO Burkhard Rischer | CEO Simon Kathmann

Diese Nachricht kann vertrauliche Informationen enthalten und ist nur für den Adressaten bestimmt.
Sollten Sie diese Nachricht irrtümlich erhalten haben, teilen Sie dies bitte dem Absender mit
und vernichten Sie diese Mail mitsamt den Anlagen. Vielen Dank.

This message may contain confidential and privileged information. If received in error,
please reply to advise the sender of the error and delete this message. Thank you.


Von: Padsen ***@***.***>
Gesendet: Montag, 24. April 2023 15:44
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Thomas Winkels ***@***.***>; Mention ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] deactivated users (Issue #91)


Hm i guess otherwise you can execute a curl command in your cmd console. I don't know if you are using mac or windows, so i hope you know how to open the command console :D The command would look like this:

curl -i https://api.hellohq.io/v1/Users?includedeacticated=true -H "Authorization: Bearer [Insert your token here]"

I hope this helps!

**Comment by Schaukelking** [comment]
Hey, sorry but i really need more information, when you're sending this via email some content gets censored for me.

1. What is the purpose of your query? Are you building an app?
2. What do you want to do with the data when you get the response? 
3. Do you have access to the API token in your helloHQ system?
4. Do you really need to get the data via api? You can also look for deactivated users in the UI if you are an admin user
5.  How did the curl request that did not work look like? What was the error message?

**Comment by Thomstar87** [comment]
Hello,

We would like to pull the data via api to include it in power bi in a dahboard
Yes i have access tot he API token in my helloHQ system 😉


  1.  Do you really need to get the data via api? You can also look for deactivated users in the UI if you are an admin user

  *   if i can see the deactivated users incl user id that would help me already
  *   can you send me a screenshot where i can find the information?
  *   in the long run but with api because everything should run as automatically as possible

5.
C:\Users\tw>   curl -i https://api.hellohq.io/v1/Users?includedeacticated=true -H "Authorization: Bearer [l90fp46XZs19ghs5MWyyqEB5790PUs8Qfsf5LyAByYs82xADZrrcZYcNdR1Mijo25SBKXtlGKEj_hOFvNTGlwaA55si96XrURxKwz426DgJ3vySblBYaehiH9FVmShVvPVSvs9bc887tdpfLNsrPzpeddHvdfe5tmhKsOM_ygb-ZS3vh48d8LgI0kUgFpLjjM7uJDBQHKPZu4xBSHtxSZm_zpL6ugNeLj-4VZ9dzoDE]"
HTTP/1.1 500 Internal Server Error
Date: Wed, 26 Apr 2023 06:25:35 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 130
Connection: keep-alive
Cache-Control: no-cache
Pragma: no-cache
Expires: -1
Strict-Transport-Security: max-age=15724800; includeSubDomains

Oops! Sorry, something went wrong. Please contact us in our developer portal at https://developer.helloHQ.io so we can assist you.
C:\Users\tw>

Thank you for your help.

Best,
Thom
Thomas Winkels
Junior Finance Manager
T +49 211 54038 130
F +49 211 54038 150
***@***.******@***.***>
www.add2.de
***@***.***
add2 GmbH | Kaistraße 16a | 40221 Düsseldorf | Germany
HR 39514 Amtsgericht Düsseldorf | CFO/COO Burkhard Rischer | CEO Simon Kathmann

Diese Nachricht kann vertrauliche Informationen enthalten und ist nur für den Adressaten bestimmt.
Sollten Sie diese Nachricht irrtümlich erhalten haben, teilen Sie dies bitte dem Absender mit
und vernichten Sie diese Mail mitsamt den Anlagen. Vielen Dank.

This message may contain confidential and privileged information. If received in error,
please reply to advise the sender of the error and delete this message. Thank you.


Von: Padsen ***@***.***>
Gesendet: Dienstag, 25. April 2023 16:30
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Thomas Winkels ***@***.***>; Mention ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] deactivated users (Issue #91)


Hey, sorry but i really need more information, when you're sending this via email some content gets censored for me.

  1.  What is the purpose of your query? Are you building an app?
  2.  What do you want to do with the data when you get the response?
  3.  Do you have access to the API token in your helloHQ system?
  4.  Do you really need to get the data via api? You can also look for deactivated users in the UI if you are an admin user
  5.  How did the curl request that did not work look like? What was the error message?

**Comment by Schaukelking** [comment]
I just censored your bearer token in your message due to data security reasons (: 
You have to remove the brackets "[" and  "]" around the bearer token, then it will work (: Can you send a curl request via power bi? I dont have experience with it and will not be able to help you with it, sadly. 

Best regards

**Comment by Thomstar87** [comment]
Hello,

it worked so far 😊

unfortunately, not all the users i need are shown. it could be that i also need the deleted users in addition to the deactivated users. is it possible to have the deleted users shown as well?

Thank you for an quick answer 😊

Best

Thom
Thomas Winkels
Junior Finance Manager
T +49 211 54038 130
F +49 211 54038 150
***@***.******@***.***>
www.add2.de
***@***.***
add2 GmbH | Kaistraße 16a | 40221 Düsseldorf | Germany
HR 39514 Amtsgericht Düsseldorf | CFO/COO Burkhard Rischer | CEO Simon Kathmann

Diese Nachricht kann vertrauliche Informationen enthalten und ist nur für den Adressaten bestimmt.
Sollten Sie diese Nachricht irrtümlich erhalten haben, teilen Sie dies bitte dem Absender mit
und vernichten Sie diese Mail mitsamt den Anlagen. Vielen Dank.

This message may contain confidential and privileged information. If received in error,
please reply to advise the sender of the error and delete this message. Thank you.


Von: Padsen ***@***.***>
Gesendet: Mittwoch, 26. April 2023 10:21
An: hellohq-io/hellohq.docs ***@***.***>
Cc: Thomas Winkels ***@***.***>; Mention ***@***.***>
Betreff: Re: [hellohq-io/hellohq.docs] deactivated users (Issue #91)


I just censored your bearer token in your message due to data security reasons (:
You have to remove the brackets "[" and "]" around the bearer token, then it will work (: Can you send a curl request via power bi? I dont have experience with it and will not be able to help you with it, sadly.

Best regards

**Comment by Schaukelking** [comment]
Sadly you cannot get the data of deleted users due to data protection reasons.

**Comment by Schaukelking** [comment]
Haha, i guess this is because you just copied my example curl and i just found a typo in it. The copied curl said "includedeactiCated" instead of "includedeactiVated" :D when you fix the type you also get boy petersen back

**Comment by Schaukelking** [comment]
You're welcome!
