### ISSUE TITLE
Unable to call Account/Authorize endpont

### ISSUE THREAD

**Issue by a-r-m-i-n** [hellohq-io/hellohq.docs#92]
**Describe the bug**
To test the API an administrator created a new app client for me, and I tried to authenticate like you've described [here](https://developer.hellohq.io/#authorization-request)

This is how I create the link:
```
<?php
$queryString = http_build_query([
    'response_type' => 'code',
    'client_id' => $this->appId,
    'state' => 'xyz',
    'redirect_uri' => urlencode('https://my-dev-domain.ddev.site.de/?routeName=hello-hq'),
    'scope' => 'read_all write_all',
]);

return 'https://api.hellohq.io/Account/Authorize?' . $queryString;
```
The actual client_id (here `$this->appId`) is `612860-avieweg-test`.

This link will point to and show the login, but then redirects to https://www.hellohq.io/SystemNichtGefunden.aspx.

Also, because we use a sub-domain to access the regular HelloHQ UI, I tried those domains too:
* iwkoeln.hellohq.io - shows an error like this:
![image](https://user-images.githubusercontent.com/1275298/234046895-16adf986-229e-4cf4-ac09-eb152ef948f8.png)
* api.iwkoeln.hellohq.io - Has invalid SSL certificate

I also tried `api.hqlabs.de` but this ended up in Error 400 (Bad Request) without any info about, what was bad.

---

So, how can I access the API in our case?

**Comment by a-r-m-i-n** [comment]
In case you want to get in touch with me, without being public, please send a mail to vieweg@iwkoeln.de

**Comment by monderino** [comment]
Hi @a-r-m-i-n,

I tested it with your settings in postman and it worked for me. I will send you a screen shot via mail.

Best Sven
