### ISSUE TITLE
API Endpoint for Private Tasks

### ISSUE THREAD

**Issue by Keew200** [hellohq-io/hellohq.docs#93]
Is there an API endpoint that can be used to create a Private Task?

I am trying to give the user some kind of notification about an external event via the API, here it would be very handy if I could create a private task for single users.

**Comment by Schaukelking** [comment]
Hey @Keew200 

Sadly there is no direct/clear way for it. What you could do:

`http://api.hellohq.io/v1/Users([userid])/Assignments?$expand=Task&$filter=Task/IsAppointment eq false and Task/ProjectId eq null`

There you get all assignments of the user, expanding the tasks and filtering the task. You will get also like FollowUp tasks (e.g. after contact history entry added) so this will not be only private tasks. But you will exclude the project tasks and appointments! 

I guess this is the nearest i can bring you. Hope this helps

Best regards

**Comment by Keew200** [comment]
Thanks for the quick answer.

```
http://api.hellohq.io/v1/Users([userid])/Assignments?$expand=Task&$filter=Task/IsAppointment eq false and Task/ProjectId eq null
```
I will take a look at this.
