### ISSUE TITLE
Refresh Token Request not working

### ISSUE THREAD

**Issue by JonEG** [hellohq-io/hellohq.docs#94]
**Refresh Token Request not working**
The documentation specifies that grant_type=refresh_token must be used, nevertheless I get an unsupported_grant_type ERROR.

![Screenshot 2023-05-02 at 12 44 56](https://user-images.githubusercontent.com/22833839/235646201-cf2c04b5-1eca-48ce-b288-d1222e2347c6.png)

![Screenshot 2023-05-02 at 12 30 50](https://user-images.githubusercontent.com/22833839/235646003-02218178-e4ec-4d07-968f-2af79302f67e.png)

**Comment by monderino** [comment]
Hi @JonEG,

can you please check your Authorization header, It looks not correct to me.  Should be a Bearer token not Basic.

Best Sven

**Comment by JonEG** [comment]
Hi @monderino, the documentation specifies for the Authorization Parameter: Basic Base64({Appld):{AppSecret})

**Comment by monderino** [comment]
Hey, 

Ah yes. Sorry my bad.
Can you please provide me a full curl command of your request? (Please remove a couple characters from the refresh token) and the url of your helloHQ system or the company of the helloHQ system?

Best 
Sven

**Comment by JonEG** [comment]
@monderino Here you are, please let me know if you need anything else.

Company url: https://medianet.hellohq.io/

Curl example:

```<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => 'https://api.hqlabs.de/Token?grant_type=refresh_token&refresh_token=9drJlgZdYKP2gIucbxpjQPPy0Zp5XOmpHRe6pXGY2pnN1Ds_hMmfGYMeMpvxfd4hbKIsyWhgNQ87VLW9EjUzVgtAy6NejvVLr-tPEj3-bTBjGfTeZkfBernkGkoqpCdjC9MKn5nCwF4yAKrJ-kMb-cn8xYok8MMDmEcR5zmYELC1Lw3M2XllSs',
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => '',
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 0,
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'POST',
  CURLOPT_HTTPHEADER => array(
    'Authorization: Basic NTc3MTU2LWhxLXN5bmM6YkpYcm83Tmk0WHMwbXFiQUJGdE5CM0dGejdtd0V3Mk0='
  ),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response; ```

**Comment by monderino** [comment]
Hi,

**if this is your full refresh token in the example above, then please delete it.**

I tested the whole flow to get my own access and refresh token. For me The call works.
It's important to use exactly the same parameter for scope, redirect_uri as you used in your first calls to get the access token.

Here my example:
<img width="1138" alt="Screenshot 2023-05-15 at 15 29 43" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/5ec0aabe-6dd7-41cf-b9f0-13ea714483d4">

Code:
```

curl --request POST \
  --url https://api.hqlabs.de/Token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data client_id=5... \
  --data 'scope=read_all write_all' \
  --data redirect_uri=http://localhost:8080 \
  --data grant_type=refresh_token \
  --data client_secret=b..... \
  --data refresh_token=9d.......
```

Best Sven

**Comment by JonEG** [comment]
That's what I was missing, thanks!

**Comment by monderino** [comment]
Great ;)

Have a good week.
