### ISSUE TITLE
Access Token Request not working

### ISSUE THREAD

**Issue by mw-aburtscher** [hellohq-io/hellohq.docs#95]
When requesting an access token following the documentation under https://developer.hellohq.io, I get an HTTP 500 error with the 
error message:

_**Customer cannot be null (for api.hqlabs.de)**_
_Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.ArgumentException: Customer cannot be null (for api.hqlabs.de)_

Stack trace:
```
[ArgumentException: Customer cannot be null (for api.hqlabs.de)]

   HQSB.Web.Utils.HQRequestContextStore.GetContext() in D:\a\hq-legacy\hq-legacy\HQSB.Web.Utils\HQRequestContextStore.cs:104

   HQSB.API.MvcApplication.Application_EndRequest(Object sender, EventArgs e) in D:\a\hq-legacy\hq-legacy\HQSB.API\Global.asax.cs:303

   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +223

   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +232

   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +3015
```

These are my request settings - I already changed the authorization header to "Bearer" as "Basic" led to "unsupported_grant_type" error as described here: https://github.com/hellohq-io/hellohq.docs/issues/94
<img width="1694" alt="Screenshot 2023-05-04 at 13 05 12" src="https://user-images.githubusercontent.com/17024901/236189737-81aafaa8-7498-436c-aae3-6619b4708a76.png">

**Comment by monderino** [comment]
Hi @mw-aburtscher,

I'm not sure why you have an Authorization Header in your request? Because the Token-Call is used to generate a new token and deliver it to you.

Did you to an Authorize-Call before?

Best Sven

**Comment by mw-aburtscher** [comment]
Hi Sven, 

yes, I did an authorize call before - that's where I got the value for the code parameter that I'm sending in the token request.
The Authorization Header is mentioned in the documentation for the Access Token Request, that's why I'm sending it. 


<img width="1414" alt="Screenshot 2023-05-05 at 12 35 45" src="https://user-images.githubusercontent.com/17024901/236438282-8d8561cf-23d0-44f3-9201-149885c7e12f.png">

Could you please send me an example request, as the documentation is not clear about parameter spelling and wheter to send parameters in request header or body.

Thanks in advance!

**Comment by monderino** [comment]
Hey,

Yes I will update the documentation.

```
curl --request POST \
  --url https://api.hqlabs.de/Token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data client_id=From helloHQ UI \
  --data 'scope=read_all write_all' \
  --data redirect_uri=https://localhost:8090 \
  --data grant_type=authorization_code \
  --data client_secret=From helloHQ UI \
  --data code=Code form authorize call
```
  
  
  Have a great weekend
