### ISSUE TITLE
API page size when using $expand parameter

### ISSUE THREAD

**Issue by eduardo-9fwr** [hellohq-io/hellohq.docs#96]
**Describe**
I am working with one of your clients to retrieve information from HQ via the API.
We already have a functional model, but now that we are trying to retrieve the Incoming Invoices we are running into time-outs.
The issue seems to be whenever we try to use the $expand=Positions parameter.
This seems to increase the page size to 10k instead of the regular 100 entries when the $expand is not added.

The same code works fine for Invoices, Quotations, and Planned revenues, but is not working for Incoming Invoices.
There are 2k more incoming invoices than Invoices, this is why I would like to limit the page size of the request.

In this case, $skip is not enough and I couldn't find another parameter that would limit the page size.
I did try a bunch of options that work in other APIs.

**Comment by monderino** [comment]
Hi @eduardo-9fwr,

based on our technology, we have no possibility to change this currently.
The only think you can do right now is to increase your timeout.

Is it really necessary to fetch all or can you also filter by a date like the UpdatedOn?

Best
Sven

**Comment by eduardo-9fwr** [comment]
Hi @monderino,

Thanks for the reply.

What you are saying is that there is no way to specify the page size, correct?
Why does the page size increase to 10k when the expand is used? Couldn't this be reduced?

We are currently doing a full refresh every day. So a filter by the UpdaterdOn is not possible.
The workaround that we are using at the moment is to request the Incoming Invoices without the expand and then loop over the ids and request one by one with the expand on the positions. This increased a lot the number of requests and the time the job is taking to complete.

**Comment by monderino** [comment]
Hey,

unfortunately we deliver all incoming invoices. There is currently no other way.
The way we can recommend is to fetch only the incoming invoices which are updated in the last 24h for example and then
request one by one.

Sorry that I can't provide a better solution.

Best Sven

**Comment by monderino** [comment]
Hey,

No, yo have to do this in your code. The default is 60s.

**Comment by eduardo-9fwr** [comment]
Hey @monderino,

I increased the timeout to 1200 seconds, but it is still returning a timeout from the API.

Regarding your suggestion to use the UpdatedOn as a filter: if a position from an incoming invoice is updated. Would the UpdatedOn field from said incoming invoices also change? Otherwise, we would still need to check every single Incoming invoice for a position that was just updated.

**Comment by monderino** [comment]
Hi @eduardo-9fwr,

Ok, sorry I though to increase the timeout will help.
Yes if the position is updated, the update on of the document will also update. Because wie calculate the sum values of the document again.

Best Sven

**Comment by eduardo-9fwr** [comment]
Hi @monderino,

One more question,

If we filter by UpdatedOn and expand the positions, would this reduce the API call response time?
Or the API has to retrieve all the information anyway?
In the latter case, we could hit the timeout again.

**Comment by eduardo-9fwr** [comment]
Even with a filter on UpdatedOn, I am getting a time-out when requesting the positions.
/v1/IncomingInvoices?$filter=UpdatedOn%20ge%202023-05-15%20and%20UpdatedOn%20lt%202023-05-16&$expand=Positions

It seems that the database tries to retrieve all the incoming invoices.
What I am still struggling to understand is why is this only happening to the Incoming Invoices.
Quotations, Invoices, and Planned revenues have doubled the number of positions but are not getting a time-out.

Any ideas on this?

**Comment by monderino** [comment]
Can you please tell me the customer you do the call for? 
Then I can test it on our end.

**Comment by eduardo-9fwr** [comment]
Hi,

Thanks for testing it.
That is what we are doing at the moment (without the date filter)
But it takes around 40 minutes to run. While the rest takes 10.

Could you also check why it takes so long for the incoming invoices + expand on the positions?

**Comment by monderino** [comment]
Hey,

I know why it takes so much time, but can't fixed.
Sorry.
