### ISSUE TITLE
do.CreatePlannedRevenue crashes because accessing the field "Interval" in a Quotation Position is not possible.

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#97]
**Describe the bug**
I tried to call "Quotations(ID)/do.CreatePlannedRevenue for a Quotation that has an "Article" with a "intervall monhtly" Article ID.

The result is:
`"Oops! Sorry, something went wrong. Please contact us in our developer portal at https://developer.helloHQ.io so we can assist you."`

When i edit the Quotation in the Frontend there is a field "Interval". When i change the "Interval" field to "monthly". The call works.

---

When i try to "modify" the Quotation Position with the Interval field i receive:

**"innererror": {
            "message": "position **: The property 'interval' does not exist on type 'HQSB.API.Model.V1.DocumentPosition'.** Make sure to only use property names that are defined by the type.\r\n",
            "type": "",
            "stacktrace": ""
        }**

**To Reproduce**
1. Create a new Quotation

`POST {
    "CompanyId": "67883",
    "Currency": "EUR",
    "DocumentTemplateId": 4065,
    "ContactPersonId": 56354,
    "ProjectId": "101939",
    "Positions": [
        {
            "Type": "Article",
            "Amount": 2,
            "ArticleId": "4025",
        "Text": "Article Position Text",
        "Optional": true,
        "Interval": "Monthly", << this field is only for showing you what i want to do.
            "ProjectId": "101939"
        }
    ]
}`

2. Change the Quotation to Status Sent
3. Call do.CreatePlannedRevenue

**Expected behavior**
I expect to "access" (write and read) the Field "Interval" inside of a document position to access the full workflow of the Planned Revenues. Otherwise its only possible with some Frontend Editing, which breaks the complete Workflow.

**Screenshots**
![Screenshot 2023-05-16 at 16 39 12](https://github.com/hellohq-io/hellohq.docs/assets/41285052/57f2c223-47d8-4afb-b50e-212b9e7fc201)

**Environment (please complete the following information):**
API

**Comment by donnercody** [comment]
I already contacted the customer support, but they told me that only you can help me with the API.

**Comment by donnercody** [comment]
Hi Svenson,

thanks for coming back.

I have tried that, but when i try it, the "PlannedRevenue" has a NetTotal of "0" but the Quotation has a NetTotal. 

I have done the following:

1. Create a Quotation

`POST Quotations

{
    "CompanyId": "67883",
    "Currency": "EUR",
    "DocumentTemplateId": 4062,
    "ContactPersonId": 56354,
    "ProjectId": "101939",
    "Positions": [
        {
            "Type": "Article",
            "Amount": 2,
            "Price": 50,
            "ArticleId": "4025",
        "Text": "Article Position Text"
        }
    ]
}`

2. Set the STatus to "Sent"
3. Called the PlannedRevenue for the quotation created above

`https://api.hqlabs.de/v1/Quotations(114424)/do.CreatePlannedRevenue

{
    "StartDate": "2023-05-17T08:04:29.554Z",
    "EndDate": "2023-08-17T12:04:29.554Z",
    "Interval": "Monthly"
}`

Now here is the result:
![Screenshot 2023-05-17 at 10 41 29](https://github.com/hellohq-io/hellohq.docs/assets/41285052/a6e65f16-f5b9-4207-90d7-ed30be826375)

But in the Quotation its like:
![Screenshot 2023-05-17 at 10 43 20](https://github.com/hellohq-io/hellohq.docs/assets/41285052/66121a86-845c-4b47-9285-499700cc16fd)

**Comment by monderino** [comment]
Hey,

yes ;) I hope you too?
Sorry for the delay. We could not look into it on Friday, but today we definitely check it.

**Comment by donnercody** [comment]
Hi @monderino ,

sounds amazing. I looking forward to the solution that helps us a lot!

Thanks,
Thoren

**Comment by patrickkurras** [comment]
Hi @donnercody, 

I just implemented the solution and it should work tomorrow as Sven explained. 

Best regards,
Patrick

**Comment by donnercody** [comment]
Amazing will try it tomorrow!

**Comment by donnercody** [comment]
Hi @patrickkurras @monderino ,

perfect, for me it works now.

The only problem we have: All the old-api calls (where no interval is set) are now crashing with a 500 status error.

Maybe you should fix that, because other people maybe also getting errors.

Thanks for your fast help!

Thoren

**Comment by monderino** [comment]
Great 🎉
