### ISSUE TITLE
Create a File inside of project via API leads to strange behaviour in frontend

### ISSUE THREAD

**Issue by donnercody** [hellohq-io/hellohq.docs#98]
Hi @monderino 

Sorry for having another question for the API.

**Describe the bug**
We want to create a file inside of the project. Therefore we try to POST against the file endpoint and then do "do.Upload" for the created File.

**To Reproduce**
1. POST against the Projects(X)/Files

`POST https://api.hqlabs.de/v1/Projects(xx)/Files 
  {"Name": "Vertrag 3.pdf"}`

2. Look into the frontend:

![Screenshot 2023-05-22 at 13 06 56](https://github.com/hellohq-io/hellohq.docs/assets/41285052/8462c928-9434-4440-81d2-687327c35f23)

When i click on "Vertrag 3.pdf".

![Screenshot 2023-05-22 at 13 07 00](https://github.com/hellohq-io/hellohq.docs/assets/41285052/cebe2aee-555c-49ff-9b26-268b5cc9dffe)

**Expected behavior**
I want to edit or download the uploaded file. But files created via API are not accessible via frontend.

Files that are uploaded via the frontend work fine.

![Screenshot 2023-05-22 at 13 18 05](https://github.com/hellohq-io/hellohq.docs/assets/41285052/4cb29046-ca1f-40d7-b259-234abb6c60e0)

**Environment (please complete the following information):**
API

**Comment by monderino** [comment]
Hey ;)

can you please provide a curl for me, then I will check what happen.

**Comment by donnercody** [comment]
Hei @monderino ,

i uploaded the File via the "/v1/Files". But the problem already occurs if i do not upload anything and only create a "empty file" where "hasContent" is False. Then the File is empty and i see it in the frontend, but i cant click on it.

When i then upload it, i got the same issue in the frontend.

I only did this and then the file isnt selectable or is "hidden" in the frontend when you click on it.

`curl --location 'https://api.hqlabs.de/v1/Projects(101956)/Files' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <TOKEN> \
--data '{
    "Name": "Vertrag 3.pdf"
}'`

Thanks,
Thoren

**Comment by monderino** [comment]
Hi,

This is not how it works, sorry. It's only to connect already existing files with the specified project.

**Comment by donnercody** [comment]
Hi @monderino , 

Hmm. 

I have tried to create the File first via the /File endpoint. Then uploaded the Data via do.Upload.

And then i have called the request above with the File.Id but it doesnt work that way. Same Result.

Can you explain me how the workflow correctly works?

Thanks,
Thoren

**Comment by monderino** [comment]
Hey,

You can do a post v1/Files to create a file entity in our system. Here you can connect the file to the project via the file relations.
Then you do to v1/Files(id)/do.Upload to add the binary content.

That should be all.

Best 
Sven

**Comment by donnercody** [comment]
I will try and give you feedback!

**Comment by donnercody** [comment]
Sorry, try to check it till end of week.

**Comment by Schaukelking** [comment]
Hey @donnercody , i guess i will close this thread due to lack of activity. If you are not happy with it just comment in here again.

Kind regards
Patrick

**Comment by donnercody** [comment]
Hi @Schaukelking ,

i have tried to do it as you said, but the same strange behaviour exists.

1) I create a FIle with a FileRelation
curl --location 'https://api.hqlabs.de/v1/Files' \
--header 'Content-Type: application/json' \
--data '{
    "Name": "test vertrag 3.pdf",
    "FileRelations": [
        {
            "ProjectId": 104031
        }
    ]
}'

2) Then i upload the data via "do.Upload"

3) After checking it again:
The Result is:
{
    "@odata.context": "http://api.hqlabs.de/v1/$metadata#Files/$entity",
    "Name": "test vertrag 3.pdf",
    "Size": null,
    "HasContent": false,
    "IsDirectory": false,
    "DirectoryId": null,
    "Id": 114623,
    "CreatedBy": 11010,
    "UpdatedBy": 11010,
    "CreatedOn": "2023-09-15T12:52:35.4663317Z",
    "UpdatedOn": "2023-09-15T12:52:35.4663317Z"
}

But inside of the project it doesnt exist:
![Screenshot 2023-09-15 at 14 57 37](https://github.com/hellohq-io/hellohq.docs/assets/41285052/b4714b1f-7c01-43c3-ac41-7f1868ab235f)


Then i tried it as i said in this Ticket via the "projects/Files" endpoint.

1) curl --location 'https://api.hqlabs.de/v1/Projects(104031)/Files' \
--header 'Content-Type: application/json' \
--data '{
    "Name": "test vertrag 3.pdf"
    }'

2) Then i upload via the "/FIle().doUpload"

3) Than it works fine:
![Screenshot 2023-09-15 at 14 59 33](https://github.com/hellohq-io/hellohq.docs/assets/41285052/8d07ce9b-c41f-4ae2-b15e-9a8b970c5e6c)


4) BUT THEN: When i "click" on any of these Buttons, the file disappeared in the frontend and the file is not downloadable.

![Screenshot 2023-09-15 at 14 59 49](https://github.com/hellohq-io/hellohq.docs/assets/41285052/36490ec5-7fa4-4af1-8cca-9f44c1a58fbd)


Thanks for your help.

**Comment by donnercody** [comment]
@monderino could you please check this ticket again?

**Comment by monderino** [comment]
@donnercody 
I will check this tomorrow.

**Comment by monderino** [comment]
Hi @donnercody,

I tested it with postman now. And all looked good so far.
I added files, a folder and binary data:
<img width="812" alt="Screenshot 2023-09-26 at 13 49 01" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/297fe623-8c89-40e8-80b7-d3ab5574d685">
<img width="920" alt="Screenshot 2023-09-26 at 13 50 30" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/93409b6f-ce42-41aa-82df-f58a99fdb7b1">
<img width="1326" alt="Screenshot 2023-09-26 at 13 52 31" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/c39f740c-211d-4d20-81f9-b25355e060f3">
<img width="1247" alt="Screenshot 2023-09-26 at 13 56 02" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/5de16b94-e33f-49b5-94bc-6aa0cceab154">

And they showed up in the UI
<img width="1189" alt="Screenshot 2023-09-26 at 13 58 17" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/071e71d2-60ef-4d9a-8f58-ee42789ce874">
<img width="1209" alt="Screenshot 2023-09-26 at 13 58 08" src="https://github.com/hellohq-io/hellohq.docs/assets/23459030/43b49cfc-5caa-4e78-8189-47727b0f554b">

I detected one issue in the UI. When I clicked the FileFromAPi_root, then it disappear from the menu. But it show up again after reload.

Please reopen to issue if you have more questions.

Best Sven
